<?php

return [

    'before_storm' => [

        'title' => 'Before the Storm',

        'subtitle' => 'Before the Storm',

        'intro' => 'Before war reached Hong Kong, the city was more than a British colonial port in the Far East. Positioned at the crossroads of South China, Southeast Asia, and major international shipping routes, Hong Kong had become an important centre for trade, transportation, communications, and regional exchange. As China\'s War of Resistance against Japanese Aggression intensified, the colony increasingly served as a gathering point for supplies, news, refugees, and wartime relief efforts.',

        'battle_tab_1' => 'Before the Storm',
        'battle_tab_2' => 'Eighteen Days of Battle',
        'battle_tab_3' => 'Black christmas', 
        'battle_tab_4' => 'Wartime Timeline',


        'section_1_title' => 'Hong Kong on the Eve of War',
        'section_1_p1' => 'Long before the outbreak of the Pacific War, Hong Kong was no longer insulated from the growing conflict in East Asia. Following the Mukden Incident in 1931, Japan gradually expanded its control over northeastern China. After the Marco Polo Bridge Incident in 1937, full-scale war broke out between China and Japan, spreading from North China into the Yangtze Valley and eventually South China. In October 1938, Japanese forces landed in Bias Bay (Daya Bay) and subsequently captured Guangzhou, dramatically altering the strategic situation in southern China.',
        'section_1_p2' => 'The fall of Guangzhou further heightened Hong Kong\'s significance. On one hand, it remained a major port, financial centre, and transportation hub for South China. On the other, it became a refuge for intellectuals, journalists, political activists, anti-Japanese supporters, and civilians fleeing the conflict. While daily life continued and the city\'s commercial activities appeared outwardly unchanged, growing tensions could be felt beneath the surface. Concerns over supply lines, border security, air-raid precautions, military preparations, and civilian relief efforts became increasingly prominent as the prospect of war drew nearer.',

        'section_2_title' => 'South China and Hong Kong\'s Strategic Importance',
        'section_2_p1' => 'Hong Kong occupied a unique position at the gateway to the South China Sea. Backed by Guangdong Province and facing the sea lanes of Southeast Asia, it held strategic value far beyond its size. For Britain, Hong Kong formed part of its wider Far Eastern imperial network and served as an important outpost linking South China and Southeast Asia. For Japan, however, Hong Kong represented a strategic objective that would need to be secured once war expanded across the Pacific. Sources associated with the Hong Kong and Kowloon Brigade have also emphasized Hong Kong\'s importance as a transportation hub and naval staging point within Japan\'s wartime network. Its harbour, communications infrastructure, and location made it valuable both for operations against China and for future military campaigns in Southeast Asia.',
        'section_2_p2' => 'This geography placed Hong Kong under immense pressure even before the fighting began. Situated adjacent to Japanese-controlled territory while serving as Britain\'s eastern outpost, the colony occupied a position of strategic vulnerability. If war came, its harbour facilities, airport, warehouses, and communications systems would become assets of considerable military value. Hong Kong was therefore never merely a local battlefield. It was a strategic crossroads linking the China theatre, the Pacific theatre, and Southeast Asia. Its eventual fall would have consequences extending far beyond the territory itself.',

        'section_readmore' => 'Continue Reading',

        'model_section_1_title' => 'A Colony Considered Difficult to Defend',
        'model_section_1_p1' => 'Despite its strategic importance, British assessments of Hong Kong\'s military prospects remained deeply conflicted. Britain was unwilling to abandon Hong Kong, both for strategic reasons and because of its symbolic importance within the Empire. Yet limited military resources, the growing demands of the war in Europe, and the priority placed on the defence of Singapore meant that Hong Kong was often regarded as difficult—if not impossible—to defend for an extended period. According to Veterans Affairs Canada, British authorities recognised Hong Kong\'s vulnerability by 1941 and sought to reinforce the colony in the hope of deterring Japanese aggression or, at the very least, delaying an invasion.',
        'model_section_1_p2' => 'This contradiction—knowing Hong Kong would be difficult to defend, yet feeling compelled to defend it—formed the foundation of the colony\'s wartime strategy. The defenders were not entirely unprepared, but they faced significant limitations in manpower, equipment, terrain, and logistics. Once Hong Kong\'s sea and air connections were severed, outside assistance would be difficult to obtain. Meanwhile, the proximity of Japanese-controlled territory to the north meant that any invasion could develop rapidly. The defence of Hong Kong was therefore never intended to be a battle of equal forces. It was, above all, an effort to delay, resist, and impose costs on an enemy that enjoyed considerable strategic advantages.',

        'model_section_2_title' => 'The Gin Drinkers Line and the Defence of the New Territories',
        'model_section_2_p1' => 'In preparation for a possible invasion from the north, British forces constructed a defensive system stretching across the hills between the New Territories and Kowloon. Known as the Gin Drinkers Line, it consisted of machine-gun positions, trenches, observation posts, and fortified strongpoints built into the surrounding terrain. One of its most important positions was the Shing Mun Redoubt, located near the Shing Mun Reservoir. Before the war, it was regarded as a key anchor point in Hong Kong\'s land defences.',
        'model_section_2_p2' => 'Despite its strategic role, the Gin Drinkers Line had significant limitations. Unlike the large fortified defensive systems found in Europe, it relied on relatively small garrisons dispersed across rugged terrain. Its effectiveness depended heavily on troop strength, communications, reinforcement capability, and the defenders\' ability to fight at night. Official military records indicate that, by the morning of 8 December 1941, three infantry battalions had taken up positions along the line, including units from the Royal Scots, the Punjab Regiment, and the Rajput Regiment. Even so, the line\'s ability to withstand a determined assault remained uncertain.',

        'model_section_3_title' => 'The Defenders and Reinforcements',
        'model_section_3_p1' => 'Hong Kong\'s defenders came from a diverse range of military backgrounds. British regular troops, Indian Army units, Canadian reinforcements, the Hong Kong Volunteer Defence Corps, and numerous support personnel all formed part of the colony\'s defensive force. This multinational composition reflected both Hong Kong\'s status as an international port and the broader realities of British defence planning in the Far East.',
        'model_section_3_p2' => 'In November 1941, Canada dispatched C Force to reinforce Hong Kong. The contingent included the Royal Rifles of Canada and the Winnipeg Grenadiers. According to Veterans Affairs Canada, 1,975 Canadian soldiers departed Vancouver in late October 1941 and arrived in Hong Kong on 16 November, joining a defensive force numbering approximately 14,000 personnel. The Hong Kong Museum of Coastal Defence notes that these reinforcements arrived only weeks before the outbreak of war. Many of the soldiers were young, had limited combat experience, and were unfamiliar with Hong Kong\'s terrain.',

        'model_section_4_title' => 'Cities, Villages, and the Foundations of Resistance',
        'model_section_4_p1' => 'Before the war, Hong Kong was more than a military outpost. It was a densely populated society with complex urban and rural networks. Hong Kong Island and Kowloon served as political, commercial, and transportation centres, while the New Territories consisted of villages, hills, islands, and coastal communities. This geography would later play a crucial role in shaping the character of resistance during the occupation. Although Japanese forces would rapidly seize major urban centres and transportation routes, the mountains, islands, fishing communities, and rural villages of the New Territories provided opportunities for underground communications, intelligence gathering, rescue operations, and guerrilla warfare.',
        'model_section_4_p2' => 'Even before the invasion, Communist-led anti-Japanese guerrilla forces in Guangdong were closely monitoring developments in Hong Kong. Anticipating a Japanese attack, they recognised that occupied Hong Kong could become an important rear-area battlefield. According to The History of the Hong Kong and Kowloon Brigade (《港九大隊志》), units from the Third and Fifth Brigades of the Guangdong People\'s Anti-Japanese Guerrilla Forces entered the New Territories shortly after the outbreak of war. Their tasks included suppressing bandit activity, collecting weapons abandoned by retreating Allied forces, promoting anti-Japanese resistance, and encouraging local villagers to defend their communities. These early activities laid important foundations for the later establishment of the Hong Kong and Kowloon Brigade and the continuation of organised resistance during the occupation.',

        'model_section_5_title' => 'War Approaches Hong Kong',
        'model_section_5_p1' => 'By the second half of 1941, tensions across East Asia had reached a critical point. Relations between Japan, Britain, and the United States continued to deteriorate, and the prospect of war in the Pacific became increasingly likely. For the people of Hong Kong, the threat of conflict was no longer confined to newspaper headlines. Air-raid drills, military movements, price fluctuations, refugee arrivals, and reports from the border all served as reminders that Hong Kong could soon become a battlefield.',
        'model_section_5_p2' => 'On 8 December 1941, those fears became reality. According to the Hong Kong Museum of History, Japanese forces occupied Hong Kong following eighteen days of fighting between 8 and 25 December 1941. Veterans Affairs Canada likewise records that Japanese aircraft attacked Kai Tak Airport on the opening day of the campaign while ground forces crossed the border and advanced south through the New Territories. From that moment onward, Hong Kong ceased to be a tense frontier city and became an active battlefield. Civilians, soldiers, rural communities, and resistance networks alike were drawn into a conflict that would reshape the territory\'s history.',

        'model_section_6_title' => 'Conclusion: Understanding the Origins of the Battle',
        'model_section_6_p1' => 'The Battle of Hong Kong did not begin with the first shots fired on 8 December 1941. Its origins lay in Japan\'s invasion of China, the fall of Guangzhou, the deteriorating situation in South China, Britain\'s strategic challenges in the Far East, and Hong Kong\'s own geographical position. The territory became a battlefield not by chance, but because its harbour, shipping routes, border, cities, and rural communities occupied a strategic position in East Asia on the eve of the Pacific War.',
        'model_section_6_p2' => 'Understanding this background helps explain why Hong Kong\'s defenders fought in isolation, why the geography of the New Territories and Kowloon proved so important, and why organised resistance continued long after the colony\'s surrender. Before the war, Hong Kong stood both as an outpost of the British Empire and as a frontier connected to the wider Chinese war effort. When the conflict finally arrived, every road, ridge, harbour, and village would become part of one of the most significant chapters in Hong Kong\'s wartime history.',

        // tab 2
        'battle_process_title' => 'Eighteen Days of Battle',
        'battle_process_subtitle' => 'Eighteen Days of Battle',
        'battle_process_intro' => 'In December 1941, Japanese forces launched an invasion of Hong Kong from the north, advancing through the New Territories, Kowloon, and ultimately Hong Kong Island. Over the course of just eighteen days, soldiers and civilians alike endured air raids, withdrawals, street fighting, and the mounting pressure of defending an increasingly isolated territory.',

        'battle_process_section_1_title' => 'An Eighteen-Day Battle from North to South',
        'battle_process_section_1_p1' => 'At dawn on 8 December 1941, Japanese troops crossed the Shenzhen River, marking the beginning of the Battle of Hong Kong. The attack coincided with the outbreak of the wider Pacific War, as Japan launched coordinated offensives against British and American positions across the region. Hong Kong became one of the first targets in this broader campaign. The invasion began with air strikes on Kai Tak Airport, crippling much of Hong Kong\'s limited air capability. Japanese forces then advanced southward through the New Territories. What had long been regarded as a vulnerable frontier suddenly became an active battlefield.',
        'battle_process_section_1_p2' => 'The campaign lasted eighteen days, stretching from the New Territories through Kowloon and finally onto Hong Kong Island. Although the defenders faced overwhelming disadvantages in manpower, firepower, air support, and supplies, they continued to resist at numerous positions. The Battle of Hong Kong was not a single engagement, but a series of defensive actions, withdrawals, urban battles, and mountain engagements fought across the territory. As Japanese forces steadily advanced, the defenders fought within an ever-shrinking perimeter until 25 December 1941, when Governor Sir Mark Young announced Hong Kong\'s surrender. The city then entered three years and eight months of Japanese occupation.',

        'battle_process_section_2_title' => 'Across the Shenzhen River: The Invasion Begins',
        'battle_process_section_2_p1' => 'The Japanese assault began with a southward advance across the Shenzhen River. Because the New Territories bordered Japanese-controlled areas of South China, Hong Kong\'s land defences came under immediate pressure. Japanese units advanced along multiple routes through Yuen Long, Sheung Shui, Fanling, Sha Tau Kok, and Tai Po, with the objective of breaking through the New Territories and reaching Kowloon. At the same time, the bombing of Kai Tak Airport severely weakened Hong Kong\'s already limited air defences.',
        'battle_process_section_2_p2' => 'The defenders\' primary task in the New Territories was to delay the Japanese advance and buy time for a withdrawal to prepared defensive positions further south. However, with superior artillery, air support, and operational initiative, the Japanese quickly gained the upper hand. As the fighting intensified, British and Commonwealth forces gradually withdrew toward the Gin Drinkers Line, the colony\'s principal defensive system north of Kowloon.',

        'battle_process_model_section_1_title' => 'The Fall of the Gin Drinkers Line',
        'battle_process_model_section_1_p1' => 'The Gin Drinkers Line stretched across the hills north of Kowloon and was supported by a network of bunkers, trenches, strongpoints, and communication routes. It was intended to prevent Japanese forces from reaching Kowloon and to buy valuable time for the defence of Hong Kong Island. At the centre of the line stood the Shing Mun Redoubt, one of its most important defensive positions.',
        'battle_process_model_section_1_p2' => 'Events unfolded far more rapidly than anticipated. During the night of 9–10 December 1941, Japanese troops launched a surprise assault on the Shing Mun Redoubt. Its capture undermined the entire defensive system, making continued resistance along the Gin Drinkers Line impossible.',
        'battle_process_model_section_1_p3' => 'The collapse of the line marked the first major turning point of the campaign. What had been expected to delay the Japanese advance for days was breached within a short period, forcing the defenders to abandon northern Kowloon and begin a fighting withdrawal. From this point onward, the battle was no longer about holding the New Territories, but about preserving the ability to continue resistance from Hong Kong Island.',

        'battle_process_model_section_2_title' => 'The Withdrawal from Kowloon',
        'battle_process_model_section_2_p1' => 'Following the loss of the Gin Drinkers Line, Allied forces began withdrawing from Kowloon to Hong Kong Island. Remaining in Kowloon risked trapping troops against the shoreline and preventing an orderly evacuation. Military commanders therefore decided to concentrate their remaining forces on the island, where Victoria Harbour offered a natural defensive barrier.',
        'battle_process_model_section_2_p2' => 'The withdrawal was a difficult and dangerous operation. Troops, equipment, and supplies had to be transported across the harbour while Japanese forces continued their advance. For civilians, the war now felt closer than ever. The fighting had moved from the New Territories into Kowloon, and the threat to Hong Kong Island was becoming increasingly apparent. Familiar streets were transformed by air-raid sirens, military checkpoints, artillery fire, and growing numbers of refugees.',
        'battle_process_model_section_2_p3' => 'By mid-December, Kowloon had fallen. Hong Kong Island became the colony\'s final major defensive position.',

        'battle_process_model_section_3_title' => ' Victoria Harbour: The Last Barrier',
        'battle_process_model_section_3_p1' => 'The defence of Hong Kong Island relied on coastal batteries, mountain strongholds, roadblocks, and infantry positions. Military planners hoped that Victoria Harbour would prevent a Japanese crossing while the island\'s rugged terrain could be used to slow any advance. However, once Kowloon had fallen, Japanese forces were able to observe and bombard positions across the harbour. Continuous artillery fire placed increasing strain on the defenders.',
        'battle_process_model_section_3_p2' => 'Before launching an amphibious assault, the Japanese subjected the island to sustained shelling and air attacks. Meanwhile, the defenders struggled with worsening shortages of supplies, disrupted communications, mounting casualties, and increasing pressure on medical facilities. As food, water, and ammunition became scarce, both soldiers and civilians were forced to endure growing hardship. The battle had become more than a military contest; it was now a question of how long the city could withstand siege conditions.',

        'battle_process_model_section_4_title' => 'The Landing on Hong Kong Island',
        'battle_process_model_section_4_p1' => 'On the evening of 18 December 1941, Japanese forces crossed Victoria Harbour and landed on the northern shore of Hong Kong Island. Heavy fighting soon erupted across North Point, Quarry Bay, Taikoo, Wong Nai Chung Gap, Repulse Bay, and Stanley. The island\'s complex geography of ridges, valleys, roads, and coastlines fragmented the battlefield, creating numerous isolated engagements. Communication between defensive positions was frequently disrupted, leaving units to fight independently.',
        'battle_process_model_section_4_p2' => 'Among the fiercest battles were those fought around Wong Nai Chung Gap, a strategic corridor linking the northern and southern parts of the island. Determined resistance was met by repeated Japanese infiltration and flanking attacks, gradually splitting the defenders\' positions. British, Canadian, Indian, and Hong Kong Volunteer Defence Corps units fought across the island, suffering heavy casualties. Many were killed, wounded, or taken prisoner. According to the Commonwealth War Graves Commission (CWGC), the Sai Wan War Cemetery serves as the final resting place and memorial for many Commonwealth servicemen who lost their lives during the Battle of Hong Kong or while held as prisoners of war, reflecting the heavy human cost of the campaign.',
        
        'battle_process_model_section_5_title' => 'Isolation and Collapse',
        'battle_process_model_section_5_p1' => 'Following the landings, the island\'s defensive network became increasingly fragmented. Although resistance continued in many areas, effective coordination and reinforcement became progressively more difficult. Japanese forces captured key high ground and transportation routes, isolating defensive sectors from one another.',
        'battle_process_model_section_5_p2' => 'Hospitals, temporary aid stations, and residential neighbourhoods were drawn into the fighting, resulting in significant civilian suffering. By the final days of the battle, the defenders faced a combination of severe challenges: lost positions, dwindling ammunition, shortages of food and water, growing numbers of wounded personnel, damaged communications, and the absence of external reinforcements. Even so, resistance continued until the very end. Forces in Stanley, in particular, held out almost until the moment of surrender, demonstrating that the defence of Hong Kong did not collapse suddenly but continued under increasingly desperate circumstances.',

        'battle_process_model_section_6_title' => 'Christmas Day Surrender: The Beginning of a Dark Era',
        'battle_process_model_section_6_p1' => 'By 25 December 1941, the military situation had become untenable. That afternoon, Governor Sir Mark Young and Major-General Christopher Maltby formally surrendered Hong Kong to Japanese forces. The day would later become known as "Black Christmas." For Hong Kong, the surrender represented more than a military defeat. It marked the end of one era and the beginning of another, as British colonial administration was replaced by Japanese occupation. The occupation would last for three years and eight months.',
        'battle_process_model_section_6_p2' => 'Yet the fall of Hong Kong did not mark the end of resistance. Following the surrender of British and Commonwealth forces, organised opposition to Japanese occupation increasingly shifted to local resistance networks and Chinese guerrilla forces. Among the most significant were the Dongjiang Column and its Hong Kong and Kowloon Brigade, Communist-led anti-Japanese units that continued operating in and around Hong Kong throughout the occupation. Their activities included intelligence gathering, rescue operations, sabotage, and support for Allied personnel and local civilians. Their efforts would pave the way for the stories that followed: secret rescue operations, intelligence networks, guerrilla warfare, maritime missions, and civilian support activities that became a defining part of Hong Kong\'s wartime resistance.',

        'battle_process_model_section_7_title' => 'Conclusion: A Defeat that Marked the Beginning of Resistance',
        'battle_process_model_section_7_p1' => 'The Battle of Hong Kong ended in military defeat, but its legacy remains deeply embedded in Hong Kong\'s history. In just eighteen days, the territory witnessed invasion, retreat, urban warfare, and eventual surrender. The campaign exposed the vulnerabilities of Britain\'s Far Eastern defences while also highlighting the determination of those who fought despite overwhelming odds.',
        'battle_process_model_section_7_p2' => 'More importantly, the battle was not the end of Hong Kong\'s wartime story—it was the beginning. As conventional military resistance collapsed, Hong Kong\'s mountains, villages, coastlines, and urban neighbourhoods became the setting for a different kind of struggle. Rescue operations, intelligence work, guerrilla actions, underground networks, maritime transport, and civilian support would together form the next chapter of Hong Kong\'s resistance during the years of Japanese occupation.',

        //tab 3
        'black_christmas_title' => 'Black Christmas',
        'black_christmas_subtitle' => 'Black Christmas',
        'black_christmas_intro' => 'On 25 December 1941, Hong Kong surrendered to Japanese forces. The day would later become known as "Black Christmas", marking both the end of the Battle of Hong Kong and the beginning of three years and eight months of Japanese occupation.',

        'black_christmas_section_1_title' => 'The Fall of a City',
        'black_christmas_section_1_p1' => 'Christmas Day 1941 remains one of the darkest dates in Hong Kong\'s history. After eighteen days of fighting across the New Territories, Kowloon, and Hong Kong Island, the defenders had exhausted their ability to continue resistance. Facing overwhelming disadvantages in manpower, firepower, air support, supplies, and the absence of external reinforcements, the outcome had become unavoidable. On that day, Governor Sir Mark Young and Major-General Christopher Maltby, commander of British forces in Hong Kong, formally surrendered to the Japanese. The territory fell under occupation, and what Hong Kong people would later remember as Black Christmas began.',
        'black_christmas_section_1_p2' => 'The significance of Black Christmas extended far beyond military defeat. For the civilian population, it marked the collapse of the existing order. Government authority ceased to function, military occupation began, and everyday life entered an uncertain future. Although the fighting was coming to an end, a far longer and darker chapter was only beginning.',

        'black_christmas_section_2_title' => 'The Christmas Day Surrender',
        'black_christmas_section_2_p1' => 'By Christmas Day 1941, the defence of Hong Kong had reached its breaking point. Following the Japanese landings on Hong Kong Island on 18 December, the defenders came under relentless pressure. Japanese forces captured key roads, strategic high ground, and communication routes, dividing the island\'s defensive positions and isolating many units from one another. Ammunition, fresh water, medical supplies, and manpower were running dangerously low, while the number of wounded continued to rise. According to records from Veterans Affairs Canada, Allied forces had suffered devastating casualties after more than seventeen days of continuous fighting. Exhausted, outnumbered, and cut off from any realistic prospect of reinforcement, the defenders could no longer sustain an effective defence. For many Canadian soldiers, surrender marked the beginning of more than three years of captivity in prisoner-of-war camps in Hong Kong and Japan.',
        'black_christmas_section_2_p2' => 'On the afternoon of 25 December 1941, Governor Sir Mark Young and Major-General Christopher Maltby formally surrendered Hong Kong to Japanese forces. The surrender ceremony took place at the Peninsula Hotel in Tsim Sha Tsui. The 80th Anniversary Commemorative Publication of the Hong Kong and Kowloon Brigade also records the event, noting that British forces announced their surrender on 25 December 1941 and identifying the scene as the surrender ceremony inside the Peninsula Hotel. For those living through the events of that day, the surrender was more than a military decision. It marked the end of the Battle of Hong Kong and the beginning of an uncertain future under occupation. Although the sound of gunfire was beginning to fade, the hardships of war were far from over.',

        'black_christmas_model_section_1_title' => 'From Battlefield to Occupation',
        'black_christmas_model_section_1_p1' => 'The end of the fighting did not bring an end to suffering. For many soldiers, surrender was followed by years of imprisonment. For civilians, life under occupation brought a new and uncertain reality: arrests, restrictions, shortages, and fear. The city that had once thrived as an international trading port was absorbed into Japan\'s wartime occupation system, and key infrastructure—including ports, warehouses, roads, ships, factories, and supplies—came under military control.',
        'black_christmas_model_section_1_p2' => 'The occupation authorities quickly established a system of military rule. Movement was restricted, while the press, public speech, public gatherings, transportation, and food distribution were placed under strict supervision. Many residents were forced to leave the urban areas, returning to mainland China or rural communities. Others lost family members to war, hunger, disease, violence, or the wider consequences of occupation. According to the Hong Kong Museum of History, the eighteen days of fighting from 8 to 25 December 1941 marked the process by which Japanese forces occupied Hong Kong. This period would later become one of the most traumatic chapters in Hong Kong\'s Second World War memory. The Battle of Hong Kong had ended, but a new period of hardship had begun.',

        'black_christmas_model_section_2_title' => 'The Human Cost of War',
        'black_christmas_model_section_2_p1' => 'The Battle of Hong Kong exacted a heavy toll on both soldiers and civilians. The defenders included British, Canadian, Indian, and Hong Kong Volunteer Defence Corps personnel, along with numerous supporting units. Many were killed, wounded, or taken prisoner during the campaign. Today, the sacrifice of those who fought is commemorated at military cemeteries across Hong Kong, including the Sai Wan War Cemetery. According to the Commonwealth War Graves Commission (CWGC), the cemetery honours many Commonwealth servicemen who died during the Battle of Hong Kong or while held as prisoners of war, serving as a lasting reminder of the human cost of the campaign.',
        'black_christmas_model_section_2_p2' => 'Civilians suffered as well. Artillery bombardments, air raids, street fighting, and military occupation shattered the sense of security that many had once taken for granted. Families were displaced, homes were destroyed, and shortages of food and medical care became increasingly severe. For ordinary residents, Black Christmas was not simply a date in military history—it marked the beginning of a profound disruption to daily life.',

        'black_christmas_model_section_3_title' => 'The Collapse of the City\'s Order',
        'black_christmas_model_section_3_p1' => 'Following the surrender, the colonial administration ceased to function, and Japanese military authorities assumed control of the city. Banks, schools, newspapers, businesses, hospitals, and public institutions all experienced disruption to varying degrees. Access to currency, employment, food supplies, transportation, and healthcare became increasingly uncertain.',
        'black_christmas_model_section_3_p2' => 'Hong Kong was no longer the free and prosperous port city it had been before the war. Although the harbour remained strategically important, its role was redirected toward military and occupation needs. Familiar urban spaces—including streets, docks, warehouses, and schools—were repurposed to serve the priorities of the occupying authorities. The routines of everyday life became subordinate to the demands of war.',

        'black_christmas_model_section_4_title' => 'The Meaning of "Black Christmas"',
        'black_christmas_model_section_4_p1' => 'The term Black Christmas remains powerful because of its striking contrast. Christmas is traditionally associated with peace, family, and hope. Yet in Hong Kong, Christmas Day 1941 brought surrender, occupation, and uncertainty. The sounds of celebration were replaced by the sounds of war—gunfire, military movements, and the grief of those who had lost loved ones.',
        'black_christmas_model_section_4_p2' => 'For many families, it was not a holiday but the beginning of fear and instability. Over time, Black Christmas became one of the defining symbols of Hong Kong\'s wartime memory. It represents not only military defeat, but also the moment when the destiny of an entire city was abruptly transformed by war.',

        'black_christmas_model_section_5_title' => 'Resistance Continues',
        'black_christmas_model_section_5_p1' => 'Although Hong Kong had surrendered, resistance did not end. With the collapse of conventional military defences, the struggle against Japanese occupation increasingly shifted from open warfare to underground resistance. Intelligence gathering, rescue operations, guerrilla activities, sabotage, and civilian support networks gradually replaced conventional battlefield operations. Among the most important resistance forces were units associated with the Chinese Communist Party, particularly the Dongjiang Column and its Hong Kong and Kowloon Brigade. Established on 3 February 1942 in Wong Mo Ying Village, Sai Kung, the Hong Kong and Kowloon Brigade became the principal organised anti-Japanese force operating in occupied Hong Kong. Throughout the three years and eight months of occupation, it remained one of the few structured resistance organisations to maintain continuous operations against Japanese rule.',
        'black_christmas_model_section_5_p2' => 'As a result, Black Christmas marked not only the fall of Hong Kong, but also the beginning of a new phase of resistance. Across the city\'s urban districts, rural villages, mountain paths, and coastal waters, new networks emerged to continue the struggle in different forms. The stories of secret rescue missions, intelligence cooperation, guerrilla warfare, maritime operations, and civilian support would all grow from this turning point in Hong Kong\'s wartime history.',

        'black_christmas_model_section_6_title' => 'Conclusion: A Turning Point in the Darkness',
        'black_christmas_model_section_6_p1' => 'On 25 December 1941, Hong Kong entered one of the darkest periods in its history. The day brought an end to the eighteen-day Battle of Hong Kong and ushered in more than three years of Japanese occupation. For many residents, it was the first direct encounter with the realities of global war and the challenges of living under foreign military rule.',
        'black_christmas_model_section_6_p2' => 'Yet Black Christmas is remembered not only as a symbol of defeat and suffering. It also serves as a reminder that Hong Kong\'s wartime story did not end with surrender. As conventional military resistance disappeared, underground networks, rural communities, maritime routes, and civilian support systems became the foundation of continued opposition. In the years that followed, Hong Kong\'s resistance would enter a more hidden, more difficult, and ultimately more enduring phase—one that revealed the resilience and determination of those who refused to abandon the struggle.',

        //tab 4
        'wartime_timeline_title' => 'Wartime Timeline',
        'wartime_timeline_subtitle' => 'Wartime Timeline',
        'wartime_timeline_intro' => 'From the outbreak of the Second Sino-Japanese War to the fall of Hong Kong and the emergence of resistance behind enemy lines, this timeline traces how Hong Kong became drawn into the wider conflict of the Second World War. It serves as a reminder that the Battle of Hong Kong was not merely an eighteen-day campaign, but the beginning of a broader story of war, occupation, and resistance.',

        'wartime_timeline_1937_title' => 'Full-Scale War Breaks Out in China',
        'wartime_timeline_1937_desc' => 'The Marco Polo Bridge Incident on 7 July 1937 marked the beginning of full-scale war between China and Japan. Although Hong Kong remained a British colony and was not yet directly involved in the fighting, the territory quickly became connected to events on the mainland. Refugees, intellectuals, journalists, and political activists arrived in Hong Kong in large numbers, transforming the colony into an important centre for wartime news, relief efforts, material support, and cultural exchange. During these years, Hong Kong was no longer simply a port city observing events from a distance. It increasingly became an important rear-area hub supporting China\'s war effort.',

        'wartime_timeline_1938_title' => 'The Fall of Guangzhou Brings War to Hong Kong\'s Doorstep',
        'wartime_timeline_1938_desc' => 'In October 1938, Japanese forces landed in South China and captured Guangzhou, dramatically increasing the strategic pressure on Hong Kong. The occupation of Guangzhou placed much of South China\'s transportation network under Japanese control and disrupted important supply routes linking China with the outside world through Hong Kong and Macau. Hong Kong was no longer a distant commercial port but a frontier city facing a direct military threat. As Japan expanded southward and sought greater control over the South China Sea, Hong Kong became an increasingly important strategic objective.',

        'wartime_timeline_1941_1208_title' => 'Japan Invades Hong Kong',
        'wartime_timeline_1941_1208_desc' => 'On the morning of 8 December 1941, Japanese forces crossed the Shenzhen River and launched their invasion of Hong Kong, marking the beginning of the Battle of Hong Kong. Japanese aircraft simultaneously attacked Kai Tak Airport, rapidly weakening the colony\'s limited air defences. Despite being heavily outmatched in manpower, firepower, and air support, the defenders attempted to slow the Japanese advance through the northern New Territories by making use of defensive positions and difficult terrain. The invasion drew Hong Kong directly into the Pacific War and marked the beginning of eighteen days of fighting.',

        'wartime_timeline_1941_1210_title' => 'The New Territories Defences Are Breached',
        'wartime_timeline_1941_1210_desc' => 'Japanese forces advanced rapidly following the opening stages of the campaign. Although defensive preparations had been made in the New Territories, the defenders were unable to withstand sustained Japanese attacks. The Gin Drinkers Line, originally intended to delay an advance toward Kowloon, proved unable to hold for long. As the line collapsed, Allied forces were forced to withdraw toward Kowloon and eventually Hong Kong Island. The loss of the New Territories represented more than a territorial setback. It deprived the defenders of strategic depth and compressed the battlefield into an increasingly confined area centred on Kowloon and Hong Kong Island.',

        'wartime_timeline_1941_1213_title' => 'Kowloon Falls',
        'wartime_timeline_1941_1213_desc' => 'By approximately 13 December, most of Kowloon Peninsula had fallen into Japanese hands. The defenders withdrew across Victoria Harbour, leaving Hong Kong Island as the colony\'s final major defensive position. The harbour now served as the last natural barrier separating the opposing forces. For civilians, the situation grew increasingly desperate. Artillery bombardments, food shortages, and the prospect of displacement created mounting anxiety throughout the city. For the defenders, the campaign had evolved from a multi-front defence into a struggle to hold an isolated island fortress.',

        'wartime_timeline_1941_1218_title' => 'Japanese Forces Land on Hong Kong Island',
        'wartime_timeline_1941_1218_desc' => 'On the night of 18 December, Japanese troops crossed Victoria Harbour and landed on the northeastern shore of Hong Kong Island. The fighting entered its most intense phase as hillsides, roads, and urban districts became battlegrounds. Allied troops mounted determined resistance at locations including Wong Nai Chung Gap, Wan Chai Gap, and Stanley. As Japanese forces expanded their foothold, defensive positions became increasingly fragmented. Communications and supply lines deteriorated, while both soldiers and civilians faced mounting casualties and hardship.',

        'wartime_timeline_1941_1225_title' => 'Black Christmas: Hong Kong Surrenders',
        'wartime_timeline_1941_1225_desc' => 'On 25 December 1941, Governor Sir Mark Young formally surrendered Hong Kong to Japanese forces on behalf of the British colonial administration. The day would later become known as Black Christmas, marking both the end of the Battle of Hong Kong and the beginning of Japanese occupation. After eighteen days of fighting, Hong Kong had been transformed from a major international port into an occupied city. Curfews, food shortages, military currency, forced relocations, and strict controls over daily life soon became realities for the civilian population. The battle had ended, but a far longer period of hardship was just beginning.',

        'wartime_timeline_1942_title' => 'Resistance Continues Behind Enemy Lines',
        'wartime_timeline_1942_desc' => 'The fall of Hong Kong did not bring an end to resistance. Following the occupation, Communist-led anti-Japanese guerrilla forces operating in South China expanded their activities into Hong Kong, Kowloon, and the New Territories. They established bases, organised local support networks, gathered weapons, and gradually developed into the Hong Kong and Kowloon Brigade, one of the most significant resistance organisations active in occupied Hong Kong. The nature of the struggle changed from conventional warfare to resistance behind enemy lines. Guerrilla fighters conducted intelligence operations, rescue missions, raids, sabotage actions, and propaganda work, while also helping cultural figures, escaped prisoners of war, and Allied personnel evade capture. The Battle of Hong Kong was therefore more than an eighteen-day military campaign. It marked the beginning of Hong Kong\'s longer history of resistance during the years of occupation.',

        // Accordion
        'accordion_title' => 'Further Reading & Research Resources',
        'accordion_link_1' => 'Government Records Service, Hong Kong SAR Government',
        'accordion_link_2' => 'Hong Kong Museum of History',
        'accordion_link_3' => 'Hong Kong Museum of Coastal Defence',
        'accordion_link_4' => 'Leisure and Cultural Services Department (LCSD)',
        'accordion_link_5' => 'The University of Hong Kong Libraries',
        'accordion_link_6' => 'The Chinese University of Hong Kong Library',
        'accordion_link_7' => 'Hong Kong Public Libraries',
        'accordion_link_8' => 'Royal Asiatic Society Hong Kong Branch',
        'accordion_link_9' => 'Commonwealth War Graves Commission (CWGC)',
        'accordion_link_10' => 'Hong Kong Memory',
        'accordion_link_11' => 'Imperial War Museums (United Kingdom)',
        'accordion_link_12' => 'The National Archives (United Kingdom)',
        'accordion_link_13' => 'Library and Archives Canada',
        'accordion_link_14' => 'Dongjiang Column Historical Research Society',
        'accordion_link_15' => 'Chinese Culture Research Institute',
        'accordion_link_16' => 'Antiquities and Monuments Office (Hong Kong)',
        'accordion_link_17' => 'War of Resistance Against Japanese Aggression Memorial Network',
        'accordion_link_18' => 'Wikipedia – Battle of Hong Kong',
        


    ],

];  