<?php

return [

    'before_storm' => [

        'title' => 'Pre-war background',

        'subtitle' => 'Before the Storm',

        'intro' => 'Before the outbreak of war, Hong Kong was not only a commercial port in the Far East, but also an important port connecting South China, Southeast Asia, and world shipping routes. With the outbreak of China\'s full-scale War of Resistance against Japan, Hong Kong gradually became a place where supplies, news, refugees, and national salvation activities converged.',

        'battle_tab_1' => 'pre-war background',
        'battle_tab_2' => 'Battle process',
        'battle_tab_3' => 'black christmas', 
        'battle_tab_4' => 'Wartime Timeline',


        'section_1_title' => 'Hong Kong Before the Storm',
        'section_1_p1' => 'Even before the full-scale outbreak of World War II, Hong Kong was no longer a safe port untouched by the flames of war. Following the Mukden Incident of 1931, Japan gradually occupied Northeast China; after the Marco Polo Bridge Incident of 1937, China\'s full-scale War of Resistance against Japan broke out, and the flames of war spread from North and East China all the way to South China. In October 1938, Japanese troops landed at Daya Bay and subsequently occupied Guangzhou, causing the situation in South China to deteriorate rapidly. From then on, although Hong Kong remained under British rule, it was gradually surrounded by the war, becoming a key location where China\'s resistance against Japan, Britain\'s Far East defense, and Japan\'s southward expansion strategy converged.',
        'section_1_p2' => 'After the fall of Guangzhou, Hong Kong\'s status became even more unique. On the one hand, it remained an important port, financial and transshipment center in South China, handling a large flow of goods, people and intelligence; on the other hand, it also became a refuge for many mainland intellectuals, democrats, anti-Japanese activists, and refugees. Pre-war Hong Kong outwardly maintained the daily rhythm of a commercial metropolis, but tensions were already brewing beneath the surface: the supply of goods, border security, air defense preparations, military deployments, and even civilian relief activities were all changing under the shadow of war.',

        'section_2_title' => 'The situation in South China and the strategic location of Hong Kong',
        'section_2_p1' => 'Hong Kong is situated at the gateway to the South China Sea, backed by Guangdong and facing Southeast Asian shipping lanes. For Britain, it was part of the Far East colonial system and a crucial stronghold for access to South China and Southeast Asia; for Japan, Hong Kong was a strategic hub that had to be captured after the outbreak of the Pacific War. Historical materials from the Hong Kong and Kowloon Brigade also indicate that Hong Kong served as a transit hub and naval relay station for the Japanese army in the Pacific, and an important base for the Japanese army\'s northward invasion of mainland China and southward invasion of Southeast Asia.',
        'section_2_p2' => 'This geographical location placed Hong Kong under multiple pressures even before the war. It was adjacent to Japanese-controlled South China and served as a British outpost in East Asia. If Japan were to advance further south, Hong Kong\'s port, airport, warehouses, and communication facilities could all become resources exploited by the Japanese after an attack or occupation. Therefore, Hong Kong was not merely a local battlefield, but a node connecting the Chinese, Pacific, and Southeast Asian theaters of war. Consequently, the fall of Hong Kong later had far-reaching consequences, impacting not only the local area but also the military and transportation situation across the entire region.',

        'section_readmore' => 'Read more',

        'model_section_1_title' => 'A colony deemed "undefendable"',
        'model_section_1_p1' => 'Despite Hong Kong\'s strategic value, Britain\'s assessment of its defense was quite contradictory. Britain needed to maintain its prestige in the Far East and was unwilling to easily relinquish Hong Kong; however, with limited military resources, a precarious situation on the European front, and Singapore\'s defense considered a priority, Hong Kong was long considered undefendable for a sustained period. Data from the Canadian Veterans Affairs Department indicates that by the end of 1941, Britain had realized Hong Kong\'s vulnerability and therefore hoped to reinforce its troops there to deter Japan, or at least delay its advance.',
        'model_section_1_p2' => 'This predicament of "knowing it\'s difficult to defend, yet still having to defend" formed the basic backdrop of the Battle of Hong Kong. The Hong Kong defenders were not entirely unprepared, but their defense was constrained by manpower, equipment, terrain, and supplies. Once Hong Kong\'s sea and air transportation to the outside world was cut off, it was difficult to receive immediate reinforcements; moreover, the northern New Territories bordered Japanese-controlled areas, meaning the Japanese could quickly advance south by land. In other words, the defense of Hong Kong was not a battle of equal strength, but a struggle to delay, resist, and wear down the enemy in strategic isolation.',

        'model_section_2_title' => 'Drunken Bay Defense Line and New Territories Defense',
        'model_section_2_p1' => 'To prevent a Japanese invasion from the north, the British constructed a defensive line spanning the New Territories and the Kowloon Ridge before the war, known as the "Drunken Bay Line." This line consisted of numerous machine gun bunkers, trenches, observation points, and positions, built along the mountainside, originally intended to prevent enemy forces from advancing south from the New Territories into Kowloon. One of the core locations of the line was the Shing Mun Bastion near the Shing Mun Reservoir. Before the war, it was considered a crucial stronghold for Hong Kong\'s land defense.',
        'model_section_2_p2' => 'However, the Drunken Bay Line had inherent weaknesses. It was not a large, fortified European line, but rather a defensive system relying on mountains, roads, bunkers, and a small number of troops. Official war records show that by the morning of December 8, 1941, three infantry battalions from the Kowloon Peninsula had entered the defensive positions, including the Royal Scottish Regiment, the Punjab Regiment, and the Rajpu Regiment; but the pressure this line could withstand still depended on the number of defenders, night-fighting capabilities, communication, and the speed of reinforcements.',

        'model_section_3_title' => 'Composition and reinforcements of the defending forces',
        'model_section_3_p1' => 'The Hong Kong garrison was not from a single source, but rather composed of British troops, Indian troops, Canadian troops, local volunteer forces, and other auxiliary units. This diverse composition reflected Hong Kong\'s nature as a British colony and international port, as well as the patchwork nature of British Far East defense before the war. Different units came from different regions, with varying training backgrounds, combat experience, and familiarity with Hong Kong\'s terrain.',
        'model_section_3_p2' => 'In November 1941, Canada\'s "C Force" arrived in Hong Kong, comprising the Royal Canadian Rifle Regiment and the Winnipeg Grenadier Regiment. According to records from the Canadian Veterans Affairs Department, 1,975 Canadian soldiers departed Vancouver in late October 1941 and arrived in Hong Kong on November 16, joining the approximately 14,000-strong Hong Kong Defence Force. The Hong Kong Museum of Coastal Defence also points out that these Canadian soldiers arrived in Hong Kong only weeks before the outbreak of war; some were young and lacked combat experience, and were unfamiliar with Hong Kong\'s terrain.',

        'model_section_4_title' => 'Urban, village and civilian resistance base',
        'model_section_4_p1' => 'Before the war, Hong Kong was not only a military stronghold but also a densely populated city with a complex social network. Hong Kong Island and Kowloon were the political, commercial, and transportation centers; the New Territories, on the other hand, consisted of numerous villages, mountains, bays, and islands. This geographical and social structure profoundly influenced the form of resistance against Japan in Hong Kong. After the outbreak of formal warfare, although the Japanese army was able to quickly occupy major towns and transportation lines, the network of mountains, islands, fishing villages, and rural areas in the New Territories still provided space for underground transportation, intelligence transmission, rescue operations, and guerrilla warfare.',
        'model_section_4_p2' => 'Before the Japanese invasion, the Guangdong People\'s Anti-Japanese Guerrilla Force, led by the Communist Party of China, closely monitored the situation in Hong Kong and anticipated that if the Japanese attacked, they should enter Hong Kong to open up a rear-area battlefield. According to the "Chronicle of the Hong Kong and Kowloon Brigade," in the early stages of the Japanese invasion of Hong Kong, the Third and Fifth Battalions of the Guangdong People\'s Anti-Japanese Guerrilla Force successively dispatched eight armed work teams into the New Territories to eliminate bandits, collect weapons left behind by the British army, promote resistance against Japan, and call on villagers to defend their hometown. These preparations laid the early foundation for the later establishment of the Hong Kong and Kowloon Brigade and the sustained resistance during the Japanese occupation of Hong Kong.',

        'model_section_5_title' => 'War is approaching Hong Kong',
        'model_section_5_p1' => 'In the latter half of 1941, the situation in East Asia deteriorated rapidly. Diplomatic relations between Japan and Britain and the United States became increasingly tense, and the Pacific War was imminent. For the citizens of Hong Kong, war was no longer just international news in the newspapers, but a reality that was gradually approaching their lives: air defense drills, military mobilizations, price fluctuations, refugee flows, and border news all reminded people that Hong Kong might become the next battlefield.',
        'model_section_5_p2' => 'On December 8, 1941, the Japanese army attacked Hong Kong, officially igniting the war. According to the Hong Kong Museum of History, the Japanese army occupied Hong Kong after 18 days of fighting, from December 8 to 25, 1941. The Canadian Veterans Affairs Department also records that on that day, the Japanese army bombed Kai Tak Airport and advanced south across the New Territories from the Chinese border. From that moment on, Hong Kong transformed from a tense pre-war frontline city into a true battlefield; and its citizens, defenders, rural communities, and anti-Japanese forces were all drawn into a war that would change the fate of Hong Kong.',

        'model_section_6_title' => 'Summary: Understanding the Starting Point of the Defense War',
        'model_section_6_p1' => 'To understand the Battle of Hong Kong, one cannot begin with the gunfire of December 8, 1941. Its context was already embedded in the Japanese invasion of China, the fall of Guangzhou, the deteriorating situation in South China, Britain\'s predicament in the Far East, and Hong Kong\'s own geographical location. Hong Kong\'s becoming a battlefield was no accident; its port, waterways, borders, cities, and villages all made it a strategically vital location on the eve of the Pacific War.',
        'model_section_6_p2' => 'This pre-war background also helps us understand subsequent history: why the Hong Kong defenders fought in isolation, why the terrain of the New Territories and Kowloon was so important, and why sustained underground resistance and guerrilla activities continued even after the fall of Hong Kong. Before the war, Hong Kong was both a stronghold on the imperial defense line and a frontline in the overall Chinese War of Resistance. When war finally came, every road, every mountain, and every village in this city would be swept into the torrent of history.',

        'battle_process_title' => 'Battle process',
        'battle_process_subtitle' => 'Eighteen Days of Battle',
        'battle_process_intro' => 'In December 1941, the Japanese army launched an offensive against Hong Kong from the north, and the fighting advanced from the New Territories all the way to Kowloon and Hong Kong Island. In just eighteen days, the defending troops and civilians experienced the immense pressure of air raids, retreats, street fighting, and the defense of an isolated island.',

        'battle_process_section_1_title' => 'Battle Overview: The Eighteen Days from North to South',
        'battle_process_section_1_p1' => 'Even before the full-scale outbreak of World War II, Hong Kong was no longer a safe port untouched by the flames of war. Following the Mukden Incident of 1931, Japan gradually occupied Northeast China; after the Marco Polo Bridge Incident of 1937, China\'s full-scale War of Resistance against Japan broke out, and the flames of war spread from North and East China all the way to South China. In October 1938, Japanese troops landed at Daya Bay and subsequently occupied Guangzhou, causing the situation in South China to deteriorate rapidly. From then on, although Hong Kong remained under British rule, it was gradually surrounded by the war, becoming a key location where China\'s resistance against Japan, Britain\'s Far East defense, and Japan\'s southward expansion strategy converged.',
        'battle_process_section_1_p2' => 'After the fall of Guangzhou, Hong Kong\'s status became even more unique. On the one hand, it remained an important port, financial and transshipment center in South China, handling a large flow of goods, people and intelligence; on the other hand, it also became a refuge for many mainland intellectuals, democrats, anti-Japanese activists, and refugees. Pre-war Hong Kong outwardly maintained the daily rhythm of a commercial metropolis, but tensions were already brewing beneath the surface: the supply of goods, border security, air defense preparations, military deployments, and even civilian relief activities were all changing under the shadow of war.',

        'battle_process_section_2_title' => 'Crossing the Shenzhen River: The Flames of War Came from the North',
        'battle_process_section_2_p1' => 'The first step in the Japanese invasion of Hong Kong was to cross the border southward from north of the Shenzhen River. The northern New Territories were connected to Japanese-controlled southern China, quickly putting pressure on Hong Kong\'s land defenses. The Japanese advanced in multiple columns, pressing southward along Yuen Long, Sheung Shui, Fanling, Sha Tau Kok, and Tai Po, aiming to break through the New Territories and approach Kowloon. Simultaneously, Kai Tak Airport was bombed, weakening Hong Kong\'s air defenses almost immediately after the start of the war.',
        'battle_process_section_2_p2' => 'The primary mission of the defending forces in the northern New Territories was to slow the Japanese advance and buy time to retreat to the main defensive line. However, given the Japanese control of the offensive and their superior artillery and air support, the defenders found it difficult to hold out in the northern New Territories for long. After the fighting began, the Hong Kong defenders gradually retreated towards the "Drunken Bay Line." This line, originally considered a crucial barrier in northern Kowloon, quickly faced a severe test under the rapid Japanese advance.',

        'battle_process_model_section_1_title' => 'Drunken Bay Defense Line: The Fall of Kowloon\'s Gateway',
        'battle_process_model_section_1_p1' => 'The Drunken Bay defense line stretched across the mountain ridge north of Kowloon, relying on mountains, bunkers, trenches, and transportation lines to form a defensive system. Its strategic significance lay in preventing Japanese troops from entering Kowloon from the New Territories, thus buying time for the defense of Hong Kong Island. Among its key points, the Shing Mun Bastion was a crucial stronghold on the line and a key target for Japanese breakthroughs.',
        'battle_process_model_section_1_p2' => 'However, the battle unfolded faster than the defenders anticipated. From the night of December 9th to the early morning of December 10th, 1941, the Japanese launched a surprise attack on the city gate bastion. This night raid caused the rapid loss of the central stronghold of the Drunken Bay defense line, making the entire line untenable. Historical records from the Juno Beach Centre indicate that the Japanese attack on the Drunken Bay defense line on December 9th rendered the entire mainland defense line undefendable, forcing the defenders to abandon it.',
        'battle_process_model_section_1_p3' => 'The fall of the Drunken Bay defense line marked the first major turning point in the Battle of Hong Kong. The line, which had been intended to delay the Japanese advance for several days, was quickly breached. This forced the defenders to abandon their positions in northern Kowloon and begin a retreat and redeployment. From then on, the battle for Hong Kong was no longer about holding the New Territories, but about how to continue the resistance after the retreat from Kowloon, relying on Victoria Harbour and Hong Kong Island.',

        'battle_process_model_section_2_title' => 'Retreat from Kowloon: Shifting from Land Defense to Hong Kong Island',
        'battle_process_model_section_2_p1' => 'After the fall of the Drunken Bay defense line, the defenders began withdrawing from Kowloon to Hong Kong Island. Defensive space in Kowloon was limited, and remaining there risked trapping troops against the shoreline without a viable escape route. As a result, the military command decided to gradually abandon Kowloon and concentrate the defense on Hong Kong Island.',
        'battle_process_model_section_2_p2' => 'The withdrawal was a difficult operation. Under pressure from advancing Japanese forces, the defenders had to maintain order while transporting personnel, equipment, and supplies across Victoria Harbour. The loss of Kowloon also enabled Japanese forces to observe and bombard Hong Kong Island from the northern shore. For civilians, the war moved steadily closer—from the New Territories to Kowloon and then toward Hong Kong Island—spreading fear and confusion throughout the city.',
        'battle_process_model_section_2_p3' => 'By mid-December, Kowloon had fallen into Japanese hands, leaving Hong Kong Island as the defenders’ final major stronghold. Although Victoria Harbour initially provided a natural barrier, Japanese control of Kowloon significantly weakened this advantage. Japanese forces soon began preparations for an amphibious assault, marking the beginning of the second phase of the battle.',

        'battle_process_model_section_3_title' => 'Across Victoria Harbour: The Weakening of the Final Barrier',
        'battle_process_model_section_3_p1' => 'The defense of Hong Kong Island relied on a network of coastal artillery batteries, mountain positions, road checkpoints, and infantry defensive lines. The defenders hoped to use Victoria Harbour to prevent a Japanese crossing while taking advantage of the island’s rugged terrain to resist invasion.',
        'battle_process_model_section_3_p2' => 'After occupying Kowloon, however, Japanese forces gained the ability to observe and shell positions on Hong Kong Island from across the harbour. Before launching their crossing, they weakened the island’s defenses through artillery bombardment and air attacks.',
        'battle_process_model_section_3_p3' => 'At the same time, the defenders faced growing difficulties, including disrupted communications, strained medical services, supply shortages, and increasing civilian casualties. As water, food, and ammunition became scarce, both soldiers and civilians on Hong Kong Island were forced to endure mounting pressure. The battle was no longer simply a contest for military positions, but a struggle over how long the city could withstand siege conditions.',

        'battle_process_model_section_4_title' => 'Landing on Hong Kong Island: The Battle Enters Its Most Brutal Stage',
        'battle_process_model_section_4_p1' => 'On the night of December 18th, 1941, Japanese forces began landing along the northern shore of Hong Kong Island. After coming ashore, they engaged defenders in fierce fighting at North Point, Quarry Bay, Taikoo, Wong Nai Chung Gap, Repulse Bay, Stanley, and other locations.',
        'battle_process_model_section_4_p2' => 'The island’s complex terrain of roads, ridges, valleys, and coastlines created a fragmented and intense battlefield. Communication between units was frequently disrupted, and individual defensive sectors often found themselves fighting in isolation.',
        'battle_process_model_section_4_p3' => 'Wong Nai Chung Gap became one of the fiercest battlegrounds of the campaign. As a key route connecting the northern and southern parts of the island, it was a critical objective for Japanese forces seeking to divide the defenders. British, Canadian, Indian, Hong Kong Volunteer Defence Corps, and other defending units fought stubbornly across the island, suffering heavy casualties. Records from the Commonwealth War Graves Commission note that many Commonwealth servicemen who died during the Battle of Hong Kong and subsequent imprisonment are commemorated at Sai Wan War Cemetery, reflecting the heavy cost of the fighting.',

        'battle_process_model_section_5_title' => 'Isolation and Fragmentation: The Collapse of the Island Defenses',
        'battle_process_model_section_5_p1' => 'Following the Japanese landings, the defensive positions on Hong Kong Island were gradually divided and isolated. Although resistance continued in many areas, coordination, communication, and reinforcement became increasingly difficult.',
        'battle_process_model_section_5_p2' => 'By capturing key high ground and transportation routes, Japanese forces were able to sever links between defensive sectors. Hospitals, emergency aid stations, and residential areas were also affected by the fighting, causing severe hardship for civilians.',
        'battle_process_model_section_5_p3' => 'As the battle entered its final stages, the defenders faced mounting challenges, including lost positions, shortages of ammunition, food, and water, large numbers of wounded personnel, and the absence of outside reinforcement. Despite these conditions, resistance continued across the island. Defenders in the Stanley area, in particular, held out until shortly before the surrender, demonstrating that Hong Kong’s defense did not collapse immediately but continued under extremely difficult circumstances.',

        'battle_process_model_section_6_title' => 'Christmas Day Surrender: The Beginning of the Black Christmas',
        'battle_process_model_section_6_p1' => 'By December 25th, 1941, the military situation in Hong Kong had become hopeless. That afternoon, Governor Sir Mark Young and Major General Christopher Maltby formally surrendered to the Japanese forces. The day later became known as the “Black Christmas.”',
        'battle_process_model_section_6_p2' => 'For Hong Kong, the surrender represented more than a military defeat. It marked the end of British colonial administration and the beginning of Japanese occupation, ushering in three years and eight months of hardship for the city and its residents.',
        'battle_process_model_section_6_p3' => 'The end of the Battle of Hong Kong did not mean the end of resistance. Following the surrender of the British forces, the responsibility for resisting Japanese occupation increasingly fell to Communist-led guerrilla forces and local resistance groups. Historical records of the East River Column’s Hong Kong and Kowloon Independent Brigade indicate that it was the only organized armed force that maintained continuous resistance throughout the occupation, laying the foundation for later stories of rescue operations, guerrilla warfare, intelligence cooperation, maritime actions, and civilian support.',

        'battle_process_model_section_7_title' => 'Summary: A Defeat That Marked the Beginning of Resistance',
        'battle_process_model_section_7_p1' => 'The Battle of Hong Kong ended in military defeat, but it also marked the beginning of a new phase of resistance. The collapse of the defensive lines, the retreat from Kowloon, and the fall of Hong Kong Island transformed the conflict from a conventional military campaign into a prolonged struggle against occupation.',
        'battle_process_model_section_7_p2' => 'The experiences of soldiers, civilians, resistance fighters, and refugees during and after the battle became an important part of Hong Kong’s wartime history. Their stories reveal not only the tragedy of defeat, but also the determination to resist under some of the most difficult circumstances the city had ever faced.',

        //tab 3
        'black_christmas_title' => 'Black Christmas',
        'black_christmas_subtitle' => 'Black Christmas',
        'black_christmas_intro' => 'On December 25, 1941, Hong Kong surrendered, a day later known as "Black Christmas." It marked the end of the Battle of Hong Kong and the beginning of three years and eight months of Japanese occupation.',

        'black_christmas_section_1_title' => 'The moment a city fell',
        'black_christmas_section_1_p1' => 'December 25, 1941, was Christmas Day, and also a somber day in Hong Kong\'s history. After eighteen days of fierce fighting, the Hong Kong defenders put up a desperate resistance in multiple battlefields across the New Territories, Kowloon, and Hong Kong Island. However, being outnumbered in terms of manpower, firepower, air superiority, supplies, and foreign aid, the tide of the war was irreversible. On this day, Hong Kong Governor Sir Mark Young and Commander-in-Chief of the British forces in Hong Kong, General Mordred, surrendered to the Japanese, and Hong Kong officially fell to the Japanese. Hong Kong people later called this day "Black Christmas" because it marked the end of the fighting and the beginning of three years and eight months of Japanese occupation. According to the Hong Kong Memory Archive, the Japanese attacked Hong Kong on December 8, 1941, and the defenders surrendered on Christmas Day after eighteen days of fierce fighting, thus beginning the Japanese occupation.',
        'black_christmas_section_1_p2' => 'The "Black Christmas" was so somber not only because Hong Kong had lost military control. For the citizens, this day represented the sudden collapse of the existing order: government power was interrupted, military occupation began, and transportation, food, security, and daily life were forced into an unknown state. Although the fighting gradually subsided, a longer and darker period had just begun.',

        'black_christmas_section_2_title' => 'Christmas Day Surrender',
        'black_christmas_section_2_p1' => 'Around December 25th, the fighting on Hong Kong Island entered its final stage. After landing, the Japanese gradually cut off the defenders\' lines of defense, controlling key transportation routes and high ground. The defending forces were divided, many positions were isolated and without support, and ammunition, water, and medical resources were increasingly scarce. The Canadian Department of Veterans Affairs stated that by Christmas Day, after more than seventeen days of fierce fighting, the Allied forces had suffered heavy casualties and ultimately had no choice but to lay down their arms and surrender; Canadian soldiers subsequently became prisoners of war, many spending more than three years in POW camps in Hong Kong and Japan.',
        'black_christmas_section_2_p2' => 'The surrender ceremony took place at the Peninsula Hotel. This hotel, originally a symbol of Hong Kong\'s prosperity and prestige as an international city, became the site of the transfer of sovereignty and military control of Hong Kong on Christmas Day, 1941. The 80th anniversary commemorative publication of the Hong Kong and Kowloon Brigade also includes related photos and captions, documenting the British surrender announcement on December 25, 1941, and identifying the photo as showing the surrender ceremony inside the Peninsula Hotel.',

        'black_christmas_model_section_1_title' => 'From War to Occupation',
        'black_christmas_model_section_1_p1' => 'The end of the fighting did not mean the end of suffering. For many soldiers, surrender meant years of imprisonment as prisoners of war. For civilians, the arrival of Japanese forces brought searches, restrictions, looting, and severe food shortages that gradually transformed every aspect of daily life. Once an international trading port, Hong Kong was absorbed into Japan\'s military occupation system, and its ports, warehouses, roads, vessels, factories, and supplies could all be requisitioned or controlled by the occupying authorities.',
        'black_christmas_model_section_1_p2' => 'The Japanese occupation government quickly established a system of military rule. Movement was restricted, while news, speech, public gatherings, transport, and food supply were placed under strict control. Many people were forced to leave urban areas and return to mainland China or rural villages, while others lost family members due to war, famine, disease, or violence. According to the Hong Kong Museum of History, the eighteen-day campaign from December 8 to 25, 1941, marked the process of Hong Kong\'s occupation and later became one of the most significant wartime traumas in the city\'s collective memory.',

        'black_christmas_model_section_2_title' => 'The Heavy Cost for Soldiers and Civilians',
        'black_christmas_model_section_2_p1' => 'The Battle of Hong Kong resulted in heavy military and civilian casualties. The defenders included British, Canadian, Indian troops, the Hong Kong Volunteer Defence Corps, and other auxiliary forces. Many were killed, wounded, or taken prisoner. After the war, large numbers of Commonwealth servicemen were buried or commemorated in military cemeteries across Hong Kong, including Sai Wan War Cemetery. These graves and memorials continue to remind us that the Battle of Hong Kong was not an abstract military event, but a historical tragedy borne by individual lives.',
        'black_christmas_model_section_2_p2' => 'Civilians also suffered greatly. Shelling, air raids, street fighting, and military occupation caused widespread fear and instability. Many families were displaced, while others suffered from starvation, lack of medical care, or abuse by occupying forces. For ordinary citizens, “Black Christmas” was not simply a date in military history, but the beginning of life being torn apart by war.',

        'black_christmas_model_section_3_title' => 'Collapse of Urban Order',
        'black_christmas_model_section_3_p1' => 'After the fall of Hong Kong, the colonial administrative system was suspended and replaced by Japanese military administration. Banks, schools, newspapers, shops, hospitals, and public institutions were severely disrupted. Basic necessities such as currency, food, employment, healthcare, and transport became increasingly unstable, forcing civilians to face not only military control but also survival pressure caused by shortages.',
        'black_christmas_model_section_3_p2' => 'Hong Kong under Japanese occupation was no longer the vibrant free port it had been before the war. While the port remained important, its function shifted to military and occupation needs. The city continued to operate, but under a logic defined by military control rather than colonial administration. Streets, docks, warehouses, and schools were repurposed for occupation purposes, and daily life was increasingly subordinated to the machinery of war.',

        'black_christmas_model_section_4_title' => 'The Contrast of Christmas',
        'black_christmas_model_section_4_p1' => 'The term “Black Christmas” is memorable because of its stark contrast. Christmas is normally associated with peace, reunion, and hope, but in Hong Kong in 1941 it brought surrender, disorder, and occupation instead. The sounds of war replaced the peace of the holiday season. For many families, that day marked not celebration, but the beginning of fear and uncertainty.',
        'black_christmas_model_section_4_p2' => 'This contrast made “Black Christmas” an important symbol in Hong Kong’s collective memory. It represents not only military defeat but also the forced transformation of a city’s fate under war. From that day onward, survival required enduring occupation, hunger, fear, and oppression, while also preserving the possibility of resistance in the darkness.',

        'black_christmas_model_section_5_title' => 'Resistance Did Not End',
        'black_christmas_model_section_5_p1' => 'After the surrender of Hong Kong, although the formal defensive lines collapsed, resistance did not stop. Instead, the nature of warfare shifted from conventional defense to guerrilla and underground resistance. Historical records of the Hong Kong and Kowloon Independent Brigade indicate that after the British surrender, the responsibility for resisting Japanese occupation fell largely to Communist-led guerrilla forces. On 3 February 1942, the Hong Kong and Kowloon Independent Brigade was established in Wong Mo Ying Village in Sai Kung, becoming the only organized armed force that maintained continuous resistance throughout the occupation.',
        'black_christmas_model_section_5_p2' => 'Thus, “Black Christmas” marked not only the fall of Hong Kong, but also the beginning of a new phase of resistance history. From urban battlefields to rural villages, from Kowloon and Hong Kong Island to the New Territories, and from land routes to maritime channels, resistance continued in new forms. Later operations such as secret rescue missions, intelligence cooperation, guerrilla warfare, anti-collaboration actions, and civilian support networks all emerged from this turning point.',

        'black_christmas_model_section_6_title' => 'Conclusion: A Turning Point in the Dark',
        'black_christmas_model_section_6_p1' => 'On 25 December 1941, Hong Kong was plunged into darkness. The eighteen-day Battle of Hong Kong ended, and a long period of Japanese occupation began. For the first time, Hong Kong civilians directly experienced the full brutality of a global war, facing occupation, disorder, and survival crises.',
        'black_christmas_model_section_6_p2' => 'However, Black Christmas was not only a symbol of defeat and suffering. It also reminds us that Hong Kong’s wartime story did not end with surrender. When formal military defenses collapsed, underground networks, rural support systems, maritime routes, and civilian assistance became essential to sustaining resistance. In the aftermath of Black Christmas, Hong Kong’s resistance entered a more hidden, more difficult, but also more resilient phase.',

        //tab 4
        'wartime_timeline_title' => 'Wartime Timeline',
        'wartime_timeline_subtitle' => 'Wartime Timeline',
        'wartime_timeline_intro' => 'From the Marco Polo Bridge Incident to the fall of Hong Kong, and then to the unfolding of the resistance war behind enemy lines, this timeline connects how Hong Kong was gradually drawn into the storm of World War II. It reminds us that the Battle of Hong Kong was not just a battle that lasted eighteen days, but also the starting point of Hong Kong\'s memory of the War of Resistance.',

        'wartime_timeline_1937_title' => 'The outbreak of the full-scale War of Resistance against Japan',
        'wartime_timeline_1937_desc' => 'Following the Marco Polo Bridge Incident in 1937, China entered full-scale resistance against Japan. Although Hong Kong remained a British colony and was not immediately a battlefield, it became closely linked to the mainland war situation. A large number of refugees, intellectuals, journalists, and political figures moved south to Hong Kong, turning the city into an important hub for war reporting, relief activities, supply transport, and ideological exchange.',

        'wartime_timeline_1938_title' => 'Fall of Guangzhou, War Approaches Hong Kong',
        'wartime_timeline_1938_desc' => 'In October 1938, Japanese forces landed in southern China and occupied Guangzhou, sharply increasing strategic pressure on Hong Kong. After the fall of Guangzhou, major transport routes in southern China came under Japanese control, weakening supply lines that previously passed through Hong Kong. The city shifted from a distant commercial port to a frontline border city under direct military threat.',

        'wartime_timeline_1941_1208_title' => 'Japanese Invasion of Hong Kong Begins',
        'wartime_timeline_1941_1208_desc' => 'On 8 December 1941, Japanese forces crossed the Shenzhen River and attacked Hong Kong from the north, marking the official beginning of the Battle of Hong Kong. On the same day, Kai Tak Airport was bombed, quickly weakening Allied air capabilities. Despite being outmatched in manpower, firepower, and air superiority, the defenders attempted to delay the Japanese advance along the northern New Territories.',

        'wartime_timeline_1941_1210_title' => 'New Territories Defense Line Collapses',
        'wartime_timeline_1941_1210_desc' => 'Japanese forces advanced rapidly after the outbreak of fighting. Although defensive positions had been prepared in the New Territories, they were quickly overwhelmed. The Gin Drinkers Line, originally intended to delay the Japanese advance, failed to hold, forcing a retreat toward Kowloon and Hong Kong Island and causing Hong Kong’s defensive depth to collapse.',

        'wartime_timeline_1941_1213_title' => 'Kowloon Peninsula Effectively Lost',
        'wartime_timeline_1941_1213_desc' => 'By around 13 December 1941, Kowloon had largely fallen under Japanese control. Allied forces withdrew to Hong Kong Island, with Victoria Harbour becoming the final natural barrier. The loss of Kowloon intensified civilian panic, food shortages, and evacuation pressure, while the battle shifted into an island defense scenario.',

        'wartime_timeline_1941_1218_title' => 'Japanese Land on Hong Kong Island',
        'wartime_timeline_1941_1218_desc' => 'On the night of 18 December 1941, Japanese forces landed on the northeastern coast of Hong Kong Island, marking the most intense phase of the battle. Fighting spread rapidly across mountainous terrain and urban areas. Defensive positions were cut off one by one, and supply and communication lines collapsed under sustained assault.',

        'wartime_timeline_1941_1225_title' => 'Black Christmas: Hong Kong Surrenders',
        'wartime_timeline_1941_1225_desc' => 'On 25 December 1941, Governor Sir Mark Young surrendered to Japanese forces on behalf of the British colonial government. This day became known as “Black Christmas,” marking the end of the Battle of Hong Kong and the beginning of Japanese occupation. The city transitioned overnight from a major port to an occupied territory under strict military control.',

        'wartime_timeline_1942_title' => 'Resistance Behind Enemy Lines Begins',
        'wartime_timeline_1942_desc' => 'After the fall of Hong Kong, resistance did not cease. Guerrilla forces operating in South China entered Hong Kong and the New Territories, establishing networks, gathering intelligence, and forming what later became the Hong Kong and Kowloon Independent Brigade. Resistance operations expanded to include rescue missions, sabotage, intelligence work, and civilian support networks.',

        // Accordion
        'accordion_title' => 'Expand reference materials',
        'accordion_link_1' => 'Hong Kong Public Records Office',
        'accordion_link_2' => 'Hong Kong Museum of History',
        'accordion_link_3' => 'Leisure and Cultural Services Department',
        'accordion_link_4' => 'The University of Hong Kong Libraries',
        'accordion_link_5' => 'The Chinese University of Hong Kong Library',
        'accordion_link_6' => 'Hong Kong Public Libraries',
        'accordion_link_7' => 'Royal Asiatic Society Hong Kong Branch',
        'accordion_link_8' => 'Commonwealth War Graves Commission',
        'accordion_link_9' => 'Hong Kong Memory',
        'accordion_link_10' => 'Imperial War Museums',
        'accordion_link_11' => 'The National Archives (UK)',
        'accordion_link_12' => 'Library and Archives Canada',
        'accordion_link_13' => 'Dongjiang Column Historical Research Association',
        'accordion_link_14' => 'Chinese Culture Research Institute',
        'accordion_link_15' => 'Antiquities and Monuments Office',
        'accordion_link_16' => 'Memorial Network of the War of Resistance Against Japanese Aggression',
        'accordion_link_17' => 'Wikipedia (Battle of Hong Kong)',
        


    ],

];  