<?php

return [
     'guerrilla_warfare' => [

        'title' => 'Guerrilla warfare',
        'subtitle' => 'Guerrilla Warfare',
        'intro' => 'Facing a Japanese army that had superior numbers and weaponry, the guerrillas used mountains, villages, bays, and streets as their battlefields. They attacked the enemy and boosted morale through raids, bombings, ambushes, and propaganda.',

        'guerrilla_tab_1' => 'Hong Kong and Kowloon Brigade',
        'guerrilla_tab_2' => 'guerrilla warfare',
        'guerrilla_tab_3' => 'Intelligence and Rescue',
        'guerrilla_tab_4' => 'Anti-Japanese resistance network',

        // tab 1
        'guerrilla_section_1_title' => 'Sustaining Resistance Across Mountains and Seas',
        'guerrilla_section_1_p1' => 'After the fall of Hong Kong, the Japanese occupied the main urban districts, transportation routes, ports, and military facilities. However, this did not mean that all opportunities for resistance had disappeared. The mountains, villages, bays, and islands of the New Territories continued to provide favorable conditions for anti-Japanese activities. It was in this environment that the Hong Kong–Kowloon Brigade launched guerrilla operations, using its knowledge of local terrain, support from civilians, and mobile tactics to resist Japanese occupation.',
        'guerrilla_section_1_p2' => 'The Hong Kong–Kowloon Brigade’s guerrilla warfare was not characterized by large-scale conventional battles. Instead, it consisted of dispersed, flexible, covert, and sustained operations behind enemy lines. These actions included ambushing patrols along mountain paths, launching night raids on Japanese positions, sabotaging transportation facilities in urban areas, and using small boats to challenge enemy vessels at sea. Commemorative publications describe how the brigade conducted rural, island, maritime, and urban guerrilla warfare in Hong Kong, a strategically important location. These operations effectively disrupted Japanese deployments and kept occupying forces and their collaborators under constant pressure and uncertainty.',

        'guerrilla_section_2_title' => 'Hong Kong’s Terrain and the Conditions for Guerrilla Warfare',
        'guerrilla_section_2_p1' => 'Hong Kong’s limited geographical size and the heavy presence of Japanese troops made it difficult for the Hong Kong–Kowloon Brigade to establish large and stable base areas. As a result, guerrilla warfare in Hong Kong could not simply follow the model used in the vast rural regions of mainland China. Instead, tactics had to be adapted to local conditions. Mountain ridges, villages, bays, islands, urban streets, and border routes all became important foundations for different forms of resistance. According to the Antiquities and Monuments Office’s article on the East River Column Heritage Trail, the Hong Kong–Kowloon Brigade relied on intelligence gathering, communications, supply transport, and rescue operations to strike at Japanese forces, becoming a central force in Hong Kong’s wartime resistance.',
        'guerrilla_section_2_p2' => 'This operating environment required units to remain small, mobile, and highly dependent on local communities. The brigade could not hold a fixed position for long periods, nor could it engage large Japanese formations in direct confrontation. Instead, it often operated in pistol squads, small teams, or company-sized units that could respond quickly to changing conditions, complete missions, and withdraw before the enemy could react. Its strength lay not in numbers, but in its familiarity with the terrain, close connections with local residents, ability to remain concealed, and capacity to strike where the enemy least expected.',
       
        'guerrilla_model_section_1_title' => 'Strike the Strong with the Weak: Mobile and Flexible Tactics',
        'guerrilla_model_section_1_p1' => 'The core of guerrilla warfare is to use the weak against the strong and strike the enemy where they are least prepared. Facing a Japanese army with superior firepower, manpower, and transportation control, the Hong Kong-Kowloon Independent Brigade avoided direct conventional battles that would have resulted in heavy losses. Instead, they relied on ambushes, surprise attacks, demolitions, sabotage, anti-collaboration operations, interceptions, and night raids to target enemy weak points. These targets included small outposts, patrol units, transport routes, puppet police stations, supply vessels, and temporary Japanese bases.',
        'guerrilla_model_section_1_p2' => 'The purpose of these tactics was not territorial occupation, but disruption of enemy operations, weakening morale, capturing supplies, destroying transport networks, protecting civilians, and demonstrating that resistance still existed. Although most operations were small in scale, their impact was significant. A single successful ambush could force Japanese troops to adjust their deployment; a demolition could disrupt transport and military logistics; and a night raid could weaken puppet police control over rural areas.',

        'guerrilla_model_section_2_title' => 'Land Guerrilla Warfare: Battles Between Villages and Strongholds',
        'guerrilla_model_section_2_p1' => 'Land-based guerrilla operations were mainly active in Sai Kung, Sha Tau Kok, Sha Tin, Tai Po, Yuen Long, and Lantau Island. These regions contained mountains, villages, coastlines, and farmland, allowing guerrillas to move covertly while receiving supplies, intelligence, and guidance from villagers. Sai Kung and Sha Tau Kok were especially important as they connected maritime routes and the Dongjiang guerrilla base area, making them key operational zones.',
        'guerrilla_model_section_2_p2' => 'The enemies faced by guerrillas were not only Japanese forces but also puppet police, spies, collaborators, bandits, and local criminal groups. Since Japan could not fully control every village and mountain path, it relied heavily on puppet organizations and informants to suppress resistance. The Hong Kong-Kowloon Independent Brigade targeted these forces both as military operations and as a means of protecting villagers and maintaining resistance zones.',


        'guerrilla_model_section_3_title' => 'Short Gun Squads and Close-Range Raids',
        'guerrilla_model_section_3_p1' => 'Short gun squads were a distinctive force within Hong Kong guerrilla warfare. These units were small, lightly equipped, and highly mobile, operating in mountainous terrain, villages, and urban outskirts. They could disguise themselves, infiltrate enemy positions, and launch sudden attacks before quickly withdrawing. This made them particularly effective in Hong Kong’s dense and complex geography.',
        'guerrilla_model_section_3_p2' => 'For example, the Sha Tin short gun squad operated in areas such as Lion Rock, Chuk Yuen, Ngau Chi Wan, and Wo Tong. Records show that in July–August 1942, they attempted to raid Japanese forces at Shing Mun Reservoir via an aqueduct route. Encountering enemy troops, they used the aqueduct for cover, waited for the enemy to approach, and opened fire, killing Japanese officers and soldiers and capturing weapons.',


        'guerrilla_model_section_4_title' => 'Raid on Kai Tak Airport: Striking the Enemy’s Core',
        'guerrilla_model_section_4_p1' => 'In February 1944, the Hong Kong-Kowloon Independent Brigade planned a raid on Kai Tak Airport, a major Japanese military facility critical to air transport, logistics, and operations. At the time, Japanese forces were intensively searching for an American pilot who had parachuted into the region, while conducting large-scale sweeps in Sai Kung and Sha Tin. The guerrillas launched an external operation to distract and disrupt enemy forces.',
        'guerrilla_model_section_4_p2' => 'According to records, Liu Heizi and others infiltrated the airport, killed a guard, and used timed explosives to destroy an aircraft and a fuel depot. This operation demonstrated that guerrilla forces could penetrate heavily guarded military installations and operate deep within enemy-controlled zones.',


        'guerrilla_model_section_5_title' => 'Blowing Up Waterloo Road Railway Bridge: Disrupting Transport Networks',
        'guerrilla_model_section_5_p1' => 'Guerrilla warfare also targeted transportation infrastructure. In April 1944, the urban unit of the Hong Kong-Kowloon Independent Brigade demolished the No. 4 railway bridge on Waterloo Road in Kowloon. This railway line was vital for Japanese troop movements and military operations.',
        'guerrilla_model_section_5_p2' => 'The explosion forced Japanese forces preparing operations in the New Territories and Bao’an to withdraw back to the city. This demonstrated how small, precise attacks on key infrastructure could significantly disrupt enemy strategic planning and force large-scale redeployments.',


        'guerrilla_model_section_6_title' => 'Night Raids on Strongholds: Striking Puppet Police and Enemy Bases',
        'guerrilla_model_section_6_p1' => 'The Hong Kong guerrillas frequently conducted night raids on Japanese and puppet police bases. Night operations allowed them to approach targets covertly and reduce the enemy’s firepower advantage. These missions required careful reconnaissance, internal coordination, terrain familiarity, and planned escape routes.',
        'guerrilla_model_section_6_p2' => 'In October 1944, the Lantau Island unit attacked the Tai O puppet police station, capturing over thirty police officers and seizing thirty-nine firearms. The operation weakened puppet authority and demonstrated continued resistance under occupation.',


        'guerrilla_model_section_7_title' => 'Guan Hang Seven Saints Temple: Destroying Japanese Fortification Plans',
        'guerrilla_model_section_7_p1' => 'In winter 1944, the Sai Kung unit launched an attack on a Japanese position at Guan Hang Seven Saints Temple. After careful reconnaissance, the unit completely destroyed the garrison and seized weapons and ammunition, preventing the construction of Japanese fortifications in the area.',
        'guerrilla_model_section_7_p2' => 'This operation showed that guerrilla forces actively prevented enemy consolidation rather than merely avoiding confrontation. By striking before fortifications were completed, they preserved operational freedom in the Sai Kung region.',


        'guerrilla_model_section_8_title' => 'Sea Guerrilla Warfare: Small Boats Against Warships',
        'guerrilla_model_section_8_p1' => 'Hong Kong’s geography made maritime guerrilla warfare essential. Using fishing boats, islands, and local maritime knowledge, the Hong Kong-Kowloon Independent Brigade developed naval guerrilla tactics. According to Chan Sheng’s memoirs, the guerrillas used small boats to attack larger enemy vessels, sinking or capturing multiple ships.',
        'guerrilla_model_section_8_p2' => 'Although small boats were vulnerable to enemy gunboats, they had advantages in mobility, concealment, and night operations. This allowed guerrillas to operate across waters including Tolo Harbour, Lantau Island, Lung Kwu Chau, and Sha Chau.',


        'guerrilla_model_section_9_title' => 'Lung Kwu Chau and Sha Chau: The Cost of Maritime Warfare',
        'guerrilla_model_section_9_p1' => 'Sea guerrilla warfare also involved heavy losses. In May 1943, a Lantau unit was ambushed by Japanese gunboats near Lung Kwu Chau and Sha Chau. The wooden sailing vessel was outgunned and sunk, resulting in the deaths of all fighters and civilians aboard.',
        'guerrilla_model_section_9_p2' => 'This event highlights the extreme risks of maritime operations. Despite their strategic importance, guerrilla boats were highly vulnerable when exposed to enemy naval firepower.',


        'guerrilla_model_section_10_title' => 'Battle of Lang Kok: Late-War Naval Success',
        'guerrilla_model_section_10_p1' => 'In August 1945, the sea unit attacked a Japanese transport vessel at Lang Kok, killing over forty enemy soldiers and capturing large quantities of weapons and supplies.',
        'guerrilla_model_section_10_p2' => 'This operation demonstrated that guerrilla forces remained active and effective even in the final phase of the war, while also securing critical supplies for continued resistance.',


        'guerrilla_model_section_11_title' => 'Urban Guerrilla Warfare: Operating in the Enemy’s Core',
        'guerrilla_model_section_11_p1' => 'Urban guerrilla units operated in heavily controlled Japanese occupation zones in Hong Kong and Kowloon. Known as the “unarmed guerrillas,” they focused on intelligence gathering, propaganda, communication, and sabotage rather than open combat.',
        'guerrilla_model_section_11_p2' => 'Their actions included distributing leaflets, relaying intelligence, and conducting targeted disruptions. These covert operations undermined Japanese control and demonstrated that occupation centers were not fully secure.',


        'guerrilla_model_section_12_title' => 'Combat Achievements and Historical Evaluation',
        'guerrilla_model_section_12_p1' => 'According to incomplete statistics, the Hong Kong-Kowloon Independent Brigade killed or wounded over one hundred Japanese soldiers, seventy collaborators and spies, and captured more than six hundred enemy personnel. They destroyed aircraft, seized hundreds of weapons, and sank or captured multiple vessels.',
        'guerrilla_model_section_12_p2' => 'Beyond numbers, their significance lies in disrupting Japanese control, protecting civilians, sustaining morale, and maintaining links between Hong Kong and broader Chinese resistance movements.',


        'guerrilla_model_section_13_title' => 'Conclusion: An Unyielding Battlefield',
        'guerrilla_model_section_13_p1' => 'Guerrilla warfare ensured that occupied Hong Kong was never fully subdued. Resistance continued across mountains, villages, islands, and city streets using limited resources and local support.',
        'guerrilla_model_section_13_p2' => 'These actions created cracks within the occupation system, proving that Hong Kong during the war was not only a place of suffering but also a place of persistent resistance and enduring hope.',

        // tab 2
        'hk_brigade_title' => 'Hong Kong and Kowloon Brigade',
        'hk_brigade_subtitle' => 'The Hong Kong–Kowloon Brigade',
        'hk_brigade_intro' => 'After the fall of Hong Kong, the resistance did not cease. The Hong Kong and Kowloon Brigade established strongholds in the New Territories, Sai Kung, Sha Tau Kok, Lantau Island, and urban areas, becoming the most important anti-Japanese force behind enemy lines in Hong Kong during the Japanese occupation.',

        'hk_brigade_section_1_title' => 'The Anti-Japanese Armed Force in the Years of Occupation',
        'hk_brigade_section_1_p1' => 'On December 25, 1941, Hong Kong fell during the “Black Christmas.” After the collapse of the regular defensive lines, the city did not fall completely silent. Under Japanese occupation, an anti-Japanese armed force led by the Communist Party of China gradually took on the responsibility of resistance in the enemy rear across Hong Kong, Kowloon, the New Territories, and surrounding waters. This force later became widely known as the Hong Kong-Kowloon Independent Brigade of the East River Column.',
        'hk_brigade_section_1_p2' => 'The Hong Kong-Kowloon Independent Brigade held a unique historical position. It was not a conventional unit from an external battlefield, but a local anti-Japanese force established, developed, and sustained under the special conditions of occupied Hong Kong. According to memorial publications, after the British surrender, multiple guerrilla units entering the New Territories were reorganized under the Guangdong People’s Anti-Japanese Guerrilla Command into the “Hong Kong-Kowloon Independent Brigade.” The brigade was officially established on February 3, 1942, in Wong Mo Ying Village, Sai Kung.',
        
        'hk_brigade_section_2_title' => 'From Guerrilla Units to the Hong Kong-Kowloon Independent Brigade',
        'hk_brigade_section_2_p1' => 'The formation of the brigade did not start from scratch. As early as the Japanese invasion of Hong Kong, multiple work teams from the 3rd and 5th detachments of the Guangdong People’s Anti-Japanese Guerrilla Force had already entered the New Territories. Their missions included mobilizing local communities, establishing resistance bases, eliminating bandits and collaborators, collecting weapons, and assisting in the rescue of intellectuals and democratic figures trapped in Hong Kong.',
        'hk_brigade_section_2_p2' => 'These early guerrilla units were familiar with rural terrain and relied heavily on local villagers, fishermen, youth, and underground transport networks. They operated in Sai Kung, Sha Tau Kok, Yuen Long, and Lantau Island, facing not only Japanese forces but also bandits, puppet police, spies, and supply shortages.',
        'hk_brigade_section_2_p3' => 'The establishment of the Hong Kong-Kowloon Independent Brigade marked a major turning point in the organization of resistance. It unified scattered armed groups into a structured force with headquarters, detachments, short-gun squads, maritime units, urban units, and intelligence systems, enabling sustained resistance under occupation.',
       
        //model
        'hk_brigade_model_section_1_title' => 'Wong Mo Ying Village and the Sai Kung Base Area',
        'hk_brigade_model_section_1_p1' => 'The founding location of the Hong Kong Brigade is closely tied to Sai Kung. On February 3, 1942, the Hong Kong Brigade was officially established in Wong Mo Ying Village, Sai Kung. Today, the Rose Chapel in Wong Mo Ying Village is regarded as an important historical site connected to the early activities of the brigade. According to the Antiquities and Monuments Office’s Dongjiang Column Heritage Trail materials, due to its strategic location, the Rose Chapel served as one of the headquarters and command posts of the guerrilla force. Local youth actively participated in the resistance, with village militia, youth associations, and women’s groups supporting guerrilla operations.',
        'hk_brigade_model_section_1_p2' => 'Sai Kung’s importance came from its geography. With mountains, villages, bays, and coastal waters, it linked Kowloon, the New Territories, northeastern Guangdong, and inland guerrilla zones. For Japanese forces, this rugged terrain was difficult to fully control. For the Hong Kong Brigade, it provided concealment, mobility, supply routes, and maritime access. As a result, Sai Kung became one of the most important early bases of the Hong Kong resistance and remains one of the most symbolic areas in Hong Kong’s wartime memory.',
        'hk_brigade_model_section_1_p3' => 'Wong Mo Ying Village represented more than just a founding site. It symbolized the close relationship between the guerrilla force and local rural society. The Hong Kong Brigade depended heavily on villagers for shelter, food, intelligence, guidance, and protection. This mutual support between soldiers and civilians formed the foundation of sustained resistance in occupied Hong Kong.',

        'hk_brigade_model_section_2_title' => 'The Only Organized Resistance Force in Occupied Hong Kong',
        'hk_brigade_model_section_2_p1' => 'The Hong Kong Brigade is widely recognized as the only organized armed resistance force that continuously operated throughout the three years and eight months of Japanese occupation. Historical records consistently highlight this status. The Hong Kong Museum of History notes that after the fall of Hong Kong in 1941, civilians suffered greatly, while the Hong Kong Brigade, led by the Communist guerrilla forces, carried out rescue operations, intelligence work, and resistance activities, contributing to the global anti-fascist war.',
        'hk_brigade_model_section_2_p2' => 'The term “organized” is crucial for understanding the brigade. It was not a loose collection of resistance groups, but a structured military organization with clear leadership, unit divisions, operational zones, and coordinated tasks. It established detachments across different regions and maintained operations through communication stations, intelligence networks, mass mobilization, and logistical support.',
        'hk_brigade_model_section_2_p3' => 'This organizational structure allowed the brigade to perform multiple roles simultaneously. It could fight, rescue, gather intelligence, conduct propaganda, operate in both rural and urban environments, and use both land and maritime networks. As a result, the Hong Kong Brigade became more than a guerrilla unit—it became the core of organized resistance in occupied Hong Kong.',

        'hk_brigade_model_section_3_title' => 'Organization and Functional Division of the Hong Kong-Kowloon Independent Brigade',
        'hk_brigade_model_section_3_p1' => 'The organization of the Hong Kong-Kowloon Independent Brigade evolved with the changing war situation. In its early stage, it was formed through the merger of several armed work teams entering the New Territories. Later, according to regional conditions and operational needs, it gradually developed into different units operating in Sai Kung, Sha Tau Kok, Yuen Long, Lantau Island, maritime zones, and urban areas. These were not merely geographic divisions, but functional structures shaped by Hong Kong’s unique wartime environment.',
        'hk_brigade_model_section_3_p2' => 'Sai Kung and Sha Tau Kok, with their mountainous terrain and rural villages, were suitable for establishing base areas, communication stations, and short-weapon guerrilla units. Yuen Long and the northwestern New Territories, connected to the Shenzhen River region, played an important role in transport, escort, and material transfer. The Lantau and maritime units used islands and sea routes to conduct naval transport, escort missions, and maritime operations. Urban units operated inside Hong Kong and Kowloon, focusing on intelligence gathering, propaganda, underground communication, and sabotage operations.',
        'hk_brigade_model_section_3_p3' => 'This division reflected the brigade’s adaptation to Hong Kong’s geography and social environment. With its small territory and heavy Japanese military presence, Hong Kong could not support large rural base areas like inland China. Therefore, the brigade had to operate in a flexible, dispersed, and concealed manner: mountains provided hiding places, the sea enabled mobility, cities enabled intelligence gathering, and villages provided logistical support. This was the distinctive nature of Hong Kong’s resistance behind enemy lines.',

        'hk_brigade_model_section_4_title' => 'Composition of Members and Local Participation',
        'hk_brigade_model_section_4_p1' => 'The members of the Hong Kong-Kowloon Independent Brigade included core cadres from the Guangdong People’s Anti-Japanese Guerrilla Force as well as a large number of local Hong Kong youths, workers, students, indigenous villagers, and rural residents. It was not an external force detached from Hong Kong society, but a resistance army that grew within local communities. Historical materials emphasize that the vast majority of its members were Hong Kong residents who risked their lives to join the resistance, reflecting a strong tradition of patriotism among Hong Kong people.',
        'hk_brigade_model_section_4_p2' => 'This local participation gives the brigade’s history special significance. After the occupation of Hong Kong, ordinary people faced difficult choices: joining the guerrillas risked Japanese retaliation, while assisting transport or hiding personnel could endanger entire families. Yet many youths and villagers still chose to participate—some took up arms, some guided operations, some provided food, others delivered intelligence, and many supported underground communication within villages.',
        'hk_brigade_model_section_4_p3' => 'Therefore, the story of the brigade is not only the story of armed fighters, but also of countless ordinary Hong Kong residents. It was these seemingly small contributions that sustained the resistance in enemy-controlled territory. Anti-Japanese efforts existed not only on battlefields, but also in village houses, docks, fishing boats, mountain paths, ancestral halls, schools, and secret communication points.',

        'hk_brigade_model_section_5_title' => 'Resistance in Strategic Enemy-Controlled Territory',
        'hk_brigade_model_section_5_p1' => 'Hong Kong held significant strategic importance in Japanese military planning. Historical records indicate that it served as a transportation hub and naval relay base in the Pacific, as well as a key position for Japanese expansion into mainland China and Southeast Asia. Japan even established the “Hong Kong Occupation Government” directly under its military headquarters, highlighting its strategic value.',
        'hk_brigade_model_section_5_p2' => 'Because of this importance, the brigade’s activities were not merely local resistance. It operated across transport routes, ports, airports, warehouses, sea lanes, and urban centers controlled by Japanese forces, effectively disrupting key nodes in the Japanese military system. The brigade gathered intelligence on ship movements, troop deployments, and military facilities, and provided information to Allied forces, linking its work directly to the global anti-fascist war.',
        'hk_brigade_model_section_5_p3' => 'This also explains why the brigade should not be viewed merely as local history. Although its activities were centered in Hong Kong and surrounding areas, its significance connected the Chinese War of Resistance with the wider Pacific War. Hong Kong was a crucial point in Japan’s southern expansion strategy, and the brigade’s resistance weakened occupation control, preserved anti-Japanese forces, and supported Allied intelligence and rescue operations.',

        'hk_brigade_model_section_6_title' => 'Multiple Forms of Anti-Japanese Operations',
        'hk_brigade_model_section_6_p1' => 'The work of the Hong Kong-Kowloon Independent Brigade was not limited to armed combat. Its methods of resistance were highly diverse, including guerrilla attacks, sabotage, counter-espionage, propaganda, intelligence gathering, escort and rescue operations, maritime transport, material transfer, logistical medical support, and mass mobilization. This diversity was a key reason for its survival under the extreme pressure of Japanese occupation in Hong Kong.',
        'hk_brigade_model_section_6_p2' => 'In military operations, the brigade used small-scale, highly mobile tactics to strike Japanese forces and collaborationist organizations, avoiding large-scale direct confrontations that would have been disadvantageous. In intelligence work, it relied on networks across urban areas, rural villages, and maritime routes to collect information on enemy troop movements, ship traffic, and military installations. In rescue operations, it helped intellectuals, democrats, and Allied personnel escape danger. In propaganda work, it used leaflets and clandestine printing to boost morale and undermine Japanese occupation authority.',
        'hk_brigade_model_section_6_p3' => 'These activities were interconnected. Guerrilla warfare required intelligence support; rescue operations depended on transportation networks; intelligence work required concealment in cities and villages; and maritime operations relied on fishermen and island bases. Therefore, the brigade cannot be understood from a single perspective—it was a comprehensive anti-Japanese organization integrating military, intelligence, transportation, propaganda, and mass mobilization work.',

        'hk_brigade_model_section_7_title' => 'Sacrifice, Commemoration, and Historical Legacy',
        'hk_brigade_model_section_7_p1' => 'The brigade’s activities came at a heavy cost. Many fighters, couriers, civilian activists, and supporting villagers were killed during battles, arrests, torture, and Japanese raids. After the war, multiple memorial sites in Hong Kong preserved this memory, including the Sai Kung Wong Chuk Wan Martyrs Memorial, the Wu Kau Tang Martyrs Memorial, and the more recently established Lau Chun-sang Anti-Japanese Heroes Group Memorial. The Antiquities and Monuments Office notes that the East River Column Heritage Trail not only records the suffering and sacrifice of the brigade during the war, but also embodies its spirit of defending the homeland with unwavering resilience.',
        'hk_brigade_model_section_7_p2' => 'These memorials remind us that the history of the brigade is not abstract military history, but one deeply rooted in Hong Kong’s landscapes of mountains, seas, and villages. Place names such as Wong Mo Ying, Chek Keng, Wu Kau Tang, Wong Chuk Wan, Sha Tau Kok, and Lung Kwu Tan are not only geographic locations but also spaces of memory. They preserve the actions of guerrillas, the support of villagers, the names of the fallen, and the enduring spark of resistance in occupied Hong Kong.',

        'hk_brigade_model_section_8_title' => 'Conclusion: A Pillar of Hong Kong’s Wartime Resistance',
        'hk_brigade_model_section_8_p1' => 'The history of the Hong Kong-Kowloon Independent Brigade shows that occupied Hong Kong was not only a place of suffering, silence, and waiting. Even after the collapse of formal defense lines, resistance continued across mountains, villages, bays, and urban areas. The brigade defended civilians, supported the anti-Japanese war effort, and connected Hong Kong to the broader Chinese resistance and the global anti-fascist struggle.',
        'hk_brigade_model_section_8_p2' => 'The importance of this force lies not only in its military strength, but also in its deep roots within Hong Kong society. Youths, workers, students, indigenous residents, fishermen, villagers, and underground operatives all participated in different ways, making the brigade one of the most representative anti-Japanese forces in occupied Hong Kong.',
        'hk_brigade_model_section_8_p3' => 'Looking back today, the brigade is not merely the name of a guerrilla unit. It represents courage, solidarity, and responsibility shown by Hong Kong people during wartime. Its legacy is a historical memory of Hong Kong resistance: even in the darkest times, people chose to stand up, defend their homeland, and keep hope alive.',

         // tab 3
        'intelligence_title' => 'Intelligence and Rescue',
        'intelligence_subtitle' => 'Spies, Signals, and Rescues',
        'intelligence_intro' => 'The struggle against Japanese occupation was not fought solely with weapons. It was also carried out along hidden mountain paths, secret communication routes, intelligence stations, and escape networks. Working alongside underground operatives and local supporters, resistance fighters rescued cultural figures, prisoners of war, and Allied personnel while gathering military intelligence that contributed to the wider Allied war effort.',

        'intelligence_section_1_title' => 'Keeping Hong Kong Connected Under Occupation',
        'intelligence_section_1_p1' => 'After the fall of Hong Kong, Japanese authorities moved quickly to tighten their control. Roads, ports, and transportation routes were placed under strict supervision, curfews were imposed, and extensive searches were conducted throughout the territory. Under these conditions, the work of the Hong Kong and Kowloon Brigade and its predecessor guerrilla units extended far beyond armed resistance. Intelligence gathering, clandestine transportation, rescue missions, and assistance to Allied personnel became central elements of the struggle.',
        'intelligence_section_1_p2' => 'Unlike military engagements, these operations often unfolded in silence and secrecy. A meeting between couriers, a mountain trail, a fishing boat, or even a small grocery shop could determine whether a rescue succeeded or whether critical intelligence reached Allied hands. Through these activities, occupied Hong Kong remained connected to both China\'s resistance movement and the wider international struggle against fascism.',
        
        'intelligence_section_2_title' => 'The Great Rescue Operation',
        'intelligence_section_2_p1' => 'One of the most remarkable undertakings of the occupation period was the operation later known as the Great Rescue. Following Hong Kong\'s surrender in December 1941, many prominent Chinese intellectuals, journalists, political activists, and anti-Japanese figures found themselves trapped within occupied territory. Japanese authorities launched extensive searches, seeking to identify, arrest, or force the surrender of individuals considered politically undesirable.',
        'intelligence_section_2_p2' => 'In response, underground Communist Party networks, the Guangdong People\'s Anti-Japanese Guerrilla Forces, and the armed work teams that later formed the Hong Kong and Kowloon Brigade organised a large-scale rescue operation. Beginning on 25 December 1941 and continuing until 22 November 1942, when journalist Zou Taofen reached a Communist-controlled base area in northern Jiangsu, the operation lasted approximately eleven months. During that time, more than 300 prominent cultural and democratic figures and approximately 800 people in total were successfully evacuated from occupied Hong Kong.',

         //model
        'intelligence_model_section_1_title' => 'Crossing the Blockade',
        'intelligence_model_section_1_p1' => 'The Great Rescue was far more than a simple evacuation. Those being rescued had to be moved through Japanese checkpoints, military cordons, bandit-controlled territory, and difficult mountain terrain before reaching guerrilla-controlled areas in Guangdong. Two principal routes emerged. The eastern route passed through Ngau Chi Wan, Kowloon Pass, Sai Kung, Kei Ling Ha, or Sham Chung Bay, before crossing Mirs Bay to guerrilla-controlled areas in Huiyang. The western route travelled through Tsuen Wan, Tai Mo Shan, Yuen Long, and Lok Ma Chau, before crossing the Shenzhen River to the guerrilla base at Pak Shek Lung.',
        'intelligence_model_section_1_p2' => 'The journeys were physically demanding and extremely dangerous. Many of those being rescued were urban intellectuals unfamiliar with long-distance travel through mountains and rural areas. Escort teams had to move discreetly, avoid patrols, provide food and shelter, and ensure that entire groups could travel without attracting attention. The success of the operation demonstrated the existence of an extensive and highly effective underground transportation network operating within occupied Hong Kong.',

        'intelligence_model_section_2_title' => 'Saving China\'s Cultural and Intellectual Community',
        'intelligence_model_section_2_p1' => 'The significance of the Great Rescue extended far beyond the individuals involved. Among those evacuated were prominent figures such as He Xiangning, Liu Yazi, Zou Taofen, Mao Dun, Xia Yan, Shen Zhiyuan, Zhang Youyu, Hu Sheng, Fan Changjiang, and Liang Shuming. Many of these individuals would go on to play influential roles in Chinese politics, journalism, literature, education, and public life.',
        'intelligence_model_section_2_p2' => 'According to contemporary accounts, resistance operatives successfully guided these individuals through Japanese patrols, checkpoints, and dangerous terrain to safety in the Chinese interior. Writer Mao Dun later described the operation as "the greatest rescue effort since the beginning of the War of Resistance." For Hong Kong, the operation demonstrated that even in the earliest stages of occupation, the city was not completely sealed off from the outside world. Between its urban districts, villages, mountains, and coastal waters, hidden routes of escape and resistance continued to exist.',

        'intelligence_model_section_3_title' => 'Rescuing Allied Personnel',
        'intelligence_model_section_3_p1' => 'The Brigade\'s rescue activities also extended to Allied servicemen.
         In January 1942, Lieutenant Colonel Lindsay Ride, who had escaped from the Sham Shui Po Prisoner of War Camp, received assistance from the armed work teams that later became part of the Hong Kong and Kowloon Brigade. Through routes in Sai Kung and the New Territories, he eventually reached safety in Free China. According to commemorative publications of the Hong Kong and Kowloon Brigade, the successful rescue of Ride and three companions helped establish cooperation between the Guangdong guerrilla forces and British military authorities.',
        'intelligence_model_section_3_p2' => 'The long-term consequences proved significant. Following his escape, Ride recommended the creation of a specialised intelligence and rescue organisation dedicated to assisting prisoners of war and gathering information within occupied territory. This recommendation led to the establishment of the British Army Aid Group (BAAG), which would become one of the most important Allied intelligence organisations operating in occupied Hong Kong and South China.',

        'intelligence_model_section_4_title' => 'Intelligence Stations: X, Y, and Z',
        'intelligence_model_section_4_p1' => 'Cooperation between the Hong Kong and Kowloon Brigade and the British Army Aid Group gradually evolved into an extensive intelligence network. In November 1942, BAAG representative Li Yiu-Biu travelled to Sai Kung to discuss intelligence cooperation with Brigade leaders Choi Kwok-Leung and Chan Tat-Ming. The result was the establishment of three important communication stations: X Station at Sha Yue Chung, Y Station at Chek Kang, Sai Kung, Z Station in a grocery shop on Portland Street, Sham Shui Po',
        'intelligence_model_section_4_p2' => 'These stations served as centres for intelligence exchange, courier operations, personnel transfers, and clandestine communications. The Portland Street station was operated by Wong Cho-Mei, who maintained the appearance of an ordinary shopkeeper while secretly coordinating underground activities. After an Allied agent was captured and revealed information under interrogation, Japanese authorities destroyed the Z Station and arrested members of Wong\'s family. Following the war, Wong was awarded the Member of the Order of the British Empire (MBE) in recognition of his contributions to the Allied cause.',

        'intelligence_model_section_5_title' => 'Y Station at Chek Kang',
        'intelligence_model_section_5_p1' => 'Among these intelligence stations, Y Station held particular significance. Located within the historic residence known as "Tin Shui Lau Fong" at Chek Kang in Sai Kung, it became the only British Army Aid Group intelligence station operating within occupied territory itself. The station\'s security depended heavily upon protection provided by the Hong Kong and Kowloon Brigade.',
        'intelligence_model_section_5_p2' => 'To reduce suspicion, many BAAG personnel stationed there were Chinese or Eurasian. Among them were Li Yiu-Biu and Tam Oi-Lai, a medical student from the University of Hong Kong. In addition to intelligence work, Tam helped train Brigade medics in first aid and assisted in the treatment of wounded resistance fighters. This cooperation extended beyond intelligence collection and reflected a broader partnership involving medical support, communications, logistics, and personnel assistance.',

        'intelligence_model_section_6_title' => 'Intelligence Gathering and Allied Operations',
        'intelligence_model_section_6_p1' => 'Occupied Hong Kong held considerable military importance. Its ports, shipyards, airfields, ammunition depots, batteries, and barracks supported Japanese operations across South China and the Pacific. According to Tsang Sang foreword to The History of the Hong Kong and Kowloon Independent Brigade, the Brigade made important contributions to Allied intelligence by monitoring Japanese shipping movements, troop deployments, and military facilities. Information gathered by resistance operatives was passed to Allied forces and helped improve the effectiveness of American air operations against Japanese targets.',
        'intelligence_model_section_6_p2' => 'Such work required patience, discipline, and secrecy. In 1944, the Brigade reportedly established an observation post at Yue Lam Court in Hong Kong\'s Mid-Levels district, maintaining round-the-clock surveillance of Japanese naval activity in Victoria Harbour. Although these operations lacked the drama of open combat, they exposed intelligence personnel and their families to constant danger. Discovery often meant arrest, torture, or execution.',
        
        'intelligence_model_section_7_title' => 'Reconnaissance and Allied Air Raids',
        'intelligence_model_section_7_p1' => 'The Brigade\'s cooperation with the British Army Aid Group also included photographic reconnaissance. According to The History of the Hong Kong and Kowloon Brigade, BAAG requested assistance in photographing key Japanese military facilities throughout Hong Kong. Resistance fighters escorted Allied personnel to elevated observation points where they photographed Kai Tak Airport, ammunition depots, artillery batteries, barracks, and other installations.',
        'intelligence_model_section_7_p2' => 'Not long afterwards, Allied aircraft carried out attacks against several of these targets, including facilities at Causeway Bay, Kai Tak Airport, Lei Yue Mun, and the Taikoo Dockyard.
         These events illustrate how local intelligence gathered inside occupied Hong Kong became integrated into broader Allied military operations.',
         
        'intelligence_model_section_8_title' => 'The Rescue of Lieutenant Klier',
        'intelligence_model_section_8_p1' => 'One of the most famous rescue operations involved American pilot Lieutenant Robert E. Klier. In February 1944, Klier parachuted into Hong Kong following an air operation connected to attacks on Kai Tak Airport. Japanese authorities immediately launched an extensive search involving more than a thousand personnel across Sai Kung and Sha Tin.',
        'intelligence_model_section_8_p2' => 'The Hong Kong and Kowloon Brigade responded by organising a complex rescue effort. According to historical accounts, Liu Hei Zai and his companions moved Klier between safe locations before hiding him in a cave near Shek Lung Tsai Village for two weeks. To divert Japanese attention, the Brigade launched a series of operations, including attacks on collaborators, the Kai Tak Airport raid, and the distribution of anti-Japanese leaflets in urban districts. Once the search pressure eased, Klier was escorted across mountain routes and eventually transferred by sea to the headquarters of the Dongjiang Column in Ping Shan.',

        'intelligence_model_section_9_title' => 'The Legacy of the Klier Rescue',
        'intelligence_model_section_9_p1' => 'After reaching safety, Klier met with Dongjiang Column commander Tsang Sang before continuing to Allied-controlled territory. He later expressed deep gratitude to the resistance fighters who had rescued him and specifically praised Choi Kwok-Leung, Wong Koon-Fong, Liu Hei Zai, and Tam Tin for their assistance.',
        'intelligence_model_section_9_p2' => 'According to the Brigade\'s 80th Anniversary Commemorative Publication, the rescue of Lieutenant Klier also helped establish formal cooperation between the United States military and the Dongjiang Column. The operation demonstrated the Brigade\'s ability to combine intelligence gathering, concealment, transportation, diversionary attacks, maritime operations, and long-distance escort missions within a single coordinated effort.',

        'intelligence_model_section_10_title' => 'Hong Kong and the International Anti-Fascist War',
        'intelligence_model_section_10_p1' => 'The intelligence and rescue work carried out by the Hong Kong and Kowloon Brigade connected occupied Hong Kong directly to the wider international struggle against fascism. According to commemorative Brigade publications, the Dongjiang Column rescued 89 foreign nationals, most of whom were assisted by the Hong Kong and Kowloon Brigade and its predecessor units. The Brigade also maintained extensive intelligence cooperation with Allied forces, contributing to military operations against Japan and supporting the broader Allied war effort.',
        'intelligence_model_section_10_p2' => 'This is an important aspect of Hong Kong\'s wartime history. Although Hong Kong fell in December 1941, it did not disappear from the Allied war effort. Through intelligence gathering, rescue operations, communications networks, and cooperation with Allied organisations, the territory remained an active part of the wider conflict. Hong Kong\'s wartime experience therefore belongs not only to local history, but also to the global history of the Second World War.',

        'intelligence_model_section_11_title' => 'The Risks Behind the Network',
        'intelligence_model_section_11_p1' => 'Intelligence and rescue work often carried risks equal to, or greater than, those faced in combat. Participants included guerrilla fighters, couriers, translators, students, medical workers, shopkeepers, and villagers. Many never carried weapons, yet they faced the same possibility of arrest, torture, and execution.',
        'intelligence_model_section_11_p2' => 'The destruction of Z Station operated by Wong Cho-Mei illustrates these dangers. What appeared to be an ordinary grocery store concealed an important communications hub. Once exposed, entire families could become targets of Japanese reprisals. These stories remind us that resistance was not confined to battlefields. It also took place behind shop counters, along mountain trails, in fishing boats, and within ordinary homes.',

        'intelligence_model_section_12_title' => 'Conclusion: Lifelines in the Darkness',
        'intelligence_model_section_12_p1' => 'The intelligence and rescue operations of the Hong Kong and Kowloon Brigade ensured that occupied Hong Kong remained more than an isolated and controlled city. Even under strict Japanese rule, people continued to carry information across mountains and bays, guide refugees to safety, assist Allied personnel, and maintain communication with the outside world.',
        'intelligence_model_section_12_p2' => 'These efforts saved lives, preserved vital connections, and sustained resistance during some of Hong Kong\'s darkest years. Perhaps more than any other aspect of the Brigade\'s history, its intelligence and rescue work reveals the courage, ingenuity, and humanitarian spirit that allowed resistance to endure under occupation.',

      //tab 4
        'the_underground_title' => 'Anti-Japanese resistance network',
        'the_underground_subtitle' => 'The Underground Resistance Network',
        'the_underground_intro' => 'The Hong Kong and Kowloon Brigade was able to continue operating throughout the three years and eight months of Japanese occupation because it relied on far more than armed fighters alone.',

        'the_underground_section_1_title' => 'The People and Places That Sustained Resistance',
        'the_underground_section_1_p1' => 'Guerrilla warfare, intelligence gathering, rescue missions, and maritime operations all depended upon an extensive and highly secretive support network. This network included villagers, fishermen, couriers, shopkeepers, women, young people, religious figures, medical workers, and underground operatives. It stretched across mountain villages, islands, coastal inlets, urban neighbourhoods, and border routes throughout Hong Kong.',
        'the_underground_section_1_p2' => 'Many of these individuals never carried weapons, and many of their names were never fully recorded. Yet their contributions enabled resistance fighters to find shelter, obtain food and supplies, transmit intelligence, escort personnel, evade searches, and continue operating under occupation. In the foreword to The History of the Hong Kong and Kowloon Independent Brigade, Tsang Sang observed that the Brigade was "an army of the people of Hong Kong and Kowloon," and that every achievement it accomplished depended upon the support of the local population.',

        'the_underground_section_2_title' => 'A Network Linking Mountains, Bays, and Cities',
        'the_underground_section_2_p1' => 'The underground resistance network was not a single route or organisation. Rather, it was a web connecting people and places across Hong Kong. Locations such as Sai Kung, Sha Tau Kok, Wu Kau Tang, Chek Kang, Sham Chung, Yuen Long, Lantau Island, Cheung Chau, Tai Po, and urban Kowloon all contributed in different ways. Some served as guerrilla bases. Others functioned as intelligence stations, supply depots, temporary shelters, or meeting points.',
        'the_underground_section_2_p2' => 'The strength of the network lay in its ability to connect different functions. Combat operations required intelligence. Intelligence depended on communication stations. Rescue missions required guides and safe houses. Maritime operations required boats and experienced navigators. Logistics depended upon food, medicine, and transportation. Injured personnel required treatment and protection. Each link appeared small in isolation, yet the loss of any one component could jeopardise an entire operation. The underground network was therefore more than a support system—it was the lifeline that enabled resistance to survive in occupied Hong Kong.',

        //Model
        'the_underground_model_section_1_title' => 'Communication Stations: The Nerve Centres of Resistance',
        'the_underground_model_section_1_p1' => 'Among the most important elements of the network were its communication stations. These facilities transmitted intelligence, relayed documents, received personnel, coordinated transportation, and distributed supplies. In many cases they also served as temporary headquarters, safe houses, or emergency shelters. Communication stations were deliberately concealed within ordinary locations such as village homes, grocery shops, fish markets, ancestral halls, and remote residences.',
        'the_underground_model_section_1_p2' => 'One notable example was the Lee Family House at Sham Chung. Historical records indicate that the Sham Chung station connected multiple routes throughout the New Territories, linking Yung Shue O, Kei Ling Ha, Shap Sze Heung, Mui Tsz Lam, Chung Mei, Chek Kang, Sai Kung Market, and Pak Tam. Large quantities of supplies passed through the station on their way to resistance forces in Guangdong, while intelligence gathered across Hong Kong was transmitted through the network to Brigade headquarters.',

        'the_underground_model_section_2_title' => 'The Risks Faced by Ordinary Families',
        'the_underground_model_section_2_p1' => 'The operation of communication stations often depended upon ordinary households willing to assume extraordinary risks. The Lee Family House and its adjoining structures served as guerrilla accommodation during the occupation. Hidden passages allowed resistance fighters to escape into the hills during Japanese sweeps. Members of the Lee family also assisted in acquiring rice coupons and food supplies for the Brigade. According to historical records, Lee Yuen-Yuk and Lee Wah-San were arrested by Japanese authorities because of their assistance to the resistance and subjected to severe torture, including water torture.',
        'the_underground_model_section_2_p2' => 'Stories such as these remind us that resistance did not occur only on battlefields. It also took place in kitchens, grocery stores, fish markets, and village homes. Some people prepared meals for resistance fighters. Others provided shelter, delivered messages, or concealed fugitives. Their actions, though often overlooked, formed the foundation upon which the Brigade survived.',

        'the_underground_model_section_3_title' => 'Village Communities and Local Support',
        'the_underground_model_section_3_p1' => 'Rural communities throughout the New Territories played an essential role in sustaining resistance. Villagers possessed intimate knowledge of mountain trails, water sources, agricultural land, and transportation routes. They provided guides, food, shelter, intelligence, and warnings of impending Japanese operations. When resistance fighters were wounded or ill, local residents often cared for them at considerable personal risk. Villages were therefore not merely the backdrop to resistance activities; they formed one of the central pillars of the underground network.',
        'the_underground_model_section_3_p2' => 'The costs could be severe. Japanese forces frequently employed collective punishment, intimidation, and torture in attempts to force villagers to reveal guerrilla positions. Many chose to remain silent despite the risks. This relationship between the Brigade and local communities gave Hong Kong\'s resistance movement a strong popular foundation. The Hong Kong and Kowloon Brigade did not operate independently from society—it survived because of it.',

        'the_underground_model_section_4_title' => 'Wu Kau Tang: A Village of Strategic Importance',
        'the_underground_model_section_4_p1' => 'Few places better illustrate the importance of rural communities than Wu Kau Tang. In February 1943, senior representatives of the Guangdong Provincial Communist leadership and the Dongjiang military-political leadership convened a meeting near Wu Kau Tang known historically as the Wu Kau Tang Conference. The Hong Kong and Kowloon Brigade was responsible for logistical arrangements and security during the gathering. The conference demonstrates that New Territories villages served not only as guerrilla operating areas but also as centres of planning, coordination, and strategic decision-making. Wu Kau Tang was also associated with one of the most important communications links in South China.',
        'the_underground_model_section_4_p2' => 'Between April 1942 and March 1943, the only radio station connecting Communist organisations and anti-Japanese guerrilla forces in Guangdong with Yan\'an was located at nearby Shek Shui Kan Village. The Hong Kong and Kowloon Brigade helped select the site and provided its protection. In an era of occupation and isolation, maintaining such a communications link was essential to the wider resistance effort throughout South China.',

        'the_underground_model_section_5_title' => 'Fishermen and Maritime Connections',
        'the_underground_model_section_5_p1' => 'Surrounded by water, Hong Kong relied heavily upon maritime transportation. Fishermen and boatmen became indispensable members of the underground network. Their knowledge of tides, channels, islands, and sheltered anchorages allowed them to transport people, supplies, and intelligence while avoiding Japanese patrols. Maritime operations often appeared less visible than combat, but they involved significant danger. Japanese gunboats, patrol vessels, weather conditions, and navigational hazards could all threaten an operation.',
        'the_underground_model_section_5_p2' => 'The sacrifice of boatman Leung Hak and five members of his family during the fatal mission that claimed the life of Liu Chun-Xiang near Lung Kwu Chau and Sha Chau illustrates that the risks of resistance were shared by civilians as well as fighters. Through their boats, experience, and courage, fishermen helped transform Hong Kong\'s coastal waters into an extension of the resistance network.',

        'the_underground_model_section_6_title' => 'Merchants, Fish Markets, and Supply Networks',
        'the_underground_model_section_6_p1' => 'Life under occupation was marked by severe shortages. Food, medicine, fuel, clothing, metal goods, and transportation resources became increasingly difficult to obtain. Maintaining resistance operations therefore required extensive support from local merchants and business owners. One example was Tsui Koon-Sang, proprietor of the Muk Lei Fish Market in Sai Kung. According to historical accounts, Tsui initially intended to leave home and join the guerrillas directly. Instead, Brigade member Wong Koon-Fong persuaded him to continue operating his business, using it as a means of supporting resistance activities.',
        'the_underground_model_section_6_p2' => 'By maintaining commercial networks and relationships, individuals like Tsui helped acquire supplies, gather information, and facilitate communications under the guise of ordinary business activities. These examples demonstrate that participation in resistance took many forms. Remaining in civilian occupations often proved just as valuable as taking up arms.',

        'the_underground_model_section_7_title' => 'Women and Youth: The Hidden Strength of Resistance',
        'the_underground_model_section_7_p1' => 'Women and young people played vital roles throughout the underground network. They served as couriers, caregivers, propagandists, guides, messengers, and organisers. In some circumstances, Japanese authorities were less likely to suspect women and younger individuals, enabling them to move more freely between villages, urban districts, and transportation routes.',
        'the_underground_model_section_7_p2' => 'These responsibilities were both dangerous and essential. Delivering a letter, escorting a visitor, or hiding an injured fighter could lead to arrest, interrogation, or torture. Although their contributions are often overshadowed by accounts of military operations, many intelligence, rescue, and logistical missions would have been impossible without their participation.',
        
        'the_underground_model_section_8_title' => 'Ling Leung: "The Mother of the Guerrillas"',
        'the_underground_model_section_8_p1' => 'One of the most memorable figures in the Brigade\'s support network was Ling Leung of Ngong Wo Village in Sai Kung. According to historical records, she devoted herself to caring for resistance fighters and became affectionately known as "the Mother of the Guerrillas." Ling allowed her home to be used by the Brigade\'s quartermaster section and encouraged her two sons to participate in resistance work. In early 1943, she reportedly saved the life of resistance worker Leung Suet-ying using traditional remedies during a serious illness.',
        'the_underground_model_section_8_p2' => 'Her story highlights an often-overlooked aspect of wartime resistance: care. Wars involve not only combat but also sickness, hunger, exhaustion, and fear. Those who provided shelter, food, medicine, and emotional support made continued resistance possible. Ling Leung is remembered not because she commanded troops, but because she helped sustain those who did.',

        'the_underground_model_section_9_title' => 'Religious Sites as Places of Refuge',
        'the_underground_model_section_9_p1' => 'Religious institutions also played a role within the underground network. Temples, churches, and ancestral halls served not only as centres of community life but sometimes as places of refuge, recovery, and clandestine meetings. One notable example involved Venerable Fat Ho, abbot of Po Lin Monastery on Lantau Island.',
        'the_underground_model_section_9_p2' => 'In 1944, during a Japanese sweep of the island, Brigade deputy commander Lo Fung was recovering from illness at the monastery. When Japanese troops searched the premises, Fat Ho disguised Lo as a monk and concealed him among worshippers attending religious services. Although Japanese soldiers later interrogated and physically assaulted the abbot, he refused to reveal Lo\'s whereabouts. The incident illustrates how religious figures and sacred spaces could become important protective barriers against occupation authorities.',
       
        'the_underground_model_section_10_title' => 'Public Mobilisation and Community Organisation',
        'the_underground_model_section_10_p1' => 'The underground resistance network involved more than concealment and transportation. The Brigade maintained dedicated sections responsible for public mobilisation, propaganda, and community outreach. According to the 80th Anniversary Commemorative Publication of the Hong Kong and Kowloon Brigade, the Brigade\'s Political Training Department included officers responsible for public mobilisation, propaganda, and united-front work, while local districts maintained their own community organisers.',
        'the_underground_model_section_10_p2' => 'These roles reflected an important reality of resistance warfare. Military operations alone could not sustain a long-term struggle. Public support was necessary to secure intelligence, food supplies, recruits, transportation, and protection. Through community engagement and political education, the resistance became not merely the work of armed units, but a broader social effort involving many sectors of Hong Kong society.',
       
        'the_underground_model_section_11_title' => 'Trust, Secrecy, and Sacrifice',
        'the_underground_model_section_11_p1' => 'At the heart of the underground network lay trust. Couriers trusted their contacts. Villagers trusted the resistance fighters they sheltered. Guides trusted those they escorted. Shopkeepers trusted that secrets would remain hidden. Under the constant threat of Japanese searches, informants, and collaborationist networks, a single mistake could have devastating consequences. The network was both resilient and fragile.',
        'the_underground_model_section_11_p2' => 'It depended upon personal relationships, local reputation, and shared conviction. Many paid a heavy price. Some were arrested. Others endured torture. Families suffered reprisals. Many lost their lives. Most were not professional soldiers, yet they accepted risks comparable to those faced by combatants. The history of the underground resistance network is therefore also the history of countless ordinary individuals whose names often remain unknown.',

        'the_underground_model_section_12_title' => 'Conclusion: Resistance Was Never the Work of One Person',
        'the_underground_model_section_12_p1' => 'The history of the Hong Kong and Kowloon Brigade demonstrates that resistance in occupied Hong Kong was never carried out by armed fighters alone. It was sustained by a vast network of people, places, routes, and relationships. Villages provided shelter. Bays connected resistance forces to the outside world. Communication stations transmitted intelligence. Merchants secured supplies. Women and youth carried messages. Religious institutions offered sanctuary. Families accepted enormous risks.',
        'the_underground_model_section_12_p2' => 'Because of this network, the Brigade was able to continue operating despite intense Japanese control. The story of Hong Kong\'s resistance therefore belongs not only to battlefields, but also to village homes, fish markets, piers, temples, mountain trails, and city streets. The underground resistance network reminds us that defending one\'s home does not always require carrying a weapon. Sometimes it means guiding a stranger through the darkness, delivering a message, offering shelter, keeping a secret, or choosing solidarity in the face of danger.'
     ]
];
