<?php

return [
     'people-and-stories' => [
        'title' => 'Anti-Japanese War Figures',
        'subtitle' => 'Those Who Stood Up',
        'intro' => 'The history of Hong Kong\'s resistance during the Second World War is not only a story of battles, organisations, and operations. It is also a story of individuals. Some were guerrilla commanders. Others served in pistol squads, intelligence networks, rescue operations, transportation routes, or support services. Many began as ordinary villagers, students, workers, merchants, fishermen, or religious figures before making decisions that would change the course of their lives.',

        // Tabs
        'tab_1' => 'Those Who Stood Up',
        'tab_2' => 'Villages That Remember',
        'tab_3' => 'Acts of Courage and Care',
        'tab_4' => 'Stories of Rescue',

        // tab 1
        'stoodUp_section_1_title' => 'The People Behind the Resistance',
        'stoodUp_section_1_p1' => 'This section does not attempt to provide a complete biography of every individual associated with Hong Kong\'s wartime resistance. Rather, it introduces some of the people whose experiences reveal the diversity of those who participated in the struggle. According to historical records of the Hong Kong and Kowloon Brigade, the vast majority of Brigade members were Hong Kong residents, including indigenous villagers and young students. They risked their lives to participate in anti-Japanese activities and reflected a broad cross-section of Hong Kong society. Their stories transform resistance from an abstract historical concept into a history of real people—individuals with names, identities, choices, and sacrifices.',
        
        'stoodUp_section_2_title' => 'Choi Kwok-Leung: An Early Leader of the Hong Kong and Kowloon Brigade',
        'stoodUp_section_2_p1' => 'Choi Kwok-Leung was one of the key figures in the early development of the Hong Kong and Kowloon Brigade. When the Brigade was formally established at Wong Mo Ying Village in Sai Kung on 3 February 1942, Choi served as Brigade Commander, working alongside Political Commissar Chan Tat-Ming and others to organise resistance behind enemy lines.',
        'stoodUp_section_2_p2' => 'The challenges facing Choi and the Brigade\'s leadership were exceptional. They were not building an organisation in a secure rear area. They were attempting to create a resistance force within occupied territory, under conditions of food shortages, disrupted communications, Japanese surveillance, and constant military pressure. The Brigade needed to fight, relocate, rescue, communicate, and protect local communities while avoiding actions that might expose civilians to reprisals. Leadership in such circumstances required not only military judgement, but also a deep understanding of Hong Kong\'s geography, communities, and wartime realities.',

        // Model
        'stoodUp_model_section_1_title' => 'Chan Tat-Ming: From Student Activist to Resistance Leader',
        'stoodUp_model_section_1_p1' => 'Chan Tat-Ming served as Political Commissar when the Hong Kong and Kowloon Brigade was established. Before the war, he had been active in Hong Kong\'s student movement. His transition from student activism to resistance leadership illustrates how the war altered the lives of many young people in Hong Kong.',
        'stoodUp_model_section_1_p2' => 'Chan\'s responsibilities extended beyond military matters. He helped oversee organisation, political education, public mobilisation, propaganda, community relations, and the development of the Brigade itself. The survival of the Brigade depended not only on weapons, but also on discipline, trust, and support from local communities. Through the efforts of leaders such as Chan, the Brigade evolved from a collection of scattered guerrilla groups into a coordinated resistance organisation with a clear structure and social foundation.',

        'stoodUp_model_section_2_title' => 'Wong Koon-Fong: A Fighter Between Mountain and Sea',
        'stoodUp_model_section_2_p1' => 'Wong Koon-Fong was one of the Brigade\'s most active operational figures. He participated in resistance activities across Sai Kung, Sha Tin, transportation routes linking Kowloon and the New Territories, rescue operations, and numerous guerrilla actions. Brigade records identify him as one of the organisation\'s important wartime figures.',
        'stoodUp_model_section_2_p2' => 'His story reflects the realities faced by combat personnel in occupied Hong Kong. Because the territory was small and heavily garrisoned, resistance fighters could not rely on conventional warfare. Success depended on mobility, disguise, reconnaissance, surprise attacks, and rapid withdrawal. Individuals such as Wong formed the operational backbone that allowed guerrilla warfare to continue despite overwhelming odds.',

        'stoodUp_model_section_3_title' => 'Lau Hei-Zai: Between Legend and Reality',
        'stoodUp_model_section_3_p1' => 'Among all resistance figures associated with the Hong Kong and Kowloon Brigade, Lau Hei-Zai remains one of the most widely remembered. He participated in numerous operations in Sha Tin, Kowloon, Cha Kwo Ling, Kai Tak Airport, and other locations. His courage and ingenuity contributed to his reputation as one of the legendary figures of Hong Kong\'s wartime resistance.',
        'stoodUp_model_section_3_p2' => 'Yet his story should not be viewed solely through the lens of legend. Behind the popular image lay the dangerous realities of pistol-squad operations: identifying collaborators, protecting transportation routes, carrying out raids, supporting rescue missions, and withdrawing before enemy reinforcements arrived. These missions involved enormous risk. Failure could lead not only to the death of the participants but also to the destruction of entire resistance networks. Lau\'s enduring place in public memory reflects the courage, resourcefulness, and constant danger faced by resistance fighters operating behind enemy lines.',

        'stoodUp_model_section_4_title' => 'Fong Lan and the "Guerrillas Without Guns"',
        'stoodUp_model_section_4_p1' => 'Fong Lan was an important figure within the Brigade\'s Urban Squadron. Unlike rural guerrilla units, the Urban Squadron relied less on direct combat and more on intelligence gathering, communications, propaganda, sabotage, and clandestine organisation. For this reason, it became known as a "guerrilla force without guns."',
        'stoodUp_model_section_4_p2' => 'Members of the Urban Squadron operated in the heart of occupied Hong Kong and Kowloon. They faced Japanese military police, collaborationist police, informants, and extensive urban surveillance. Their existence reminds us that resistance was not confined to mountain trails and remote villages. It also took place in city streets, shops, banks, printing locations, and transportation networks.',

        'stoodUp_model_section_5_title' => 'Fung Chi: The Courage of a Courier',
        'stoodUp_model_section_5_p1' => 'Among the most respected women in the history of the Hong Kong and Kowloon Brigade was Fung Chi. She was the mother of Urban Squadron leader Fong Lan and actively supported her daughter\'s involvement in resistance work. She later volunteered as a courier, transporting intelligence despite the dangers involved. According to The History of the Hong Kong and Kowloon Brigade, Fung Chi was arrested in March 1944 while carrying intelligence materials.',
        'stoodUp_model_section_5_p2' => 'Historical records indicate that she endured severe torture but refused to reveal information about her comrades or the organisation. She was ultimately executed. In September 2020, Fung Chi was included in the Third National List of Renowned Anti-Japanese Martyrs and Heroic Groups. Her story illustrates that some of the most important acts of resistance occurred far from the battlefield. The work of a courier might involve nothing more than carrying a letter, delivering a message, or travelling along a familiar route. Yet these tasks often carried risks equal to those faced in combat.',

        'stoodUp_model_section_6_title' => 'Wong Cho-Mei: Linking Hong Kong to Allied Intelligence',
        'stoodUp_model_section_6_p1' => 'Wong Cho-mei played a crucial role in the intelligence cooperation between the Hong Kong and Kowloon Brigade and the British Army Aid Group (BAAG). One of the BAAG\'s communication centres in Kowloon—the famous Z Station on Portland Street—operated from a grocery store registered under his name. Members of his family also participated in the operation. When an Allied contact was captured and revealed information under interrogation, Japanese authorities destroyed the station and arrested members of Wong\'s family.',
        'stoodUp_model_section_6_p2' => 'Following the war, Wong received the Member of the Order of the British Empire (MBE) in recognition of his contributions to Allied operations. His experience illustrates how intelligence work often depended on ordinary businesses and family networks rather than military facilities.',

        'stoodUp_model_section_7_title' => 'Chan Chi-Yin, Wong Kam, and the Maritime Resistance',
        'stoodUp_model_section_7_p1' => 'Hong Kong\'s geography gave maritime operations a special significance. Figures such as Chan Chi-Yin and Wong Kam participated in maritime transportation, rescue missions, escort duties, and naval operations. Brigade records and commemorative publications identify them among the key personnel of the Maritime Squadron.',
        'stoodUp_model_section_7_p2' => 'Maritime resistance was exceptionally dangerous. Using small fishing vessels, sailing boats, and launches, these individuals navigated waters patrolled by Japanese gunboats and military craft. Their work expanded the geography of Hong Kong\'s resistance beyond mountains and villages to include Mirs Bay, Lung Kwu Chau, Sha Chau, Lantau Island, and the surrounding South China Sea.',

        'stoodUp_model_section_8_title' => 'Lau Chun-Xiang: A Hero of the Sea',
        'stoodUp_model_section_8_p1' => 'Lau Chun-Xiang was one of the most important figures associated with the Brigade\'s Lantau Island Squadron. In May 1943, he led six resistance fighters on a mission intended to establish communications between guerrilla areas in Bao\'an and Zhongshan. Their vessel was intercepted by Japanese gunboats near Lung Kwu Chau and Sha Chau. Following a fierce engagement, the vessel was sunk and Lau, his companions, and members of the boatman\'s family lost their lives.',
        'stoodUp_model_section_8_p2' => 'His story captures both the courage and the cost of maritime resistance. In 2023, the Lau Chun-Xiang Anti-Japanese Heroes Memorial Monument was unveiled at Lung Kwu Tan. It became Hong Kong\'s first monument dedicated to anti-Japanese heroes formally recognised at the national level.',

        'stoodUp_model_section_9_title' => 'Ling Leung: "The Mother of the Guerrillas"',
        'stoodUp_model_section_9_p1' => 'Not all resistance figures carried weapons. Ling Leung, a resident of Ngong Wo Village in Sai Kung, became known as "the Mother of the Guerrillas." She cared for resistance fighters, allowed her home to be used by the Brigade\'s quartermaster section, and encouraged her two sons to participate in resistance work.',
        'stoodUp_model_section_9_p2' => 'Her story reminds us that food, shelter, care, and emotional support were as essential to resistance as weapons and intelligence. The strength of Hong Kong\'s wartime resistance depended not only on those who fought, but also on those who sustained the fighters.',

        'stoodUp_model_section_10_title' => 'Venerable Fat Ho: A Protector in Times of War',
        'stoodUp_model_section_10_p1' => 'Venerable Fat Ho, abbot of Po Lin Monastery on Lantau Island, represents another dimension of resistance. In 1944, during a Japanese sweep of Lantau Island, Brigade Deputy Commander Lo Fung was recovering from illness at the monastery. Fat Ho concealed him from Japanese troops and refused to reveal his whereabouts despite being beaten during interrogation.',
        'stoodUp_model_section_10_p2' => 'His story demonstrates how religious institutions and religious leaders sometimes became part of the wider resistance network. Monasteries and temples, traditionally places of refuge and compassion, also became places where lives were protected under extraordinary circumstances.',

        'stoodUp_model_section_11_title' => 'The Lo Family of Nam Chung: Resistance as a Family Commitment',
        'stoodUp_model_section_11_p1' => 'The Lo family of Nam Chung, Sha Tau Kok, provides an important example of how resistance could involve entire families. The 80th Anniversary Commemorative Publication of the Hong Kong and Kowloon Brigade highlights members of the family, including Lo Hui-Yuet, Lo Yue-Chung, Lo Yu-Ching, and Lo Au-Fung, whose contributions are featured in exhibitions at the Hong Kong Sha Tau Kok Anti-Japanese War Memorial Hall.',
        'stoodUp_model_section_11_p2' => 'Their story demonstrates that resistance was not always an individual decision. Entire families and villages often became involved, sharing both the responsibilities and the risks associated with resistance work.',

        'stoodUp_model_section_12_title' => 'Students, Workers, Villagers, and Fishermen',
        'stoodUp_model_section_12_p1' => 'One of the most significant characteristics of the Hong Kong and Kowloon Brigade was the diversity of its membership. Its ranks included students, workers, indigenous villagers, fishermen, merchants, and people from many different backgrounds. Most had not been professional soldiers before the war. Some lost educational opportunities after Hong Kong fell. Others lost employment as factories and businesses closed. Many were drawn into resistance through community networks or patriotic movements.',
        'stoodUp_model_section_12_p2' => 'This broad social foundation helped make the Brigade more than a military organisation. Students brought energy and commitment. Workers contributed organisational experience. Villagers understood local geography and community relationships. Fishermen possessed maritime knowledge. Merchants helped maintain supply networks. Together, they reflected the diverse character of Hong Kong society itself.',

        'stoodUp_model_section_13_title' => 'The Women of Hong Kong\'s Resistance',
        'stoodUp_model_section_13_p1' => 'Women played indispensable roles throughout the resistance movement. They served as couriers, organisers, intelligence operatives, caregivers, propagandists, and community mobilisers. Figures such as Fung Chi, Fong Lan, Ling Leung, and Leung Pui-Wan demonstrate the many different forms that courage could take.',
        'stoodUp_model_section_13_p2' => 'Some endured imprisonment without betraying their comrades. Others organised urban operations, cared for resistance fighters, or secretly produced propaganda under blackout conditions. Their stories remind us that resistance cannot be understood solely through armed combat. Many of the most important contributions occurred behind the scenes, through persistence, discretion, and sacrifice.',

        'stoodUp_model_section_14_title' => 'Those Who Fell and Those Who Remembered',
        'stoodUp_model_section_14_p1' => 'Some resistance figures died during the war. Others survived and helped preserve its memory. The Brigade\'s historical records contain the names of commanders, couriers, community organisers, villagers, fighters, medical workers, and countless others whose contributions made resistance possible. Those who survived often participated in writing histories, recording memoirs, and supporting commemorative activities after the war.',
        'stoodUp_model_section_14_p2' => 'The 80th Anniversary Commemorative Publication of the Hong Kong and Kowloon Brigade notes that former Dongjiang Column veterans living in Hong Kong established associations that contributed to the preservation of Brigade history through publications and recollections. Because of these efforts, later generations have been able to learn about a chapter of Hong Kong\'s past that might otherwise have been forgotten.',

        'stoodUp_model_section_15_title' => 'Conclusion: Seeing History Through People',
        'stoodUp_model_section_15_p1' => 'The significance of these individuals lies not simply in remembering their names, but in understanding how history is shaped by human choices. Some chose to lead. Others chose to fight. Some carried intelligence. Some protected secrets. Some opened their homes. Some cared for the wounded. Some endured torture rather than betray their comrades. Together, these choices formed the human foundation of Hong Kong\'s wartime resistance.',
        'stoodUp_model_section_15_p2' => 'Looking back today, we do not see a single type of hero. We see people of different ages, backgrounds, occupations, and experiences. Some carried rifles. Some steered boats. Some delivered messages. Some prepared meals. Some rescued others. Some suffered in silence. It was through their courage, perseverance, and willingness to help one another that the history of occupied Hong Kong became more than a story of hardship and oppression. It also became a story of resilience, solidarity, and the determination to protect one\'s community in a time of war.',

        // tab 2
        'village_title' => 'Village memory',
        'village_subtitle' => 'Villages That Remember',
        'village_intro' => 'The villages of the New Territories played an important role during the War of Resistance against Japanese Aggression. They served as guerrilla bases, sources of food and intelligence, places of refuge, and vital links in transportation and communication networks.',

        'village_section_1_title' => 'Places Where the Memory of War Endures',
        'village_section_1_p1' => 'Many villagers faced intimidation, imprisonment, torture, and even death, yet continued to support resistance activities. Today, the memory of that period survives not only in official histories and memorials, but also in the villages themselves. Across Sai Kung, Sha Tau Kok, Tai Po, Lantau Island, Yuen Long, and Lung Kwu Tan, traces of wartime history remain embedded in mountain paths, bays, churches, ancestral halls, village houses, and coastal landscapes.',
        'village_section_1_p2' => 'These places appear ordinary today, yet during the occupation they witnessed courage, sacrifice, secrecy, and resilience. According to The History of the Hong Kong and Kowloon Brigade, numerous villages—including Wong Mo Ying, Chek Kang, Wu Kau Tang, Ngong Wo, and others—played important roles in supporting resistance operations. Their stories illustrate how local communities became an integral part of Hong Kong\'s wartime experience.',

        'village_section_2_title' => 'Sai Kung: A Landscape of Resistance',
        'village_section_2_p1' => 'Among all regions associated with the Hong Kong and Kowloon Brigade, Sai Kung occupies a particularly important place. Its mountains, villages, bays, and maritime routes connected Kowloon, northeastern New Territories, Mirs Bay, and the wider Dongjiang guerrilla areas in Guangdong. For Japanese forces, this rugged terrain was difficult to control completely. For resistance fighters and their supporters, it offered opportunities for concealment, transportation, communication, and supply operations.',
        'village_section_2_p2' => 'Places such as Wong Mo Ying, Chek Kang, Sham Chung, Shan Liu, Ngong Wo, and Tai Long all became connected, in different ways, to Hong Kong\'s wartime resistance. Some villages housed guerrilla units. Others sheltered fugitives, transported supplies, cared for the wounded, or provided intelligence. Many endured Japanese reprisals as a consequence of their support. The memory of resistance in Sai Kung is therefore not concentrated in a single battlefield. It is dispersed across mountains, shorelines, village lanes, and family homes.',

        // Model
        'village_model_section_1_title' => 'Wong Mo Ying: A Place of Foundation and Suffering',
        'village_model_section_1_p1' => 'Few villages carry greater symbolic significance in the history of the Hong Kong and Kowloon Brigade than Wong Mo Ying. On 3 February 1942, the Brigade was formally established in the village, marking the transition from scattered armed work teams to a unified resistance organisation operating throughout occupied Hong Kong. The village therefore represents both a geographical location and a symbolic birthplace of organised resistance behind enemy lines.',
        'village_model_section_1_p2' => 'Yet Wong Mo Ying is remembered not only for its role in the Brigade\'s founding. According to The History of the Hong Kong and Kowloon Brigade, Japanese forces conducted a sweep through the village on 21 September 1944. Unable to locate guerrilla fighters, they gathered villagers inside the local church and subjected them to severe interrogation and torture in an attempt to obtain information. The story of Wong Mo Ying illustrates an important reality of occupation: villages suspected of supporting resistance often bore the consequences of Japanese retaliation. The silence and endurance of villagers became part of the cost of protecting the resistance.',

        'village_model_section_2_title' => 'Chek Kang: A Village of Intelligence and Support',
        'village_model_section_2_p1' => 'Nestled between mountains and sea, Chek Kang occupied a strategic position that connected multiple land and maritime routes. During the occupation, it served as an important centre for transportation, communications, intelligence, and medical support. The historic residence known as Tin Shui Lau Fong became associated with the British Army Aid Group\'s Y Station, representing one of the most significant examples of intelligence cooperation between the Hong Kong and Kowloon Brigade and Allied forces.',
        'village_model_section_2_p2' => 'Yet Chek Kang\'s wartime memory extends beyond intelligence work. According to The History of the Hong Kong and Kowloon Brigade, Lee Yau-Dai, who served as chairwoman of the village women\'s association, mobilised local women to support resistance activities. Their contributions included organising anti-Japanese performances, gathering firewood, transporting food and supplies, preparing accommodation, cleaning facilities, repairing clothing, caring for the wounded, and carrying intelligence messages. Chek Kang therefore represents more than a resistance base. It demonstrates how an entire community could contribute to the war effort through everyday acts of labour and support.',

        'village_model_section_3_title' => 'Sham Chung: A House Along the Lifeline',
        'village_model_section_3_p1' => 'The Lee Family House at Sham Chung formed an important link in the Brigade\'s transportation network. Historical records indicate that routes passing through Sham Chung connected locations including Yung Shue O, Kei Ling Ha, Shap Sze Heung, Mui Tsz Lam, Chung Mei, Chek Kang, Sai Kung Market, and Pak Tam. Large quantities of supplies passed through the village en route to resistance forces, while intelligence was transmitted through the same network.',
        'village_model_section_3_p2' => 'Buildings such as the Lee Family House possessed a dual identity. Outwardly, they appeared to be ordinary village homes. In reality, they could function as safe houses, communications stations, medical shelters, intelligence centres, or supply depots. The memory of Sham Chung reminds us that resistance depended not only on armed fighters, but also on people willing to transform their homes into places of refuge and support.',

        'village_model_section_4_title' => 'Wu Kau Tang: Hong Kong’s Model Resistance Village',
        'village_model_section_4_p1' => 'Few villages are more closely associated with Hong Kong\'s wartime resistance than Wu Kau Tang. According to The History of the Hong Kong and Kowloon Brigade, it was remembered as "Hong Kong\'s Model Resistance Village." This distinction reflected not the village\'s size, but the sacrifices made by its residents and its role in supporting the resistance movement.',
        'village_model_section_4_p2' => 'On 25 September 1942, Japanese forces carried out a sweep of the village, gathering residents and demanding information about local guerrilla activities. Village leader Lee Sai-Fan refused to reveal any information. He was subjected to water torture, beaten, dragged by military horses, and ultimately died from his injuries. Another village leader, Lee Yuen-Pui, similarly refused to disclose information. He was brutally tortured and suffered permanent injuries. After recovering consciousness, he nevertheless encouraged his daughter and fellow villagers to join the resistance. Their experiences reflect the extraordinary price paid by many rural communities during the occupation.',

        'village_model_section_5_title' => 'The Wu Kau Tang Conference and the Shek Shui Kan Radio Station',
        'village_model_section_5_p1' => 'The historical significance of Wu Kau Tang extends beyond the suffering endured by its residents. In February 1943, senior representatives of the Guangdong Provincial Communist leadership and the Dongjiang military-political leadership convened near Wu Kau Tang in what became known as the Wu Kau Tang Conference. According to the 80th Anniversary Commemorative Publication of the Hong Kong and Kowloon Brigade, this meeting was regarded as an event of major significance in the history of the Communist movement in Guangdong, while the Brigade was responsible for logistics and security.',
        'village_model_section_5_p2' => 'Nearby Shek Shui Kan Village also played a critical role in wartime communications. Between April 1942 and March 1943, the only radio station linking Communist organisations and anti-Japanese guerrilla forces in Guangdong with Yan\'an operated from Shek Shui Kan. The Hong Kong and Kowloon Brigade assisted in selecting and protecting the site. Together, these events transformed the area from an ordinary rural community into an important centre of communication, coordination, and strategic planning.',

        'village_model_section_6_title' => 'Ngong Wo: A Village of Care and Refuge',
        'village_model_section_6_p1' => 'The wartime memory of Ngong Wo Village is closely associated with Ling Leung, affectionately remembered as "the Mother of the Guerrillas." According to the 80th Anniversary Commemorative Publication of the Hong Kong and Kowloon Brigade, she opened her home to the Brigade\'s quartermaster section, encouraged her two sons to participate in resistance work, and helped save the life of resistance worker Leung Suet-Ying during a serious illness in 1943',
        'village_model_section_6_p2' => 'Ngong Wo represents another dimension of resistance. Wars require more than weapons and fighters. They also require places where people can rest, recover, hide, and begin again. The village\'s memory is therefore rooted not in combat, but in care, shelter, and protection.',

        'village_model_section_7_title' => 'Shan Liu and the Great Rescue',
        'village_model_section_7_p1' => 'The village of Shan Liu played an important role in the Great Rescue operation. As evacuees were escorted from Kowloon through Ngau Chi Wan, Kowloon Pass, and onward into Sai Kung, Shan Liu became an important stopping point along the route. Villagers provided food, shelter, and concealment, enabling rescued individuals to continue their journey toward the coast before crossing by sea to Free China.',
        'village_model_section_7_p2' => 'Such assistance rarely produced dramatic scenes, yet it was essential to the success of rescue operations. Every stage of a journey required local knowledge, planning, observation, and support. The memory of Shan Liu reminds us that Hong Kong\'s mountain villages became part of a larger network of escape and survival.',

        'village_model_section_8_title' => 'Lantau Island: Resistance Across an Island Landscape',
        'village_model_section_8_p1' => 'Lantau Island occupies a special place in the history of the Hong Kong and Kowloon Brigade. Its villages, monasteries, mountain trails, and coastal routes were closely connected to the activities of the Lantau Island Squadron, maritime transportation networks, and resistance operations.',
        'village_model_section_8_p2' => 'Lantau\'s distance from the urban centre, combined with its rugged terrain and strategic coastal position, offered opportunities for concealment but also exposed the island to Japanese naval patrols. The island\'s wartime memory includes guerrilla activities, civilian support, religious sanctuary, and maritime sacrifice. The stories of Liu Chun-Xiang and his companions, who lost their lives in the waters near Lung Kwu Chau and Sha Chau, remain closely connected to Lantau\'s resistance history.',

        'village_model_section_9_title' => 'Lung Kwu Tan: Looking Toward the Sea',
        'village_model_section_9_p1' => 'The memory of Lung Kwu Tan is closely linked to the Liu Chun-Xiang Anti-Japanese Heroes Group. In May 1943, Liu Chun-Xiang and his companions sailed from Tung Chung toward Lung Kwu Tan in an attempt to establish new communication routes, but were ambushed by Japanese gunboats near Lung Kwu Chau and Sha Chau and killed in action.',
        'village_model_section_9_p2' => 'According to the commemorative publication of the Liu Chun-Xiang Anti-Japanese Heroes Memorial Monument, Lung Kwu Tan was the location where the group had originally intended to land. It later became the site of the memorial dedicated to their sacrifice. Standing on the shore today, visitors can look across the water toward Lung Kwu Chau and Sha Chau, linking the peaceful landscape of the present with the events of wartime. The monument gives a permanent physical location to a story that originally unfolded at sea.',

        'village_model_section_10_title' => 'Churches, Monasteries, and Ancestral Halls',
        'village_model_section_10_p1' => 'Village memory survives not only in homes but also in religious and communal buildings. The church at Wong Mo Ying, the Catholic community of Chek Kang, Po Lin Monastery, ancestral halls, and village schools all became connected, in different ways, to the wartime experience. Some witnessed interrogations and torture. Others sheltered resistance fighters, cared for the sick, hosted meetings, or served as communication points.',
        'village_model_section_10_p2' => 'These structures are important because they anchor history to identifiable places. When visitors stand before a church, monastery, or ancestral hall today, they are not simply looking at a building. They are standing in a place where people once faced difficult choices, protected others, and endured the pressures of occupation. Local memory allows history to return from the written page to the physical landscape.',

        'village_model_section_11_title' => 'The Risks Faced by Villagers',
        'village_model_section_11_p1' => 'Supporting the resistance often carried severe consequences. Villages suspected of sheltering guerrillas, supplying food, or transmitting intelligence could face raids, arrests, torture, and executions. The experiences of Wu Kau Tang and Wong Mo Ying illustrate the reality that villagers paid a very real human price for their support.',
        'village_model_section_11_p2' => 'Village memory therefore contains not only stories of courage but also stories of fear, suffering, and loss. Many villagers never formally joined the resistance. Their contribution lay in their silence, their willingness to provide shelter, and their determination not to betray those they protected. Their sacrifices form an essential part of Hong Kong\'s wartime history.',

        'village_model_section_12_title' => 'From Oral History to Commemoration',
        'village_model_section_12_p1' => 'Many of these village stories survived through oral testimony, local investigations, family recollections, and commemorative activities. According to The History of the Hong Kong and Kowloon Brigade, the reconstruction of village history draws upon interviews with villagers from places such as Chek Kang, the Chinese University of Hong Kong\'s Sai Kung Oral History Project, and archival materials relating to New Territories communities and maritime populations.',
        'village_model_section_12_p2' => 'This is particularly important because many ordinary villagers left behind few written records. Their experiences have often been preserved through memory rather than official documentation. By recording and preserving these stories, later generations ensure that the contributions of those who supported the resistance are not forgotten.',

        'village_model_section_13_title' => 'Conclusion: Places Remember the War',
        'village_model_section_13_p1' => 'The memory of Hong Kong\'s resistance becomes more tangible when viewed through the villages that experienced it. Wong Mo Ying remembers the founding of the Hong Kong and Kowloon Brigade and the suffering of its villagers; Chek Kang remembers intelligence work, transportation routes, and the contributions of women; Sham Chung remembers the houses and paths that sustained communications. Wu Kau Tang remembers sacrifice, leadership, and strategic coordination; Ngong Wo remembers care and protection; Lantau Island and Lung Kwu Tan remember the dangers of maritime resistance and the sacrifices made at sea.',
        'village_model_section_13_p2' => 'Together, these villages remind us that the War of Resistance was not fought only on distant battlefields. It was also fought along village paths, mountain trails, church grounds, ancestral halls, piers, and shorelines across Hong Kong. These places remember the choices people made, the risks they accepted, and the hope they preserved during one of the darkest periods in the city\'s history.',

        // tab 3
        'acts_title' => 'Civilian mutual aid',
        'acts_subtitle' => 'Acts of Courage and Care',
        'acts_intro' => 'The history of Hong Kong\'s resistance during the Second World War is not only a story of guerrilla fighters and military operations. It is also a story of ordinary people helping one another through some of the darkest years in the city\'s history.',

        'acts_section_1_title' => 'Supporting One Another in a Time of War',
        'acts_section_1_p1' => 'During the Japanese occupation, food was scarce, transportation was disrupted, villages were subjected to military sweeps, and arrests occurred frequently. Many residents struggled simply to survive. Yet despite their own hardships, countless individuals chose to support resistance fighters, care for the sick and wounded, protect those being pursued, or share what little food and shelter they possessed. These acts of mutual assistance became one of the foundations upon which the Hong Kong and Kowloon Brigade was able to survive.',
        'acts_section_1_p2' => 'In the foreword to The History of the Hong Kong and Kowloon Independent Brigade, Tsang Sang observed that the Brigade was "an army of the people of Hong Kong and Kowloon," and that every achievement it attained depended upon the enthusiastic support of local residents. The history of Hong Kong\'s resistance was therefore not created by a small number of armed fighters acting alone. It was sustained by villagers, fishermen, merchants, women, young people, religious figures, couriers, and countless others who shared the burden of resistance.',

        'acts_section_2_title' => 'A Bowl of Rice, A Place to Sleep, A Safe Path Forward',
        'acts_section_2_p1' => 'Acts of assistance were not always dramatic. Sometimes they took the form of a bowl of rice, a spare bed, a temporary refuge, guidance along a mountain trail, or a timely warning delivered at the right moment. For guerrilla fighters, intelligence agents, couriers, and rescued individuals operating behind enemy lines, these seemingly small acts often meant the difference between life and death.',
        'acts_section_2_p2' => 'Under Japanese occupation, any form of assistance to resistance forces could carry serious consequences. Providing food might be interpreted as aiding guerrillas. Offering directions could be treated as collaboration with resistance fighters. Sheltering a wanted individual could place an entire family at risk. Yet many ordinary people chose to help. Their actions were not undertaken from a position of abundance. Most lived under the same shortages of food, medicine, and security as everyone else. What makes these stories remarkable is that people continued to share even when they themselves had very little.',

        // Model
        'acts_model_section_1_title' => 'Villagers: The Foundation of Resistance',
        'acts_model_section_1_p1' => 'The villages of the New Territories formed one of the most important foundations of civilian support. Villagers understood the local terrain. They knew which mountain paths avoided Japanese patrols, which caves could conceal fugitives, which families could be trusted, and which bays provided safe access to transportation routes. For the Hong Kong and Kowloon Brigade, this support was not simply a logistical convenience—it was essential to survival.',
        'acts_model_section_1_p2' => 'Village assistance often took practical forms. Some prepared food and water. Others transported firewood and supplies. Some repaired clothing or cared for wounded fighters. Others passed on information whenever Japanese troops appeared nearby. As a result, ordinary villages became part of a wider resistance network. Many villagers never carried weapons, yet they accepted risks comparable to those faced by resistance fighters.',

        'acts_model_section_2_title' => 'The Women of Chek Kang: Collective Support',
        'acts_model_section_2_p1' => 'The experience of Chek Kang Village demonstrates how mutual aid could evolve from individual acts into collective community support. According to The History of the Hong Kong and Kowloon Brigade, Lee Yau-Dai, chairwoman of the village women’s association, organised local women to support the Hong Kong and Kowloon Brigade in numerous ways. They performed anti-Japanese songs and dramas, gathered firewood, transported food and supplies to mountain storage sites, arranged accommodation for fighters, cleaned facilities, repaired clothing, cared for the sick and wounded, and carried intelligence messages.',
        'acts_model_section_2_p2' => 'These task may appear ordinary, yet they sustained the daily functioning of the resistance. Fighters needed food, clothing, shelter, information, and medical care. Communities also needed people who could explain the purpose of the resistance and maintain morale. The women of Chek Kang remind us that women were not passive observers of the war. They were active participants whose contributions were indispensable.',

        'acts_model_section_3_title' => 'Ling Leung: A Mother to the Guerrillas',
        'acts_model_section_3_p1' => 'Among the most beloved figures associated with civilian support was Ling Leung of Ngong Wo Village. Remembered as "the Mother of the Guerrillas," she cared tirelessly for resistance fighters and became a symbol of compassion during wartime. According to the 80th Anniversary Commemorative Publication of the Hong Kong and Kowloon Brigade, Ling lent her home to the Brigade\'s quartermaster section, encouraged her two sons to join the resistance, and in early 1943 helped save the life of resistance worker Leung Suet-Ying through traditional remedies.',
        'acts_model_section_3_p2' => 'Ling\'s story represents one of the most powerful forms of civilian support. She was neither a commander nor a combatant. Her contribution came through shelter, care, healing, and encouragement. For young resistance fighters moving through dangerous territory, a villager willing to treat them as family could provide strength that no weapon could replace.',

        'acts_model_section_4_title' => 'Merchants and Fish Markets: Business as Cover',
        'acts_model_section_4_p1' => 'Civilian assistance also emerged through commercial networks. During the occupation, shops, fish markets, rice merchants, and general stores often served purposes beyond ordinary commerce. They could become places for gathering supplies, exchanging information, or providing discreet assistance to resistance activities. Merchants possessed valuable knowledge of local markets, transportation routes, and supply chains. They were often better positioned than ordinary residents to obtain food, medicine, and information.',
        'acts_model_section_4_p2' => 'Such work required considerable caution. Business owners had to satisfy inspections by Japanese authorities while simultaneously ensuring that their true activities remained hidden. A transferred package, a coded message, or a temporary lodging arrangement could have implications for an entire underground network. In this context, mutual aid became not only an act of generosity but also an exercise in skill, judgement, and courage.',

        'acts_model_section_5_title' => 'Couriers: Linking People and Information',
        'acts_model_section_5_p1' => 'Few roles were more important—or more dangerous—than that of the courier. Documents, intelligence reports, medicine, verbal messages, travel arrangements, and personnel movements all depended upon couriers travelling between villages, urban districts, mountain routes, and coastal locations. The 80th Anniversary Commemorative Publication of the Hong Kong and Kowloon Brigade records the names of fallen couriers including Fung Chi, Cheung Wing-Yin, Cheung Kam-Fuk, Tsang Wing-Sang, and Lau Yeung-Sing, highlighting both the importance and dangers of courier work.',
        'acts_model_section_5_p2' => 'Couriers rarely appeared in dramatic battles. Yet their responsibilities often determined whether operations succeeded or failed. They memorised routes, identified contacts, avoided checkpoints, and carried sensitive information under constant threat of arrest. Without couriers, the resistance could not have connected villages to cities, mountains to harbours, or isolated groups to one another.',

        'acts_model_section_6_title' => 'Fishermen and Boatmen: The Sea as a Lifeline',
        'acts_model_section_6_p1' => 'Hong Kong\'s resistance depended heavily upon the sea. Fishermen and boatmen possessed intimate knowledge of channels, tides, winds, and islands. Their expertise allowed resistance fighters to move people and supplies through waters patrolled by Japanese gunboats and military vessels. This support carried enormous risks.',
        'acts_model_section_6_p2' => 'The story of Liu Chun-Xiang and the Anti-Japanese Heroes Group illustrates the sacrifices involved. In May 1943, Liu and his companions departed from Tung Chung by sailing vessel. Near Lung Kwu Chau and Sha Chau, they were ambushed by Japanese gunboats. Seven resistance fighters and the boatman Leung Hak together with five members of his family were killed. The tragedy reminds us that maritime support was not passive assistance. Fishermen and boatmen often shared the same dangers and sacrifices as the resistance fighters they helped.',

        'acts_model_section_7_title' => 'Religious Compassion in Wartime',
        'acts_model_section_7_p1' => 'Religious institutions sometimes became places of refuge. One of the most notable examples involved Venerable Fat Ho, abbot of Po Lin Monastery on Lantau Island. During a Japanese sweep of the island in 1944, Brigade Deputy Commander Lo Fung was recovering from illness at the monastery. Fat Ho disguised him as a monk and concealed him among hundreds of monks, nuns, and worshippers.',
        'acts_model_section_7_p2' => 'When Japanese soldiers later threatened and beat the abbot, he refused to reveal Lo Fung\'s whereabouts. His actions demonstrate that mutual aid could emerge not only from family ties or village loyalties, but also from deeply held moral and religious convictions.',

        'acts_model_section_8_title' => 'The Power of Silence',
        'acts_model_section_8_p1' => 'Mutual assistance often depended upon silence. When Japanese troops entered villages and demanded information about resistance activities, one of the most important forms of support was the refusal to speak. Village leaders such as Lee Sai-Fan and Lee Yuen-Pui of Wu Kau Tang endured severe torture rather than reveal the whereabouts of guerrilla fighters.',
        'acts_model_section_8_p2' => 'The importance of such silence is difficult to quantify. Communication stations survived because people remained silent. Resistance fighters escaped because people remained silent. Entire villages preserved their secrets because people remained silent. Sometimes the most courageous action was not what someone did, but what they refused to say.',

        'acts_model_section_9_title' => 'Trust as Resistance',
        'acts_model_section_9_p1' => 'Mutual assistance depended fundamentally upon trust. Villagers trusted resistance fighters. Couriers trusted their contacts. Merchants trusted those who received supplies. Resistance fighters trusted the communities that sheltered them. Occupation systems often seek to undermine such trust through surveillance, informants, intimidation, and torture.',
        'acts_model_section_9_p2' => 'The Japanese authorities employed all of these methods. For this reason, mutual aid became a form of resistance in itself. Whenever people chose to trust, protect, and assist one another despite the risks, they challenged the isolation and fear that occupation sought to create. Trust became one of the most powerful resources available to Hong Kong\'s resistance network.',

        'acts_model_section_10_title' => 'Women, Elders, and Children',
        'acts_model_section_10_p1' => 'Mutual aid was not carried solely by young men. Women delivered messages, cared for the wounded, repaired clothing, prepared food, and organised community support. Elderly residents watched roads, monitored village activity, and helped conceal younger participants. Children sometimes carried simple signals, observed unfamiliar visitors, or relayed information between households.',
        'acts_model_section_10_p2' => 'Many of these activities were embedded within ordinary life. A woman carrying a basket through a village, an elderly resident sitting outside a house, or a child visiting a neighbour might appear entirely unremarkable. Yet beneath the surface, such actions could form part of a wider protective network. The strength of mutual aid lay precisely in its ability to operate within everyday life.',

        'acts_model_section_11_title' => 'Sharing During Hunger',
        'acts_model_section_11_p1' => 'Perhaps the most powerful examples of mutual assistance emerged during times of scarcity. Historical accounts from Chek Kang describe severe food shortages during the occupation. Some residents reportedly died from hunger. Yet even under these conditions, villagers continued to contribute rice and food to support resistance fighters.',
        'acts_model_section_11_p2' => 'Such acts carry particular significance because they were not donations made from abundance. They were sacrifices made when those giving help also faced hunger themselves. The sharing of food reflected a belief that the survival of the community and the survival of the resistance were closely connected.',

        'acts_model_section_12_title' => 'Preserving the Memory of Mutual Aid',
        'acts_model_section_12_p1' => 'Many of these acts were never formally recorded. A meal shared, a warning delivered, a night\'s shelter provided, or a secret protected rarely appeared in official documents. Much of this history survives through oral testimony, local memory, commemorative publications, and later historical research. For this reason, preserving the stories of mutual aid is not simply about adding detail to military history.',
        'acts_model_section_12_p2' => 'It is about ensuring that those who supported the resistance—often without recognition or public reward—retain a place within Hong Kong\'s historical memory. As the records of the Hong Kong and Kowloon Brigade demonstrate, resistance was sustained not only by commanders and fighters, but also by villagers, women, merchants, couriers, religious figures, fishermen, and countless others whose names may never appear in conventional military histories.',
        
        'acts_model_section_13_title' => 'Conclusion: The Most Ordinary, and the Most Precious, Form of Resistance',
        'acts_model_section_13_p1' => 'Acts of mutual aid gave Hong Kong\'s wartime resistance its deepest human dimension. Some people carried weapons. Others steered boats. Some printed leaflets. Others delivered messages. Some guarded secrets. Others opened their homes. Some shared food despite hunger. Others protected complete strangers despite the risks. These actions were not always dramatic. Yet they enabled the Hong Kong and Kowloon Brigade and the wider resistance movement to survive.',
        'acts_model_section_13_p2' => 'Under occupation, mutual assistance became a form of resistance in its own right. It resisted fear. It resisted isolation. It resisted the mistrust that occupation authorities sought to create. Because of these ordinary yet extraordinary acts, Hong Kong\'s wartime history is not remembered solely through battles and sacrifice. It is also remembered through compassion, trust, generosity, and the determination of people to protect one another in a time of war.',

         // tab 4
        'rescue_title' => 'rescue story',
        'rescue_subtitle' => 'Stories of Rescue',
        'rescue_intro' => 'Many of the most remarkable stories from occupied Hong Kong do not begin with battles. They begin with rescue. After Hong Kong fell in December 1941, countless individuals found themselves trapped in a city under military occupation. Some were writers, journalists, and intellectuals. Others were prisoners of war, Allied servicemen, or civilians whose identities, professions, or political views placed them at risk.',

        'rescue_section_1_title' => 'Opening Paths to Survival',
        'rescue_section_1_p1' => 'Under conditions of curfews, roadblocks, military patrols, and intensive searches, guiding a person safely out of Hong Kong often proved more difficult—and sometimes more dangerous—than fighting a battle. These rescue operations reveal another side of the Hong Kong and Kowloon Brigade and its predecessor armed work teams. They were not only resistance fighters. They were also guardians of escape routes and protectors of human lives.',
        'rescue_section_1_p2' => 'From the Great Rescue of anti-Japanese intellectuals to the evacuation of Allied personnel, from assisting escaped prisoners of war to protecting downed American airmen, the Brigade connected mountain trails, coastal bays, village houses, communication stations, and fishing boats into a network of survival. Through these efforts, pathways remained open even when the city appeared completely sealed off.',

        'rescue_section_2_title' => 'The Great Rescue: Saving Lives After the Fall of Hong Kong',
        'rescue_section_2_p1' => 'One of the most significant rescue operations in modern Chinese wartime history began immediately after Hong Kong\'s surrender on 25 December 1941. Following the occupation, large numbers of anti-Japanese intellectuals, journalists, cultural figures, and democratic activists found themselves in grave danger. Japanese authorities sought to identify, monitor, arrest, or coerce prominent individuals into cooperation. Many of those trapped in Hong Kong came from other provinces of China. They were unfamiliar with local geography, local dialects, and safe places of refuge. Without assistance, many faced the prospect of arrest, execution, or forced collaboration.',
        'rescue_section_2_p2' => 'In response, underground Communist Party organisations, the Guangdong People\'s Anti-Japanese Guerrilla Forces, and the armed work teams that later formed the Hong Kong and Kowloon Brigade launched what became known as the Great Rescue. Beginning on the day of Hong Kong\'s surrender and concluding on 22 November 1942, when journalist Zou Taofen reached an anti-Japanese base area in northern Jiangsu, the operation lasted approximately eleven months. During that period, more than 300 prominent anti-Japanese cultural and democratic figures and approximately 800 individuals in total were successfully evacuated from occupied Hong Kong.',

        //Model
        'rescue_model_section_1_title' => 'Crossing Enemy Territory',
        'rescue_model_section_1_p1' => 'The Great Rescue was not a conventional evacuation. Those being rescued had to leave Hong Kong Island or urban Kowloon, pass through Japanese-controlled territory, avoid checkpoints, military patrols, informants, and bandits, and then travel through mountain routes or coastal waterways into guerrilla-controlled areas. Every stage required careful coordination. Guides, couriers, safe houses, transportation stations, escorts, lookouts, and local supporters all played essential roles.',
        'rescue_model_section_1_p2' => 'The operation succeeded because of a highly organised underground network. The eastern route passed through Ngau Chi Wan, Kowloon Pass, and Sai Kung, before crossing from Kei Ling Ha or Sham Chung Bay into the waters of Mirs Bay. The western route travelled through Tsuen Wan, Tai Mo Shan, Yuen Long, and Lok Ma Chau, before crossing the Shenzhen River to the guerrilla base at Pak Shek Lung. These routes transformed ordinary villages, bays, and mountain trails into lifelines linking occupied Hong Kong with the wider resistance movement.',
        
        'rescue_model_section_2_title' => 'Liao Chengzhi, Lian Guan, and Qiao Guanhua',
        'rescue_model_section_2_p1' => 'Among the earliest prominent figures to escape through the eastern route were Liao Chengzhi, Lian Guan, and Qiao Guanhua. According to historical records, on 1 January 1942, these individuals departed Hong Kong as part of the effort to establish and test evacuation routes for later rescue operations. Their journey took them through Ngau Chi Wan, Kowloon Pass, and the mountain paths of Sai Kung before they boarded a vessel at Kei Ling Ha Bay and crossed to Sha Tau Kok.',
        'rescue_model_section_2_p2' => 'The route was dangerous. Japanese patrols, military checkpoints, and criminal groups all posed threats. Escort personnel had to coordinate disguises, meeting points, security arrangements, and boat departures with great precision. For those attempting to escape, Kei Ling Ha was more than a geographical location—it represented a gateway between occupation and freedom.',
    
        'rescue_model_section_3_title' => 'Mao Dun, Zou Taofen, and the Western Route',
        'rescue_model_section_3_p1' => 'Another important escape route passed through the western New Territories. Prominent cultural figures such as Mao Dun and Zou Taofen travelled through Tsuen Wan, Tai Mo Shan, Yuen Long, and Lok Ma Chau before reaching guerrilla-controlled territory. One important stop along this route was Shek Lo (適廬) in Yeung Ka Tsuen, Shap Pat Heung, Yuen Long.',
        'rescue_model_section_3_p2' => 'Historical records identify the residence as both a transit station for the Great Rescue and an activity centre for the Yuen Long Squadron of the Hong Kong and Kowloon Brigade. Its owner, Yeung Cheuk-Nam, strongly supported resistance activities. The western route demanded considerable endurance. Many of those being rescued were intellectuals and writers unaccustomed to long journeys through mountain terrain. Guides and escorts were required to provide accommodation, food, navigation, and protection. Later artistic works, including the woodcut The Waning Moon Before Dawn (曉風殘月) by Cai Dizhi and Xu Qinsong, depicted scenes inspired by these journeys. The image portrays Mao Dun carrying a bundle at the front of the group, with Zou Taofen following behind, offering a visual reminder of the hardships endured by those escaping occupied Hong Kong.',

        'rescue_model_section_4_title' => 'Cheung Chau and the Maritime Escape Routes',
        'rescue_model_section_4_p1' => 'Not all rescues took place over land. For some individuals—particularly the elderly, the infirm, or those whose identities made concealment difficult—maritime routes offered a more practical alternative. Cheung Chau became an important transit point along one of the western maritime escape routes. Some evacuees travelled from Hong Kong Island to Cheung Chau, then onward to Macau, before continuing to the Chinese mainland.',
        'rescue_model_section_4_p2' => 'These journeys depended upon fishermen, boatmen, safe houses, weather conditions, tides, and careful secrecy. A single fishing boat could carry the hopes of an entire group. The maritime routes demonstrate that rescue operations unfolded not only on mountain trails but also across Hong Kong\'s surrounding waters.',

        'rescue_model_section_5_title' => '"The Greatest Rescue Operation"',
        'rescue_model_section_5_p1' => 'Perhaps the most extraordinary aspect of the Great Rescue was its success. Despite shortages of money, language barriers, difficult terrain, changing enemy conditions, and constant danger, underground organisers and armed work teams successfully escorted hundreds of people to safety without a single casualty among the rescued groups. Writer Mao Dun later described the operation as: "The greatest rescue effort since the beginning of the War of Resistance."',
        'rescue_model_section_5_p2' => 'His assessment reflected more than the scale of the operation. Many of those rescued later continued to make important contributions to journalism, literature, education, politics, and anti-Japanese mobilisation. The Great Rescue therefore preserved not only lives but also a significant portion of China\'s wartime intellectual and cultural leadership.',
        
        'rescue_model_section_6_title' => 'Lieutenant Colonel Lindsay Ride: From Escape to Cooperation',
        'rescue_model_section_6_p1' => 'The Hong Kong and Kowloon Brigade also played a crucial role in rescuing Allied military personnel. In January 1942, Lieutenant Colonel Lindsay Ride and three companions escaped from an internment camp and were rescued by one of the armed work teams that later became part of the Hong Kong and Kowloon Brigade. The significance of Ride\'s rescue extended far beyond his personal survival.',
        'rescue_model_section_6_p2' => 'After reaching safety, he helped establish the British Army Aid Group (BAAG), an organisation dedicated to intelligence gathering and the rescue of prisoners of war. His escape also laid the foundation for cooperation between British intelligence networks and the Guangdong anti-Japanese guerrilla forces. What began as a rescue operation evolved into a lasting wartime partnership.',

        'rescue_model_section_7_title' => 'From Rescue to Intelligence Cooperation',
        'rescue_model_section_7_p1' => 'The rescue of Ride ultimately helped create one of the most important Allied intelligence networks operating in occupied South China. Between 1942 and 1943, Wong Cho-Mei, working with the Hong Kong and Kowloon Brigade\'s International Affairs Group, established a grocery store on Portland Street, Kowloon that functioned as a clandestine communication station supporting cooperation with the British Army Aid Group.',
        'rescue_model_section_7_p2' => 'Following the war, Wong was awarded the Member of the Order of the British Empire (MBE) in recognition of his contributions to Allied operations. His story demonstrates how rescue missions could create new intelligence networks, new partnerships, and new channels of international cooperation.',

        'rescue_model_section_8_title' => 'Lieutenant Klier: Waiting in a Cave',
        'rescue_model_section_8_p1' => 'One of the most dramatic rescue operations involved American pilot Lieutenant Robert E. Klier. In February 1944, Klier parachuted into Hong Kong following an Allied air operation. Japanese authorities immediately launched a large-scale search. According to the 80th Anniversary Commemorative Publication of the Hong Kong and Kowloon Brigade, the Brigade rescued the downed pilot and facilitated subsequent cooperation between American forces and the Dongjiang Column.',
        'rescue_model_section_8_p2' => 'Klier\'s foreign appearance made concealment particularly difficult. The Brigade first moved him away from immediate danger, then arranged hiding places, interpreters, escorts, and transportation. Historical accounts record that Lau Hei-Zai and his companions escorted Klier and concealed him in a cave near Shek Lung Tsai Village, where he remained hidden for approximately two weeks. The waiting was perhaps the most dangerous stage of all. Any mistake could have exposed both the pilot and those protecting him.',
       
        'rescue_model_section_9_title' => 'A Strategy of Diversion',
        'rescue_model_section_9_p1' => 'Klier\'s rescue succeeded not only because of concealment but also because of diversion. To reduce pressure on the search effort, the Hong Kong and Kowloon Brigade launched a series of operations elsewhere, including actions against collaborators, attacks on Kai Tak Airport, and the distribution of anti-Japanese leaflets in urban districts. This strategy resembles the classical military concept of "Besieging Wei to Rescue Zhao" (圍魏救趙)—relieving pressure by forcing an opponent to divert resources elsewhere.',
        'rescue_model_section_9_p2' => 'The rescue therefore depended upon the integration of guerrilla warfare, intelligence gathering, transportation networks, and psychological pressure. Saving one life required the coordinated efforts of an entire organisation.',
        
        'rescue_model_section_10_title' => 'From Hong Kong to the Dongjiang Headquarters',
        'rescue_model_section_10_p1' => 'Klier was eventually escorted safely to the headquarters of the Dongjiang Column, where he met commander Tsang Sang. Photographs preserved in the 80th Anniversary Commemorative Publication of the Hong Kong and Kowloon Brigade document Tsang Sang bidding farewell to Klier at the Dongjiang headquarters in To Yeung Village. The route that carried Klier to safety linked caves, mountain paths, guerrilla bases, coastal routes, and inland resistance areas into a single rescue corridor.',
        'rescue_model_section_10_p2' => 'His rescue also strengthened cooperation between American forces and the Dongjiang Column. Years later, Klier\'s sons visited former veterans of the Hong Kong and Kowloon Brigade to express gratitude for the actions that had saved their father\'s life. The story thus became part of both family memory and international historical memory.',
        
        'rescue_model_section_11_title' => 'Rescuing the International Community',
        'rescue_model_section_11_p1' => 'The Brigade\'s rescue activities extended far beyond a handful of famous cases. According to historical records, 89 foreign nationals were rescued during the Japanese occupation of Hong Kong. These included individuals from Britain, India, Denmark, Norway, Russia, the Philippines, and the United States. Apart from five American airmen rescued by other Dongjiang Column units in Mirs Bay, those detained in Hong Kong Island and Kowloon were rescued by the Hong Kong and Kowloon Brigade and escorted to guerrilla-controlled territory before continuing to inland China.',
        'rescue_model_section_11_p2' => 'These figures highlight the international character of the Brigade\'s rescue work. Hong Kong was a global city before the war, and its rescue operations reflected that reality. The Brigade\'s efforts connected occupied Hong Kong not only to China\'s War of Resistance but also to the wider Allied struggle against fascism.',
        
        'rescue_model_section_12_title' => 'The Ordinary People Behind Extraordinary Rescues',
        'rescue_model_section_12_p1' => 'Every successful rescue depended upon a large number of ordinary people. Some provided shelter, some guided travellers through mountain paths. Some prepared boats, while some supplied food. Some carried messages, and some watched for enemy movements. These individuals included villagers, fishermen, couriers, merchants, women, and underground operatives.',
        'rescue_model_section_12_p2' => 'Without their assistance, even the best-organised resistance force could not have conducted long-distance rescue operations involving multiple languages, regions, and identities. Rescue operations depended above all upon reliability. A reliable householder would not betray a guest; a reliable boatman would not abandon a mission; a reliable courier would arrive at the correct location; a reliable contact would appear at the agreed time. The success of rescue operations rested upon this chain of trust.',    
    
        'rescue_model_section_13_title' => 'The Risks and Costs of Rescue',
        'rescue_model_section_13_p1' => 'Rescue work was never safe. Sheltering a wanted individual could endanger an entire household. Escorting intellectuals through mountain routes risked encounters with Japanese troops or bandits. Assisting Allied personnel often increased the risk of detection because of language differences and physical appearance. Operating a clandestine communication station could expose an entire family if discovered.',
        'rescue_model_section_13_p2' => 'For this reason, rescue stories should not be judged solely by their successful outcomes. Behind every successful escape were people who endured fear, secrecy, uncertainty, arrest, torture, or loss. Many of their names have never been recorded. Yet their sacrifices formed the foundation of every rescue that succeeded.',

        
        'rescue_model_section_14_title' => 'The Meaning of Rescue',
        'rescue_model_section_14_p1' => 'The rescue operations carried out by the Hong Kong and Kowloon Brigade reveal another form of courage within the War of Resistance. This courage was not only expressed through armed combat, but also through the patient, careful, and dangerous work of bringing people out of enemy-controlled territory one by one. Rescue work required far more than weapons. It depended on memory, judgement, language skills, knowledge of terrain, reliable contacts, safe houses, transportation routes, and a deep sense of responsibility for the lives of others.',
        'rescue_model_section_14_p2' => 'The Great Rescue preserved an important part of China\'s wartime cultural and intellectual community. The rescue of Lieutenant Colonel Lindsay Ride helped lead to cooperation between the guerrillas and the British Army Aid Group. The rescue of Lieutenant Robert E. Klier strengthened cooperation between American forces and the Dongjiang Column. The rescue of 89 foreign nationals connected Hong Kong\'s resistance directly to the wider international anti-fascist war. These operations show that the Brigade\'s rescue work was not secondary to its military role. It was one of its most important contributions to Hong Kong\'s wartime history and to the broader Allied struggle.',
 
        'rescue_model_section_15_title' => 'Conclusion: Lifelines Through the Darkness',
        'rescue_model_section_15_p1' => 'The rescue stories of the Hong Kong and Kowloon Brigade reveal another form of courage during wartime. Rather than defeating the enemy in battle, these operations focused on protecting life. The Great Rescue preserved some of the most important intellectual and cultural figures of China\'s War of Resistance. The rescue of Lindsay Ride helped establish cooperation with the British Army Aid Group. The rescue of Robert Klier strengthened cooperation between American forces and the Dongjiang Column.',
        'rescue_model_section_15_p2' => 'The rescue of 89 foreign nationals connected Hong Kong\'s resistance directly to the wider international struggle against fascism. Together, these stories remind us that occupied Hong Kong was never completely isolated. Even when roads, ports, checkpoints, and cities were under Japanese control, people continued to create pathways through mountains, villages, bays, and hidden communication networks. Each successful rescue represented the efforts of countless individuals working together in secrecy and danger. Their achievements demonstrate that even in the darkest circumstances, human courage, cooperation, and compassion could keep hope alive—and create a path toward freedom.',
        
     ],
];
