<?php

return [
     'people-and-stories' => [
        'title' => 'Anti-Japanese War Figures',
        'subtitle' => 'Those Who Stood Up',
        'intro' => 'The history of Hong Kong\'s resistance during the Second World War is not only a story of battles, organisations, and operations. It is also a story of individuals. Some were guerrilla commanders. Others served in pistol squads, intelligence networks, rescue operations, transportation routes, or support services. Many began as ordinary villagers, students, workers, merchants, fishermen, or religious figures before making decisions that would change the course of their lives.',

        // Tabs
        'tab_1' => 'Those Who Stood Up',
        'tab_2' => 'Villages That Remember',
        'tab_3' => 'Acts of Courage and Care',
        'tab_4' => 'Stories of Rescue',

        // tab 1
        'stoodUp_section_1_title' => 'The People Behind the Resistance',
        'stoodUp_section_1_p1' => 'This section does not attempt to provide a complete biography of every individual associated with Hong Kong\'s wartime resistance. Rather, it introduces some of the people whose experiences reveal the diversity of those who participated in the struggle. According to historical records of the Hong Kong and Kowloon Brigade, the vast majority of Brigade members were Hong Kong residents, including indigenous villagers and young students. They risked their lives to participate in anti-Japanese activities and reflected a broad cross-section of Hong Kong society. Their stories transform resistance from an abstract historical concept into a history of real people—individuals with names, identities, choices, and sacrifices.',
        

        'stoodUp_section_2_title' => 'Choi Kwok-Leung: An Early Leader of the Hong Kong and Kowloon Brigade',
        'stoodUp_section_2_p1' => 'Choi Kwok-Leung was one of the key figures in the early development of the Hong Kong and Kowloon Brigade. When the Brigade was formally established at Wong Mo Ying Village in Sai Kung on 3 February 1942, Choi served as Brigade Commander, working alongside Political Commissar Chan Tat-Ming and others to organise resistance behind enemy lines.',
        'stoodUp_section_2_p2' => 'The challenges facing Choi and the Brigade\'s leadership were exceptional. They were not building an organisation in a secure rear area. They were attempting to create a resistance force within occupied territory, under conditions of food shortages, disrupted communications, Japanese surveillance, and constant military pressure. The Brigade needed to fight, relocate, rescue, communicate, and protect local communities while avoiding actions that might expose civilians to reprisals. Leadership in such circumstances required not only military judgement, but also a deep understanding of Hong Kong\'s geography, communities, and wartime realities.',

        // Model
        'stoodUp_model_section_1_title' => 'Chan Tat-Ming: From Student Activist to Resistance Leader',
        'stoodUp_model_section_1_p1' => 'Chan Tat-Ming served as Political Commissar when the Hong Kong and Kowloon Brigade was established. Before the war, he had been active in Hong Kong\'s student movement. His transition from student activism to resistance leadership illustrates how the war altered the lives of many young people in Hong Kong.',
        'stoodUp_model_section_1_p2' => 'Chan\'s responsibilities extended beyond military matters. He helped oversee organisation, political education, public mobilisation, propaganda, community relations, and the development of the Brigade itself. The survival of the Brigade depended not only on weapons, but also on discipline, trust, and support from local communities. Through the efforts of leaders such as Chan, the Brigade evolved from a collection of scattered guerrilla groups into a coordinated resistance organisation with a clear structure and social foundation.',

        'stoodUp_model_section_2_title' => 'Wong Koon-Fong: A Fighter Between Mountain and Sea',
        'stoodUp_model_section_2_p1' => 'Wong Koon-Fong was one of the Brigade\'s most active operational figures. He participated in resistance activities across Sai Kung, Sha Tin, transportation routes linking Kowloon and the New Territories, rescue operations, and numerous guerrilla actions. Brigade records identify him as one of the organisation\'s important wartime figures.',
        'stoodUp_model_section_2_p2' => 'His story reflects the realities faced by combat personnel in occupied Hong Kong. Because the territory was small and heavily garrisoned, resistance fighters could not rely on conventional warfare. Success depended on mobility, disguise, reconnaissance, surprise attacks, and rapid withdrawal. Individuals such as Wong formed the operational backbone that allowed guerrilla warfare to continue despite overwhelming odds.',

        'stoodUp_model_section_3_title' => 'Lau Hei-Zai: Between Legend and Reality',
        'stoodUp_model_section_3_p1' => 'Among all resistance figures associated with the Hong Kong and Kowloon Brigade, Lau Hei-Zai remains one of the most widely remembered. He participated in numerous operations in Sha Tin, Kowloon, Cha Kwo Ling, Kai Tak Airport, and other locations. His courage and ingenuity contributed to his reputation as one of the legendary figures of Hong Kong\'s wartime resistance.',
        'stoodUp_model_section_3_p2' => 'Yet his story should not be viewed solely through the lens of legend. Behind the popular image lay the dangerous realities of pistol-squad operations: identifying collaborators, protecting transportation routes, carrying out raids, supporting rescue missions, and withdrawing before enemy reinforcements arrived. These missions involved enormous risk. Failure could lead not only to the death of the participants but also to the destruction of entire resistance networks. Lau\'s enduring place in public memory reflects the courage, resourcefulness, and constant danger faced by resistance fighters operating behind enemy lines.',

        'stoodUp_model_section_4_title' => 'Fong Lan and the "Guerrillas Without Guns"',
        'stoodUp_model_section_4_p1' => 'Fong Lan was an important figure within the Brigade\'s Urban Squadron. Unlike rural guerrilla units, the Urban Squadron relied less on direct combat and more on intelligence gathering, communications, propaganda, sabotage, and clandestine organisation. For this reason, it became known as a "guerrilla force without guns."',
        'stoodUp_model_section_4_p2' => 'Members of the Urban Squadron operated in the heart of occupied Hong Kong and Kowloon. They faced Japanese military police, collaborationist police, informants, and extensive urban surveillance. Their existence reminds us that resistance was not confined to mountain trails and remote villages. It also took place in city streets, shops, banks, printing locations, and transportation networks.',

        'stoodUp_model_section_5_title' => 'Fung Chi: The Courage of a Courier',
        'stoodUp_model_section_5_p1' => 'Among the most respected women in the history of the Hong Kong and Kowloon Brigade was Fung Chi. She was the mother of Urban Squadron leader Fong Lan and actively supported her daughter\'s involvement in resistance work. She later volunteered as a courier, transporting intelligence despite the dangers involved. According to The History of the Hong Kong and Kowloon Brigade, Fung Chi was arrested in March 1944 while carrying intelligence materials.',
        'stoodUp_model_section_5_p2' => 'Historical records indicate that she endured severe torture but refused to reveal information about her comrades or the organisation. She was ultimately executed. In September 2020, Fung Chi was included in the Third National List of Renowned Anti-Japanese Martyrs and Heroic Groups. Her story illustrates that some of the most important acts of resistance occurred far from the battlefield. The work of a courier might involve nothing more than carrying a letter, delivering a message, or travelling along a familiar route. Yet these tasks often carried risks equal to those faced in combat.',

        'stoodUp_model_section_6_title' => 'Wong Cho-Mei: Linking Hong Kong to Allied Intelligence',
        'stoodUp_model_section_6_p1' => 'Wong Cho-mei played a crucial role in the intelligence cooperation between the Hong Kong and Kowloon Brigade and the British Army Aid Group (BAAG). One of the BAAG\'s communication centres in Kowloon—the famous Z Station on Portland Street—operated from a grocery store registered under his name. Members of his family also participated in the operation. When an Allied contact was captured and revealed information under interrogation, Japanese authorities destroyed the station and arrested members of Wong\'s family.',
        'stoodUp_model_section_6_p2' => 'Following the war, Wong received the Member of the Order of the British Empire (MBE) in recognition of his contributions to Allied operations. His experience illustrates how intelligence work often depended on ordinary businesses and family networks rather than military facilities.',

        'stoodUp_model_section_7_title' => 'Chan Chi-Yin, Wong Kam, and the Maritime Resistance',
        'stoodUp_model_section_7_p1' => 'Hong Kong\'s geography gave maritime operations a special significance. Figures such as Chan Chi-Yin and Wong Kam participated in maritime transportation, rescue missions, escort duties, and naval operations. Brigade records and commemorative publications identify them among the key personnel of the Maritime Squadron.',
        'stoodUp_model_section_7_p2' => 'Maritime resistance was exceptionally dangerous. Using small fishing vessels, sailing boats, and launches, these individuals navigated waters patrolled by Japanese gunboats and military craft. Their work expanded the geography of Hong Kong\'s resistance beyond mountains and villages to include Mirs Bay, Lung Kwu Chau, Sha Chau, Lantau Island, and the surrounding South China Sea.',

        'stoodUp_model_section_8_title' => 'Lau Chun-Xiang: A Hero of the Sea',
        'stoodUp_model_section_8_p1' => 'Lau Chun-Xiang was one of the most important figures associated with the Brigade\'s Lantau Island Squadron. In May 1943, he led six resistance fighters on a mission intended to establish communications between guerrilla areas in Bao\'an and Zhongshan. Their vessel was intercepted by Japanese gunboats near Lung Kwu Chau and Sha Chau. Following a fierce engagement, the vessel was sunk and Lau, his companions, and members of the boatman\'s family lost their lives.',
        'stoodUp_model_section_8_p2' => 'His story captures both the courage and the cost of maritime resistance. In 2023, the Lau Chun-Xiang Anti-Japanese Heroes Memorial Monument was unveiled at Lung Kwu Tan. It became Hong Kong\'s first monument dedicated to anti-Japanese heroes formally recognised at the national level.',

        'stoodUp_model_section_9_title' => 'Ling Leung: "The Mother of the Guerrillas"',
        'stoodUp_model_section_9_p1' => 'Not all resistance figures carried weapons. Ling Leung, a resident of Ngong Wo Village in Sai Kung, became known as "the Mother of the Guerrillas." She cared for resistance fighters, allowed her home to be used by the Brigade\'s quartermaster section, and encouraged her two sons to participate in resistance work.',
        'stoodUp_model_section_9_p2' => 'Her story reminds us that food, shelter, care, and emotional support were as essential to resistance as weapons and intelligence. The strength of Hong Kong\'s wartime resistance depended not only on those who fought, but also on those who sustained the fighters.',

        'stoodUp_model_section_10_title' => 'Venerable Fat Ho: A Protector in Times of War',
        'stoodUp_model_section_10_p1' => 'Venerable Fat Ho, abbot of Po Lin Monastery on Lantau Island, represents another dimension of resistance. In 1944, during a Japanese sweep of Lantau Island, Brigade Deputy Commander Lo Fung was recovering from illness at the monastery. Fat Ho concealed him from Japanese troops and refused to reveal his whereabouts despite being beaten during interrogation.',
        'stoodUp_model_section_10_p2' => 'His story demonstrates how religious institutions and religious leaders sometimes became part of the wider resistance network. Monasteries and temples, traditionally places of refuge and compassion, also became places where lives were protected under extraordinary circumstances.',

        'stoodUp_model_section_11_title' => 'The Lo Family of Nam Chung: Resistance as a Family Commitment',
        'stoodUp_model_section_11_p1' => 'The Lo family of Nam Chung, Sha Tau Kok, provides an important example of how resistance could involve entire families. The 80th Anniversary Commemorative Publication of the Hong Kong and Kowloon Brigade highlights members of the family, including Lo Hui-Yuet, Lo Yue-Chung, Lo Yu-Ching, and Lo Au-Fung, whose contributions are featured in exhibitions at the Hong Kong Sha Tau Kok Anti-Japanese War Memorial Hall.',
        'stoodUp_model_section_11_p2' => 'Their story demonstrates that resistance was not always an individual decision. Entire families and villages often became involved, sharing both the responsibilities and the risks associated with resistance work.',

        'stoodUp_model_section_12_title' => 'Students, Workers, Villagers, and Fishermen',
        'stoodUp_model_section_12_p1' => 'One of the most significant characteristics of the Hong Kong and Kowloon Brigade was the diversity of its membership. Its ranks included students, workers, indigenous villagers, fishermen, merchants, and people from many different backgrounds. Most had not been professional soldiers before the war. Some lost educational opportunities after Hong Kong fell. Others lost employment as factories and businesses closed. Many were drawn into resistance through community networks or patriotic movements.',
        'stoodUp_model_section_12_p2' => 'This broad social foundation helped make the Brigade more than a military organisation. Students brought energy and commitment. Workers contributed organisational experience. Villagers understood local geography and community relationships. Fishermen possessed maritime knowledge. Merchants helped maintain supply networks. Together, they reflected the diverse character of Hong Kong society itself.',

        'stoodUp_model_section_13_title' => 'The Women of Hong Kong\'s Resistance',
        'stoodUp_model_section_13_p1' => 'Women played indispensable roles throughout the resistance movement. They served as couriers, organisers, intelligence operatives, caregivers, propagandists, and community mobilisers. Figures such as Fung Chi, Fong Lan, Ling Leung, and Leung Pui-Wan demonstrate the many different forms that courage could take.',
        'stoodUp_model_section_13_p2' => 'Some endured imprisonment without betraying their comrades. Others organised urban operations, cared for resistance fighters, or secretly produced propaganda under blackout conditions. Their stories remind us that resistance cannot be understood solely through armed combat. Many of the most important contributions occurred behind the scenes, through persistence, discretion, and sacrifice.',

        'stoodUp_model_section_14_title' => 'Those Who Fell and Those Who Remembered',
        'stoodUp_model_section_14_p1' => 'Some resistance figures died during the war. Others survived and helped preserve its memory. The Brigade\'s historical records contain the names of commanders, couriers, community organisers, villagers, fighters, medical workers, and countless others whose contributions made resistance possible. Those who survived often participated in writing histories, recording memoirs, and supporting commemorative activities after the war.',
        'stoodUp_model_section_14_p2' => 'The 80th Anniversary Commemorative Publication of the Hong Kong and Kowloon Brigade notes that former Dongjiang Column veterans living in Hong Kong established associations that contributed to the preservation of Brigade history through publications and recollections. Because of these efforts, later generations have been able to learn about a chapter of Hong Kong\'s past that might otherwise have been forgotten.',

        'stoodUp_model_section_15_title' => 'Conclusion: Seeing History Through People',
        'stoodUp_model_section_15_p1' => 'The significance of these individuals lies not simply in remembering their names, but in understanding how history is shaped by human choices. Some chose to lead. Others chose to fight. Some carried intelligence. Some protected secrets. Some opened their homes. Some cared for the wounded. Some endured torture rather than betray their comrades. Together, these choices formed the human foundation of Hong Kong\'s wartime resistance.',
        'stoodUp_model_section_15_p2' => 'Looking back today, we do not see a single type of hero. We see people of different ages, backgrounds, occupations, and experiences. Some carried rifles. Some steered boats. Some delivered messages. Some prepared meals. Some rescued others. Some suffered in silence. It was through their courage, perseverance, and willingness to help one another that the history of occupied Hong Kong became more than a story of hardship and oppression. It also became a story of resilience, solidarity, and the determination to protect one\'s community in a time of war.',

        // tab 2
        'village_title' => 'Village memory',
        'village_subtitle' => 'Villages That Remember',
        'village_intro' => 'The villages of the New Territories played an important role during the War of Resistance against Japanese Aggression. They served as guerrilla bases, sources of food and intelligence, places of refuge, and vital links in transportation and communication networks.',

        'village_section_1_title' => 'Places Where the Memory of War Endures',
        'village_section_1_p1' => 'Many villagers faced intimidation, imprisonment, torture, and even death, yet continued to support resistance activities. Today, the memory of that period survives not only in official histories and memorials, but also in the villages themselves. Across Sai Kung, Sha Tau Kok, Tai Po, Lantau Island, Yuen Long, and Lung Kwu Tan, traces of wartime history remain embedded in mountain paths, bays, churches, ancestral halls, village houses, and coastal landscapes.',
        'village_section_1_p2' => 'These places appear ordinary today, yet during the occupation they witnessed courage, sacrifice, secrecy, and resilience. According to The History of the Hong Kong and Kowloon Brigade, numerous villages—including Wong Mo Ying, Chek Kang, Wu Kau Tang, Ngong Wo, and others—played important roles in supporting resistance operations. Their stories illustrate how local communities became an integral part of Hong Kong\'s wartime experience.',

        'village_section_2_title' => 'Sai Kung: A Landscape of Resistance',
        'village_section_2_p1' => 'Among all regions associated with the Hong Kong and Kowloon Brigade, Sai Kung occupies a particularly important place. Its mountains, villages, bays, and maritime routes connected Kowloon, northeastern New Territories, Mirs Bay, and the wider Dongjiang guerrilla areas in Guangdong. For Japanese forces, this rugged terrain was difficult to control completely. For resistance fighters and their supporters, it offered opportunities for concealment, transportation, communication, and supply operations.',
        'village_section_2_p2' => 'Places such as Wong Mo Ying, Chek Kang, Sham Chung, Shan Liu, Ngong Wo, and Tai Long all became connected, in different ways, to Hong Kong\'s wartime resistance. Some villages housed guerrilla units. Others sheltered fugitives, transported supplies, cared for the wounded, or provided intelligence. Many endured Japanese reprisals as a consequence of their support. The memory of resistance in Sai Kung is therefore not concentrated in a single battlefield. It is dispersed across mountains, shorelines, village lanes, and family homes.',

        // Model
        'village_model_section_1_title' => 'Wong Mo Ying: A Place of Foundation and Suffering',
        'village_model_section_1_p1' => 'Few villages carry greater symbolic significance in the history of the Hong Kong and Kowloon Brigade than Wong Mo Ying. On 3 February 1942, the Brigade was formally established in the village, marking the transition from scattered armed work teams to a unified resistance organisation operating throughout occupied Hong Kong. The village therefore represents both a geographical location and a symbolic birthplace of organised resistance behind enemy lines.',
        'village_model_section_1_p2' => 'Yet Wong Mo Ying is remembered not only for its role in the Brigade\'s founding. According to The History of the Hong Kong and Kowloon Brigade, Japanese forces conducted a sweep through the village on 21 September 1944. Unable to locate guerrilla fighters, they gathered villagers inside the local church and subjected them to severe interrogation and torture in an attempt to obtain information. The story of Wong Mo Ying illustrates an important reality of occupation: villages suspected of supporting resistance often bore the consequences of Japanese retaliation. The silence and endurance of villagers became part of the cost of protecting the resistance.',

        'village_model_section_2_title' => 'Chek Kang: A Village of Intelligence and Support',
        'village_model_section_2_p1' => 'Nestled between mountains and sea, Chek Kang occupied a strategic position that connected multiple land and maritime routes. During the occupation, it served as an important centre for transportation, communications, intelligence, and medical support. The historic residence known as Tin Shui Lau Fong became associated with the British Army Aid Group\'s Y Station, representing one of the most significant examples of intelligence cooperation between the Hong Kong and Kowloon Brigade and Allied forces.',
        'village_model_section_2_p2' => 'Yet Chek Kang\'s wartime memory extends beyond intelligence work. According to The History of the Hong Kong and Kowloon Brigade, Lee Yau-Dai, who served as chairwoman of the village women\'s association, mobilised local women to support resistance activities. Their contributions included organising anti-Japanese performances, gathering firewood, transporting food and supplies, preparing accommodation, cleaning facilities, repairing clothing, caring for the wounded, and carrying intelligence messages. Chek Kang therefore represents more than a resistance base. It demonstrates how an entire community could contribute to the war effort through everyday acts of labour and support.',

        'village_model_section_3_title' => 'Sham Chung: A House Along the Lifeline',
        'village_model_section_3_p1' => 'The Lee Family House at Sham Chung formed an important link in the Brigade\'s transportation network. Historical records indicate that routes passing through Sham Chung connected locations including Yung Shue O, Kei Ling Ha, Shap Sze Heung, Mui Tsz Lam, Chung Mei, Chek Kang, Sai Kung Market, and Pak Tam. Large quantities of supplies passed through the village en route to resistance forces, while intelligence was transmitted through the same network.',
        'village_model_section_3_p2' => 'Buildings such as the Lee Family House possessed a dual identity. Outwardly, they appeared to be ordinary village homes. In reality, they could function as safe houses, communications stations, medical shelters, intelligence centres, or supply depots. The memory of Sham Chung reminds us that resistance depended not only on armed fighters, but also on people willing to transform their homes into places of refuge and support.',

        'village_model_section_4_title' => 'Wu Kau Tang: Hong Kong’s Model Resistance Village',
        'village_model_section_4_p1' => 'Few villages are more closely associated with Hong Kong\'s wartime resistance than Wu Kau Tang. According to The History of the Hong Kong and Kowloon Brigade, it was remembered as "Hong Kong\'s Model Resistance Village." This distinction reflected not the village\'s size, but the sacrifices made by its residents and its role in supporting the resistance movement.',
        'village_model_section_4_p2' => 'On 25 September 1942, Japanese forces carried out a sweep of the village, gathering residents and demanding information about local guerrilla activities. Village leader Lee Sai-Fan refused to reveal any information. He was subjected to water torture, beaten, dragged by military horses, and ultimately died from his injuries. Another village leader, Lee Yuen-Pui, similarly refused to disclose information. He was brutally tortured and suffered permanent injuries. After recovering consciousness, he nevertheless encouraged his daughter and fellow villagers to join the resistance. Their experiences reflect the extraordinary price paid by many rural communities during the occupation.',

        'village_model_section_5_title' => 'The Wu Kau Tang Conference and the Shek Shui Kan Radio Station',
        'village_model_section_5_p1' => 'The historical significance of Wu Kau Tang extends beyond the suffering endured by its residents. In February 1943, senior representatives of the Guangdong Provincial Communist leadership and the Dongjiang military-political leadership convened near Wu Kau Tang in what became known as the Wu Kau Tang Conference. According to the 80th Anniversary Commemorative Publication of the Hong Kong and Kowloon Brigade, this meeting was regarded as an event of major significance in the history of the Communist movement in Guangdong, while the Brigade was responsible for logistics and security.',
        'village_model_section_5_p2' => 'Nearby Shek Shui Kan Village also played a critical role in wartime communications. Between April 1942 and March 1943, the only radio station linking Communist organisations and anti-Japanese guerrilla forces in Guangdong with Yan\'an operated from Shek Shui Kan. The Hong Kong and Kowloon Brigade assisted in selecting and protecting the site. Together, these events transformed the area from an ordinary rural community into an important centre of communication, coordination, and strategic planning.',

        'village_model_section_6_title' => 'Ngong Wo: A Village of Care and Refuge',
        'village_model_section_6_p1' => 'The wartime memory of Ngong Wo Village is closely associated with Ling Leung, affectionately remembered as "the Mother of the Guerrillas." According to the 80th Anniversary Commemorative Publication of the Hong Kong and Kowloon Brigade, she opened her home to the Brigade\'s quartermaster section, encouraged her two sons to participate in resistance work, and helped save the life of resistance worker Leung Suet-Ying during a serious illness in 1943',
        'village_model_section_6_p2' => 'Ngong Wo represents another dimension of resistance. Wars require more than weapons and fighters. They also require places where people can rest, recover, hide, and begin again. The village\'s memory is therefore rooted not in combat, but in care, shelter, and protection.',

        'village_model_section_7_title' => 'Shan Liu and the Great Rescue',
        'village_model_section_7_p1' => 'The village of Shan Liu played an important role in the Great Rescue operation. As evacuees were escorted from Kowloon through Ngau Chi Wan, Kowloon Pass, and onward into Sai Kung, Shan Liu became an important stopping point along the route. Villagers provided food, shelter, and concealment, enabling rescued individuals to continue their journey toward the coast before crossing by sea to Free China.',
        'village_model_section_7_p2' => 'Such assistance rarely produced dramatic scenes, yet it was essential to the success of rescue operations. Every stage of a journey required local knowledge, planning, observation, and support. The memory of Shan Liu reminds us that Hong Kong\'s mountain villages became part of a larger network of escape and survival.',

        'village_model_section_8_title' => 'Lantau Island: Resistance Across an Island Landscape',
        'village_model_section_8_p1' => 'Lantau Island occupies a special place in the history of the Hong Kong and Kowloon Brigade. Its villages, monasteries, mountain trails, and coastal routes were closely connected to the activities of the Lantau Island Squadron, maritime transportation networks, and resistance operations.',
        'village_model_section_8_p2' => 'Lantau\'s distance from the urban centre, combined with its rugged terrain and strategic coastal position, offered opportunities for concealment but also exposed the island to Japanese naval patrols. The island\'s wartime memory includes guerrilla activities, civilian support, religious sanctuary, and maritime sacrifice. The stories of Liu Chun-Xiang and his companions, who lost their lives in the waters near Lung Kwu Chau and Sha Chau, remain closely connected to Lantau\'s resistance history.',

        'village_model_section_9_title' => 'Lung Kwu Tan: Looking Toward the Sea',
        'village_model_section_9_p1' => 'The memory of Lung Kwu Tan is closely linked to the Liu Chun-Xiang Anti-Japanese Heroes Group. In May 1943, Liu Chun-Xiang and his companions sailed from Tung Chung toward Lung Kwu Tan in an attempt to establish new communication routes, but were ambushed by Japanese gunboats near Lung Kwu Chau and Sha Chau and killed in action.',
        'village_model_section_9_p2' => 'According to the commemorative publication of the Liu Chun-Xiang Anti-Japanese Heroes Memorial Monument, Lung Kwu Tan was the location where the group had originally intended to land. It later became the site of the memorial dedicated to their sacrifice. Standing on the shore today, visitors can look across the water toward Lung Kwu Chau and Sha Chau, linking the peaceful landscape of the present with the events of wartime. The monument gives a permanent physical location to a story that originally unfolded at sea.',

        'village_model_section_10_title' => 'Churches, Monasteries, and Ancestral Halls',
        'village_model_section_10_p1' => 'Village memory survives not only in homes but also in religious and communal buildings. The church at Wong Mo Ying, the Catholic community of Chek Kang, Po Lin Monastery, ancestral halls, and village schools all became connected, in different ways, to the wartime experience. Some witnessed interrogations and torture. Others sheltered resistance fighters, cared for the sick, hosted meetings, or served as communication points.',
        'village_model_section_10_p2' => 'These structures are important because they anchor history to identifiable places. When visitors stand before a church, monastery, or ancestral hall today, they are not simply looking at a building. They are standing in a place where people once faced difficult choices, protected others, and endured the pressures of occupation. Local memory allows history to return from the written page to the physical landscape.',

        'village_model_section_11_title' => 'The Risks Faced by Villagers',
        'village_model_section_11_p1' => 'Supporting the resistance often carried severe consequences. Villages suspected of sheltering guerrillas, supplying food, or transmitting intelligence could face raids, arrests, torture, and executions. The experiences of Wu Kau Tang and Wong Mo Ying illustrate the reality that villagers paid a very real human price for their support.',
        'village_model_section_11_p2' => 'Village memory therefore contains not only stories of courage but also stories of fear, suffering, and loss. Many villagers never formally joined the resistance. Their contribution lay in their silence, their willingness to provide shelter, and their determination not to betray those they protected. Their sacrifices form an essential part of Hong Kong\'s wartime history.',

        'village_model_section_12_title' => 'From Oral History to Commemoration',
        'village_model_section_12_p1' => 'Many of these village stories survived through oral testimony, local investigations, family recollections, and commemorative activities. According to The History of the Hong Kong and Kowloon Brigade, the reconstruction of village history draws upon interviews with villagers from places such as Chek Kang, the Chinese University of Hong Kong\'s Sai Kung Oral History Project, and archival materials relating to New Territories communities and maritime populations.',
        'village_model_section_12_p2' => 'This is particularly important because many ordinary villagers left behind few written records. Their experiences have often been preserved through memory rather than official documentation. By recording and preserving these stories, later generations ensure that the contributions of those who supported the resistance are not forgotten.',

        'village_model_section_13_title' => 'Conclusion: Places Remember the War',
        'village_model_section_13_p1' => 'The memory of Hong Kong\'s resistance becomes more tangible when viewed through the villages that experienced it. Wong Mo Ying remembers the founding of the Hong Kong and Kowloon Brigade and the suffering of its villagers; Chek Kang remembers intelligence work, transportation routes, and the contributions of women; Sham Chung remembers the houses and paths that sustained communications. Wu Kau Tang remembers sacrifice, leadership, and strategic coordination; Ngong Wo remembers care and protection; Lantau Island and Lung Kwu Tan remember the dangers of maritime resistance and the sacrifices made at sea.',
        'village_model_section_13_p2' => 'Together, these villages remind us that the War of Resistance was not fought only on distant battlefields. It was also fought along village paths, mountain trails, church grounds, ancestral halls, piers, and shorelines across Hong Kong. These places remember the choices people made, the risks they accepted, and the hope they preserved during one of the darkest periods in the city\'s history.'

     ],
];