<?php

return [
     'japanese_occupation_rule' => [
        'title' => 'The Japanese Occupation Rule',
        'subtitle' => 'The Japanese Occupation Rule',
        'intro' => 'On 25 December 1941, Hong Kong fell to Japanese forces on what would later become known as Black Christmas. With the fighting over, the challenge facing the occupiers was no longer how to defeat the defenders, but how to govern a densely populated city, a major port, and a complex society under military rule.',
          
        // Tabs
        'tab_1' => 'Japanese Rule in Hong Kong',
        'tab_2' => 'Survival and Rationing in Crisis',
        'tab_3' => 'Economy and Society Under Occupation',
        'tab_4' => 'Everyday Life Under Occupation',

    // tab 1
    'rule_hk_section_1_title' => 'From Military Victory to Occupation Government',
    'rule_hk_section_1_p1' => 'The surrender of Hong Kong marked a profound transformation in the city\'s history. The British colonial administration ceased to function, and Hong Kong became a Japanese-occupied territory. Existing political institutions were disrupted, while civilian life was gradually incorporated into a system centred on military control, public security, resource management, and ideological supervision.',
    'rule_hk_section_1_p2' => 'According to Hong Kong Memory, Japanese forces established complete control over Hong Kong on 25 December 1941. In February 1942, the Hong Kong Occupation Government was formally established under Lieutenant General Rensuke Isogai, the first Japanese Governor of Occupied Hong Kong. Hong Kong was subsequently administered as part of Japan\'s wartime military system and was regarded as an important logistical base supporting operations in South China and the Pacific. This shift fundamentally altered the city\'s role. Hong Kong was no longer governed as a civilian colonial port, but as a military occupation centre whose resources, infrastructure, and population were expected to serve Japan\'s wartime objectives.',

    'rule_hk_section_2_title' => 'Establishing the Occupation Government',
    'rule_hk_section_2_p1' => 'Following the occupation, the Japanese administration created a military-civilian governing structure centred on the Hong Kong Occupation Government. Although the new administration assumed responsibility for public administration, policing, judicial functions, economic regulation, and social affairs, its primary purpose remained the support of Japanese military operations. The British administrative system was dismantled. Government buildings, public institutions, police functions, and judicial authority were transferred to Japanese control.',
    'rule_hk_section_2_p2' => 'According to wartime records preserved by the Government Records Service of Hong Kong, the occupation authorities introduced property-registration programmes that recorded ownership, addresses, land values, and building information. Certain streets and districts were renamed using Japanese nomenclature, while buildings and land were requisitioned for military and administrative use.',
    'rule_hk_section_2_p3' => 'These measures reflected more than administrative management. They represented an effort to reshape the urban landscape itself. Streets, buildings, schools, public institutions, and neighbourhoods were systematically reclassified, renamed, and repurposed within the framework of occupation rule.',

    // Model
    'rule_hk_model_section_1_title' => 'A City Governed by Military Priorities',
    'rule_hk_model_section_1_p1' => 'Under Japanese administration, Hong Kong was first and foremost regarded as a strategic military asset. Its harbour, shipyards, warehouses, airport, communications infrastructure, and transportation network were valued primarily for their contribution to Japan\'s military operations across South China and the Pacific. As a result, many aspects of governance became subordinate to military requirements.',
    'rule_hk_model_section_1_p2' => 'Before the war, Hong Kong had functioned as a free port, an international trading centre, and a hub of regional mobility. Under occupation, however, the city increasingly became a controlled logistical base. Ports were used for military transportation, industrial facilities were requisitioned, and civilian movement became subject to curfews, permits, checkpoints, and military oversight.',
    'rule_hk_model_section_1_p3' => 'For ordinary residents, the effects of military rule were felt in everyday life. Travel, employment, business activities, housing, access to food, and even access to information were increasingly regulated. Occupation was not confined to government offices. It extended into markets, streets, schools, police stations, workplaces, and homes.',

    'rule_hk_model_section_2_title' => 'The Kempeitai, Police, and the Politics of Fear',
    'rule_hk_model_section_2_p1' => 'Among the most feared institutions of occupied Hong Kong were the Kempeitai—the Japanese military police—and the broader security apparatus that supported them. To suppress resistance, monitor the population, and maintain control, the Japanese authorities relied upon military police, civilian police, intelligence agents, and local collaborators. House searches, identity checks, arrests, interrogations, and torture became recurring features of life under occupation.',
    'rule_hk_model_section_2_p2' => 'For many residents, the power of the occupation regime rested not only on punishment but on uncertainty. Individuals suspected of sheltering resistance fighters, transmitting intelligence, listening to foreign broadcasts, storing supplies, or associating with the wrong people could attract official attention. Informants and collaborators further deepened public anxiety by creating an atmosphere in which trust became increasingly fragile.',
    'rule_hk_model_section_2_p3' => 'This system of fear served a strategic purpose. It was intended not only to punish resistance but also to discourage it before it occurred. Political discussion became dangerous, assistance to resistance groups became risky, and even private actions could carry significant consequences. Although businesses reopened and daily routines resumed to some extent, many residents lived with a constant awareness that surveillance, investigation, or arrest could occur without warning.',

    'rule_hk_model_section_3_title' => 'Population Control and Forced Repatriation',
    'rule_hk_model_section_3_p1' => 'One of the occupation government\'s most consequential policies was population reduction. Severe food shortages emerged shortly after the occupation began. Unable—or unwilling—to maintain food supplies for Hong Kong\'s pre-war population, the Japanese administration implemented strict rationing and a policy of forced repatriation. According to the Government Records Service, the occupation authorities introduced both rice rationing and population-reduction measures in response to wartime shortages.',
    'rule_hk_model_section_3_p2' => 'Large numbers of unemployed residents, refugees, and individuals without stable access to food were compelled to leave Hong Kong and return to mainland China. For the occupation authorities, reducing the population eased pressure on limited food supplies and simplified administrative control. For affected families, however, the policy often meant separation, displacement, and uncertain journeys through a region already disrupted by war.',
    'rule_hk_model_section_3_p3' => 'The impact on Hong Kong society was profound. Prior to the occupation, the city had absorbed large numbers of refugees, workers, merchants, and intellectuals. During the occupation, population levels declined dramatically as a result of repatriation, hunger, disease, displacement, and death. Neighbourhoods became quieter. Businesses closed. Entire communities were altered. These demographic changes would shape many aspects of wartime life in the years that followed.',

    'rule_hk_model_section_4_title' => 'Registration, Documentation, and Movement Control',
    'rule_hk_model_section_4_p1' => 'Control over movement became another key feature of occupation rule. Residents were increasingly required to carry identity documents, permits, registration papers, and ration cards. Travel between districts often required official authorisation, and access to food or employment could depend upon proper documentation. Without the required papers, individuals risked detention, investigation, or accusations of involvement in resistance activities.',
    'rule_hk_model_section_4_p2' => 'The result was a significant reduction in personal freedom. Routes that had once connected districts, villages, islands, and urban centres became regulated spaces subject to inspection and control. For resistance groups, these measures complicated intelligence gathering and rescue operations. For ordinary residents, even routine travel became more difficult and uncertain.',
    'rule_hk_model_section_4_p3' => 'The permit system also contributed to social inequalities. Those with access to employment, official documentation, or connections to occupation institutions generally found it easier to survive. Those without such advantages faced greater risks of poverty, marginalisation, repatriation, or hunger. Occupation rule thus linked access to basic necessities with administrative compliance and political control.',

    'rule_hk_model_section_5_title' => 'Renaming, Propaganda, and Cultural Assimilation',
    'rule_hk_model_section_5_p1' => 'The Japanese administration sought not only to govern Hong Kong but also to reshape its symbolic landscape. Certain streets and districts received Japanese names. Public spaces displayed imperial propaganda. Schools and newspapers were subjected to censorship and ideological supervision. The Government Records Service notes that street names and place names were altered during the occupation, while property records documented these administrative changes.',
    'rule_hk_model_section_5_p2' => 'These changes were more than bureaucratic adjustments. They formed part of a broader effort to redefine the city\'s identity and integrate it into Japan\'s wartime imperial vision. Language, education, public ceremonies, and media became tools through which the occupation authorities attempted to weaken existing loyalties and promote acceptance of Japanese rule.',
    'rule_hk_model_section_5_p3' => 'Yet official propaganda did not necessarily translate into genuine support. Many residents complied publicly while privately preserving their own views, memories, and identities. Occupation authorities could rename streets and buildings, but they could not entirely erase the fears, grievances, and aspirations that persisted beneath the surface.',

    'rule_hk_model_section_6_title' => 'Local Elites and Collaboration',
    'rule_hk_model_section_6_p1' => 'Managing a city as complex as Hong Kong required more than Japanese personnel alone. The occupation authorities therefore sought assistance from selected Chinese elites, business leaders, community figures, and local intermediaries. Such arrangements reduced administrative burdens while creating the appearance of local participation in governance.',
    'rule_hk_model_section_6_p2' => 'These relationships were often complex and morally ambiguous. Some individuals cooperated in order to protect their families, communities, or businesses. Others actively supported occupation policies and became involved in collaborationist organisations, intelligence work, or law enforcement activities. For resistance groups, local collaborators could be particularly dangerous because of their knowledge of local languages, social networks, and community structures.',
    'rule_hk_model_section_6_p3' => 'As a result, occupied Hong Kong cannot be understood simply as a division between Japanese authorities and local residents. The realities of occupation created difficult choices, competing pressures, and a wide spectrum of responses ranging from resistance to accommodation. The social divisions created during this period would leave lasting scars on the community.',

    'rule_hk_model_section_7_title' => 'The Internment of Foreign Civilians',
    'rule_hk_model_section_7_p1' => 'Foreign civilians also experienced dramatic changes following the occupation. Many British and other Allied civilians were confined in internment camps, the most famous of which was Stanley Internment Camp. Residents of these camps lost their freedom and endured years of uncertainty, shortages, illness, and psychological strain.',
    'rule_hk_model_section_7_p2' => 'The internment system reflected the Japanese government\'s effort to isolate individuals associated with former colonial authorities or enemy nations. While Chinese residents often experienced occupation through rationing, surveillance, forced labour, population controls, and policing measures, foreign civilians were frequently subjected to detention and confinement. Although the experiences differed, both groups lived under the authority of the same occupation regime.',

    'rule_hk_model_section_8_title' => 'Violence as the Foundation of Occupation',
    'rule_hk_model_section_8_p1' => 'Occupation rule was sustained not only through administration but also through the threat of violence. Historical research and post-war testimony document arrests, torture, sexual violence, executions, looting, and other forms of abuse during the occupation period. Even when violence was not immediately visible, its possibility remained ever-present.',
    'rule_hk_model_section_8_p2' => 'For many residents, the greatest burden was uncertainty. The threat could come from Japanese soldiers, military police, informants, collaborationist police, or other agents of the occupation system. In response, many people sought protection through family networks, trusted relationships, and local communities while avoiding unnecessary attention.',
    'rule_hk_model_section_8_p3' => 'This atmosphere of insecurity forms the essential background for understanding later chapters on rationing, economic hardship, survival, and everyday life under occupation. Life under Japanese rule was not merely difficult—it was shaped by the combined pressures of military power, administrative control, and the constant possibility of coercion.',

    'rule_hk_model_section_9_title' => 'Conclusion: A City Under Control',
    'rule_hk_model_section_9_p1' => 'Japanese-occupied Hong Kong was a city fundamentally reshaped by military rule. The Occupation Government, the Kempeitai, police forces, registration systems, population controls, property records, renamed streets, propaganda campaigns, and collaborationist institutions formed an extensive system of control. This system sought to regulate movement, food supplies, employment, housing, language, education, and even public memory. It aimed to transform Hong Kong into a functioning component of Japan\'s wartime machinery.',
    'rule_hk_model_section_9_p2' => 'Yet control did not necessarily produce genuine acceptance. The occupation authorities could seize government offices, rename streets, establish checkpoints, and impose rationing, but they could not eliminate people\'s desire for security, dignity, and freedom. It was precisely because occupation rule was so restrictive that the acts of survival, mutual assistance, and resistance undertaken by Hong Kong\'s people became all the more significant.',

    // tab 2
    'survival_title' => 'Survival and rationing',
    'survival_subtitle' => 'Survival and Rationing in Crisis',
    'survival_intro' => 'One of the most immediate and pressing challenges faced by Hong Kong\'s residents during the Japanese occupation was survival itself. Before the war, Hong Kong depended heavily on imported food and regional trade networks to sustain its population. After the Japanese occupation, transportation routes were disrupted, trade connections severed, and resources requisitioned for military purposes. The city\'s established supply system quickly collapsed.',

    'survival_section_1_title' => 'Living Through Shortage and Uncertainty',
    'survival_section_1_p1' => 'Residents faced not only political repression and military rule, but also the daily struggle to obtain food, fuel, medicine, and other necessities. Questions that had once seemed routine became matters of survival: Was there enough rice? Could fuel be found for cooking? Would medicine still be available? Would there be enough food tomorrow?',
    'survival_section_1_p2' => 'According to exhibition materials produced by the Government Records Service, Hong Kong residents endured severe shortages of food and everyday necessities during the occupation. In response to worsening conditions, the Japanese administration introduced population-reduction measures, strict rice rationing, and compulsory currency conversion into military notes. Although these policies were presented as mechanisms for managing scarce resources, they also increased the population\'s dependence on the occupation authorities. Access to food increasingly depended upon registration, ration tickets, permits, and compliance with official regulations. Those without stable employment, proper documentation, or strong social support networks often found themselves most vulnerable to hunger and displacement.',

    'survival_section_2_title' => 'The Origins of the Food Crisis',
    'survival_section_2_p1' => 'Hong Kong had never been a self-sufficient city. Its dense population and limited agricultural land meant that food supplies depended largely on imports from mainland China and overseas markets. Once war disrupted maritime transport, regional trade, and inland supply routes, food became increasingly scarce. The occupation further intensified these shortages. Japanese military forces and occupation agencies received priority access to available resources, leaving fewer supplies for civilians. The resulting crisis was not simply a consequence of nature or geography. It emerged from a combination of wartime disruption, military requisitioning, economic isolation, and occupation policies.',
    'survival_section_2_p2' => 'As food supplies dwindled, daily life deteriorated rapidly. Rice prices soared. Meat, cooking oil, salt, sugar, fuel, and medicine became increasingly difficult to obtain. Many families reduced the number of meals they ate each day. Rice was stretched into thin porridge, while sweet potatoes, wild vegetables, leaves, and other substitutes became important sources of sustenance. Hunger affected more than physical health. It altered family relationships, economic behaviour, and social priorities. People queued for hours to obtain small amounts of food, exchanged possessions for supplies, sought assistance from relatives, or abandoned the city altogether in search of survival.',

    // Model
    'survival_model_section_1_title' => 'Rice Rationing and Daily Limits',
    'survival_model_section_1_p1' => 'To control food distribution, the Japanese administration introduced a formal rice-rationing system. According to the Government Records Service, by 1942 the daily rice allocation was limited to 6.4 taels per person, distributed through government-issued ration coupons. Rice distribution was restricted to authorised merchants, and contemporary reports in the Hong Kong Daily News indicated that only 57 designated rice dealers operated on Hong Kong Island during this period.',
    'survival_model_section_1_p2' => 'These allocations fell well below normal nutritional requirements. Even residents who possessed ration coupons could not always obtain sufficient food. Long queues, inconsistent quality, and interruptions in supply were common. For labourers, the elderly, children, and those suffering from illness, prolonged undernourishment quickly weakened physical health. Although rationing theoretically guaranteed minimum access to food, it effectively institutionalised scarcity. Daily life became an exercise in calculating how to survive with less than what was needed.',

    'survival_model_section_2_title' => 'Waiting, Queuing, and Uncertainty',
    'survival_model_section_2_p1' => 'Rationing transformed the rhythm of everyday life. Residents often spent hours waiting in line to purchase rice, collect supplies, or obtain information about future distributions. An intelligence report cited by the Government Records Service noted that severe food shortages existed during the early occupation period. Many residents survived on thin rice porridge and waited for hours to obtain rationed rice.',
    'survival_model_section_2_p2' => 'The queue itself became a defining feature of wartime life. Waiting consumed time and energy while generating constant uncertainty. Would supplies run out before reaching the front of the line? Would the ration station close unexpectedly? Would the required documents be accepted? Would prices increase again? For many families, obtaining food became the central concern around which daily life revolved.',

    'survival_model_section_3_title' => 'Forced Repatriation: Reducing the City\'s Population',
    'survival_model_section_3_p1' => 'As shortages intensified, the occupation authorities implemented one of their most controversial policies: population repatriation. According to historical records preserved by the Government Records Service, severe food shortages prompted the Japanese administration to reduce Hong Kong\'s population through organised repatriation programmes. Sources associated with the Hong Kong and Kowloon Brigade further record that occupation authorities sought to expel as many as one million residents, directing many refugees through Yuen Long and onward to Shenzhen.',
    'survival_model_section_3_p2' => 'For the authorities, reducing the population eased pressure on food supplies and simplified administration. For ordinary people, however, repatriation often meant forced displacement. Families were separated. Employment disappeared. Elderly individuals, children, and vulnerable residents faced uncertain journeys through wartime conditions with little guarantee of safety or support. What appeared on paper as a population-management policy became, in practice, a profound humanitarian crisis.',

    'survival_model_section_4_title' => 'From City to Countryside',
    'survival_model_section_4_p1' => 'Under the combined pressures of rationing and repatriation, many residents left urban areas in search of food. The countryside offered no guarantee of comfort, but it sometimes provided access to farmland, fuel, relatives, and local support networks unavailable in the city. This movement altered the social landscape of Hong Kong.',
    'survival_model_section_4_p2' => 'Neighbourhoods that had once been crowded became quieter. Businesses closed. Families dispersed. Meanwhile, villages in the New Territories absorbed increasing numbers of refugees and displaced residents. Some exchanged labour for food. Others depended upon relatives or charitable assistance. Many travelled considerable distances in search of basic necessities. Survival increasingly depended not only on personal effort, but also on whether one had somewhere to go and someone willing to help.',

    'survival_model_section_5_title' => 'The Black Market and the Economy of Exchange',
    'survival_model_section_5_p1' => 'When official supplies proved inadequate, the black market became an important part of everyday survival. Rice, fuel, salt, cooking oil, medicine, cloth, and other essentials could often be obtained through unofficial channels—usually at greatly inflated prices. Families with savings or valuable possessions could exchange jewellery, furniture, clothing, or foreign currency for food. Poorer households frequently exhausted their resources quickly and found themselves with little left to trade.',
    'survival_model_section_5_p2' => 'The black market reflected more than opportunism. It emerged because official distribution systems failed to meet basic needs. For some, it offered a means of survival. For others, it represented exploitation. In either case, it became a central feature of the wartime economy. Many families gradually exchanged years of accumulated possessions for only a few days\' worth of food.',

    'survival_model_section_6_title' => 'Military Currency and Economic Collapse',
    'survival_model_section_6_p1' => 'The Japanese administration required residents to exchange Hong Kong currency for Japanese military notes. According to the Government Records Service, this compulsory currency conversion effectively transferred private wealth into the hands of the occupation authorities. The consequences were severe.',
    'survival_model_section_6_p2' => 'Savings lost value. Confidence in the currency eroded. Inflation intensified. Even residents who possessed money often found that essential goods remained unavailable. In an environment of scarcity, tangible items became more valuable than paper currency. Rice, fuel, medicine, clothing, and permits often carried greater practical value than money itself.',

    'survival_model_section_7_title' => 'Fuel Shortages and the Challenge of Cooking',
    'survival_model_section_7_p1' => 'Food shortages were accompanied by shortages of fuel. The Government Records Service notes that firewood and other fuel sources became increasingly difficult to obtain during the occupation. Even families fortunate enough to acquire rice sometimes lacked the means to cook it.',
    'survival_model_section_7_p2' => 'Residents adapted by preparing thinner meals, cooking in larger batches, collecting firewood, dismantling wooden materials for fuel, and reusing whatever combustible materials they could find. The challenges of daily life extended beyond obtaining food. Cooking, heating, and basic household activities became increasingly difficult under conditions of scarcity.',

    'survival_model_section_8_title' => 'Rooftop Gardens and Self-Help',
    'survival_model_section_8_p1' => 'In response to shortages, many residents sought ways to become more self-reliant. According to the Government Records Service, some residents cultivated vegetables on rooftops during the occupation in an effort to supplement their diets.',
    'survival_model_section_8_p2' => 'Rooftops, courtyards, vacant lots, hillsides, and village land were transformed into small-scale growing areas. These gardens rarely produced enough food to eliminate hunger, but they represented an important form of self-help and resilience. For many families, a small patch of vegetables provided not only nutrition but also hope.',

    'survival_model_section_9_title' => 'Hunger, Disease, and Death',
    'survival_model_section_9_p1' => 'Long-term hunger weakened resistance to disease. Medical supplies were scarce. Hospitals and clinics operated under difficult conditions. Malnutrition, infectious disease, injury, and deteriorating sanitation combined to threaten public health. The Government Records Service records that conditions within internment camps were particularly harsh, with many detainees suffering from malnutrition and illness.',
    'survival_model_section_9_p2' => 'Conditions in rural areas could be equally severe. According to The History of the Hong Kong and Kowloon Brigade, villagers in Chek Keng endured extreme hardship during the occupation. Food shortages became so severe that two residents reportedly died of starvation. Yet even under these conditions, villagers continued to contribute rice to support resistance fighters. Such accounts remind us that hunger was not an abstract statistic—it was a force that shaped daily decisions and, in some cases, determined life and death.',

    'survival_model_section_10_title' => 'Families Under Strain',
    'survival_model_section_10_p1' => 'The burdens of rationing and population control affected different groups in different ways. Young and healthy adults sometimes found opportunities to seek work or relocate. The elderly, children, pregnant women, the sick, and those living alone often faced greater difficulties. Once a household lost its income, savings and possessions could disappear rapidly. Some families sent children to live with relatives. Others sought refuge elsewhere. Many became separated and never reunited.',
    'survival_model_section_10_p2' => 'Under such conditions, the family became the most important unit of survival. Decisions about who would eat first, who would receive limited resources, who would remain, and who would leave were often painful and deeply personal. The suffering of wartime Hong Kong was not measured only in demographic statistics or economic indicators. It was also experienced through countless quiet sacrifices made within individual households.',

    'survival_model_section_11_title' => 'Dignity Amid Scarcity',
    'survival_model_section_11_p1' => 'Perhaps the harshest aspect of rationing was the way it forced people to struggle for the most basic necessities of life. Queuing, registration checks, waiting, rejection, and displacement became part of the occupation experience. Yet survival did not necessarily mean surrender.',
    'survival_model_section_11_p2' => 'Many residents continued to care for their families, assist neighbours, support resistance groups, and preserve hope despite extraordinary hardship. Historical records describe villagers in places such as Chek Kang and Tai Long sharing scarce food supplies with resistance fighters despite facing shortages themselves. Such actions remind us that resistance sometimes took the form of armed struggle—but it could also take the form of generosity, solidarity, and mutual aid during times of hunger.',

    'survival_model_section_12_title' => 'Conclusion: Hong Kong in a Time of Hunger',
    'survival_model_section_12_p1' => 'The rationing system forced Hong Kong\'s residents to confront the limits of survival every day. Food shortages, restricted rice allocations, population repatriation, black-market trading, currency devaluation, fuel scarcity, disease, and displacement combined to create some of the most difficult conditions experienced during the occupation. For many people, war was not experienced primarily through battles or military campaigns. It was experienced through shrinking bowls of rice, hours spent waiting in queues, the loss of savings, the search for fuel, and the difficult decision to leave home in search of survival.',
    'survival_model_section_12_p2' => 'This history reminds us that the damage caused by occupation extended beyond violence and imprisonment. It was also measured in hunger, deprivation, and the gradual erosion of everyday life. The survival of Hong Kong\'s people during these years was not inevitable. It was the result of persistence, sacrifice, mutual support, and a continuous struggle to endure under extraordinarily difficult circumstances.',

    // tab 3
    'economy_title' => 'Economy and Society',
    'economy_subtitle' => 'Economy and Society Under Occupation',
    'economy_intro' => 'Japanese occupation transformed Hong Kong not only politically, but also economically and socially.',

    'economy_section_1_title' => 'A City Reshaped by War',
    'economy_section_1_p1' => 'Before the war, Hong Kong was one of South China\'s most important free ports, a major centre for trade and finance, and a key gateway linking China with the wider world. After the occupation, commercial networks were severed, banks and currency systems were reorganised, factories and warehouses were requisitioned, and private property became increasingly vulnerable to government control. The impact extended far beyond markets and businesses.',
    'economy_section_1_p2' => 'The wartime economy altered how people worked, travelled, spent money, obtained food, and interacted with one another. Employment disappeared, savings lost value, social networks weakened, and many families found themselves struggling to survive. According to Hong Kong Memory, Hong Kong\'s population declined from approximately 1.6 million before the occupation to around 600,000 by the time of Japan\'s surrender in 1945. This dramatic reduction reflected not only wartime casualties but also displacement, repatriation, economic collapse, and the breakdown of normal social life.',

    'economy_section_2_title' => 'The End of the Free Port',
    'economy_section_2_p1' => 'Much of Hong Kong\'s pre-war prosperity depended upon its role as a free port and international trading centre. The city thrived on maritime commerce, financial services, shipping, and its connections with mainland China. Once Japanese forces occupied Hong Kong, however, these foundations rapidly deteriorated. International shipping routes were disrupted. Foreign trade became subject to wartime restrictions and blockades. British, American, and Allied businesses could no longer operate normally, while many companies, warehouses, and commercial facilities were seized, controlled, or closed by the occupation authorities. Hong Kong ceased to function as an open trading port and instead became an economy subordinate to Japan\'s wartime priorities.',
    'economy_section_2_p2' => 'The consequences for ordinary residents were severe. The decline of maritime trade affected dockworkers, sailors, warehouse staff, transport workers, merchants, clerks, and countless others whose livelihoods depended upon commerce. As trade contracted, employment opportunities disappeared, supplies became scarcer, and prices continued to rise. Many residents could no longer survive through their pre-war occupations and were forced to seek temporary work, rely on informal exchanges, depend upon relatives, or leave Hong Kong altogether.',
    
    // Model
    'economy_model_section_1_title' => 'Military Notes and Monetary Collapse',
    'economy_model_section_1_p1' => 'One of the most significant economic changes introduced during the occupation was the replacement of Hong Kong’s monetary system. According to Hong Kong Memory, from 1 June 1943 onward, Hong Kong dollars could no longer be exchanged for Japanese military notes, which became the territory’s sole legal currency. The Government Records Service further notes that residents were compelled to exchange Hong Kong currency for military notes, effectively transferring private wealth into a currency controlled by the occupation authorities. The consequences were profound.',
    'economy_model_section_1_p2' => 'Unlike established currencies, military notes lacked a stable economic foundation and could be issued in large quantities by the Japanese administration. As the war progressed and Japan’s military situation deteriorated, inflation accelerated and public confidence in the currency declined. For many residents, money itself became unreliable. A sack of rice, a bottle of cooking oil, medicine, clothing, or fuel often possessed greater practical value than a stack of military notes.',

    'economy_model_section_2_title' => 'Banks, Businesses, and Property Under Control',
    'economy_model_section_2_p1' => 'The occupation authorities also restructured Hong Kong’s financial and commercial institutions. Banks associated with Britain, the United States, and other Allied nations were restricted, liquidated, or placed under supervision. Japanese banks and businesses received preferential treatment. This restructuring represented more than an economic adjustment—it was a transfer of power: control over currency, banking, deposits, trade, and credit was reorganised under the occupation regime.',
    'economy_model_section_2_p2' => 'Government Records Service wartime records show that the Japanese authorities undertook property registration after the occupation, documenting addresses, land area, ownership, and valuations, while also requisitioning buildings and land. For ordinary residents and businesses, property no longer offered stability or security. Homes could be occupied, warehouses taken over, equipment confiscated, and bank savings rendered worthless. Wealth accumulated before the war rapidly became vulnerable under the pressures of war and occupation.',

    'economy_model_section_3_title' => 'An Economy Directed Toward War',
    'economy_model_section_3_p1' => 'Economic activity during the occupation was increasingly shaped by military needs. Japanese authorities prioritised shipyards, airports, warehouses, transportation infrastructure, and industrial facilities capable of supporting military operations. Resources that had once served civilian markets were redirected toward wartime objectives. Factories were closed, repurposed, or compelled to support the occupation administration. Vehicles, vessels, fuel, metal, timber, and construction materials were often requisitioned. As a result, Hong Kong\'s economy lost much of its normal commercial function.',
    'economy_model_section_3_p2' => 'Businesses could no longer respond primarily to market demand. Employment became unstable. Supply chains broke down. The objective of the occupation authorities was not to restore Hong Kong’s prosperity as a commercial city, but to extract value from the territory in support of Japan’s war effort. Economic activity continued, but its purpose, beneficiaries, and rules had fundamentally changed.',

    'economy_model_section_4_title' => 'Unemployment and Labour Pressures',
    'economy_model_section_4_p1' => 'As trade declined and businesses closed, unemployment became widespread. The loss of employment affected more than income. It also influenced access to rationed food, housing, and the right to remain in Hong Kong. Those without work were often considered surplus population and faced increased pressure under repatriation policies. Those who remained employed frequently had little choice but to accept low wages, difficult conditions, or work connected to military projects.',
    'economy_model_section_4_p2' => 'Labour was increasingly controlled by the occupation system rather than market forces. Residents worked on roads, docks, construction sites, shipyards, airfields, and other military-related projects. Employment became a means of survival rather than stability.',

    'economy_model_section_5_title' => 'The Black Market and the Informal Economy',
    'economy_model_section_5_p1' => 'Shortages, inflation, and inadequate official supplies contributed to the rapid growth of the black market. Rice, cooking oil, medicine, cloth, fuel, and countless other necessities were traded through unofficial channels. Jewellery, furniture, clothing, foreign currency, and personal possessions were frequently exchanged for food.',
    'economy_model_section_5_p2' => 'The black market was both exploitative and essential. For some, it offered opportunities for profit. For others, it represented the only means of survival. Its existence reflected the limitations of the occupation economy. When official systems could no longer meet basic needs, informal networks emerged to fill the gap. Access to goods increasingly depended upon personal connections, resources, and luck. Those with access to supplies or transportation routes often enjoyed significant advantages, while poorer households became increasingly vulnerable. As a result, wartime society became more unequal and more dependent upon informal relationships.',

    'economy_model_section_6_title' => 'Population Decline and Social Dislocation',
    'economy_model_section_6_p1' => 'The occupation years witnessed a dramatic decline in Hong Kong\'s population. According to Hong Kong Memory, the population fell from approximately 1.6 million before the occupation to around 600,000 by 1945. This decline resulted from repatriation, displacement, starvation, unemployment, disease, wartime deaths, and the fragmentation of families. The effects extended far beyond statistics.',
    'economy_model_section_6_p2' => 'Neighbourhoods became quieter. Schools, businesses, factories, and community organisations lost members. Families found themselves dispersed across Hong Kong, the New Territories, Guangdong, and beyond. Many who left never returned. The city remained physically intact in many places, yet its social fabric had been profoundly damaged.',

    'economy_model_section_7_title' => 'Shifting Social Hierarchies',
    'economy_model_section_7_p1' => 'Occupation altered the distribution of resources and opportunities. Individuals who had enjoyed wealth and status before the war could quickly lose security if their assets were seized or their savings lost value. Workers and the poor, already vulnerable, faced even greater difficulties amid unemployment and food shortages. At the same time, some individuals gained advantages through access to supplies, administrative positions, commercial connections, or black-market networks. These changes created complex moral and social questions.',
    'economy_model_section_7_p2' => 'Some cooperated with occupation authorities in order to preserve institutions, provide medical services, or protect local communities. Others actively collaborated for personal gain. Many residents found themselves navigating difficult choices shaped by fear, responsibility, and survival. The social history of occupied Hong Kong is therefore not simply a story of victims and perpetrators, but also a story of difficult decisions made under extraordinary circumstances.',

    'economy_model_section_8_title' => 'Charitable Organisations and Relief Efforts',
    'economy_model_section_8_p1' => 'Despite severe constraints, traditional Chinese charitable institutions continued to provide assistance during the occupation. Organisations such as the Tung Wah Group of Hospitals and Po Leung Kuk attempted to maintain medical services, relief programmes, shelters, and funeral assistance despite shortages of funding, supplies, and administrative support. Their efforts provided limited but important assistance to vulnerable members of society.',
    'economy_model_section_8_p2' => 'Yet charitable work could not compensate for the wider collapse of the economy. As hunger, unemployment, and disease spread, the resources available to relief organisations remained limited. They functioned less as solutions than as attempts to alleviate the worst consequences of a society under strain. Their continued efforts nevertheless demonstrate that traditions of mutual aid and public responsibility survived even during the occupation.',

    'economy_model_section_9_title' => 'Education, Professionals, and Youth Opportunities',
    'economy_model_section_9_p1' => 'The economic crisis also affected education and professional life. Many schools were closed, relocated, or requisitioned. Students lost access to normal educational opportunities at precisely the moment when young people would ordinarily have been preparing for their futures. Paths into business, industry, higher education, and professional careers were disrupted by war. Some young people entered the workforce prematurely. Others left Hong Kong. Some joined resistance organisations. Many found themselves caught between unemployment and interrupted education.',
    'economy_model_section_9_p2' => 'Professional groups also faced significant challenges. Doctors, teachers, engineers, bank employees, civil servants, and business professionals all had to adapt to the realities of occupation. Some worked within institutions controlled by the occupation authorities. Others participated in underground activities or survived through private support networks. For an entire generation, the normal pathways of social advancement were interrupted by war.',

    'economy_model_section_10_title' => 'Reshaping Urban Space',
    'economy_model_section_10_p1' => 'The occupation transformed not only the economy but also the city itself. The Government Records Service records that buildings and land were requisitioned while certain streets and districts were renamed according to Japanese conventions. Schools became military facilities. Commercial buildings were appropriated for government functions. Warehouses supported military logistics. Residential properties were registered, reassigned, or occupied.',
    'economy_model_section_10_p2' => 'Although the physical city remained, its meaning and function changed. Places once associated with commerce, education, or community life could become military installations, administrative centres, or detention facilities. Economic control therefore extended beyond markets and businesses into the urban landscape itself.',

    'economy_model_section_11_title' => 'Wartime Profits and Moral Ambiguity',
    'economy_model_section_11_p1' => 'Every wartime economy creates winners as well as losers. During the occupation, some individuals profited through black-market activity, smuggling, privileged access to supplies, administrative influence, or cooperation with occupation institutions. These activities often intensified social inequalities and generated lasting controversy after the war.',
    'economy_model_section_11_p2' => 'The distinction between survival, accommodation, and profiteering was not always clear. Some people interacted with occupation authorities to protect their families or institutions. Others used the system to advance their own interests at the expense of others. These grey areas became one of the enduring legacies of occupation. The economic damage caused by war extended beyond material loss. It also eroded trust, leaving communities to question who had helped others during difficult times and who had benefited from their suffering.',

    'economy_model_section_12_title' => 'Conclusion: A Society Transformed by Economic Collapse',
    'economy_model_section_12_p1' => 'Under Japanese occupation, Hong Kong was transformed from a free port and commercial hub into an economy subordinated to military priorities. Currency lost credibility. Trade declined. Property and businesses came under official control. Employment patterns changed. Population levels fell dramatically. Informal markets became essential to survival. These developments represented far more than economic decline.',
    'economy_model_section_12_p2' => 'They altered relationships, disrupted communities, weakened social institutions, and reshaped everyday life. For many residents, the greatest hardship was not simply poverty, but the disappearance of the foundations upon which ordinary life depended: stable work, reliable money, access to supplies, community networks, and trust in the future. The economic collapse of occupied Hong Kong therefore became a profound social trauma—one that forced a city renowned for trade and mobility to relearn how to survive under conditions of restriction, scarcity, and uncertainty.',

     // tab 4
    'everyday_title' => 'Everyday Life Under Occupation',
    'everyday_subtitle' => 'Everyday Life Under Occupation',
    'everyday_intro' => 'During the Japanese occupation, war was not confined to military headquarters, police stations, or official proclamations. It entered the daily lives of ordinary people.',

    'everyday_section_1_title' => 'Living Amid Fear and Scarcity',
    'everyday_section_1_p1' => 'Street names changed. School curricula changed. Newspapers and radio broadcasts were censored. Blackout regulations darkened the city at night. Residents faced inspections, searches, and uncertainty whenever they left home—and often returned to homes where food was scarce. For ordinary Hong Kong residents, war was not a distant international conflict. It was a reality encountered every day.',
    'everyday_section_1_p2' => 'The focus is concerned not only with policies and statistics, but with how people lived under occupation. Some spent hours queuing for food. Others turned rooftops into vegetable gardens. Families carefully concealed light from their windows to comply with blackout regulations. People listened quietly for news, hid relatives or resistance workers, and learned when silence was the safest response. According to exhibitions presented by the Government Records Service, residents of occupied Hong Kong faced severe shortages of food and daily necessities, while buildings were destroyed or requisitioned, and the appearance of the city changed dramatically.',

    'everyday_section_2_title' => 'A Familiar City Becomes Unfamiliar',
    'everyday_section_2_p1' => 'Following the occupation, Japanese authorities sought not only to govern Hong Kong but also to reshape its symbolic landscape. Government buildings and military facilities were taken over. Public buildings were repurposed. Streets and districts were renamed using Japanese terminology. The Government Records Service notes that occupation authorities conducted property-registration programmes, renamed certain streets and districts, and requisitioned buildings and land for military and administrative purposes.',
    'everyday_section_2_p2' => 'For residents, these changes represented more than administrative adjustments. Street names, schools, markets, and public spaces formed part of everyday memory and identity. When familiar places were renamed, restricted, or repurposed, the city itself felt different. People still walked the same roads and lived in the same neighbourhoods, yet they did so within an entirely different system of power. This sense of unfamiliarity was one of the most difficult aspects of daily life to measure, yet one of the most deeply felt.',

    // Model
    'everyday_model_section_1_title' => 'Blackouts and the Fear of Night',
    'everyday_model_section_1_p1' => 'Blackout regulations transformed the city\'s nights. Windows had to be covered. Light could not be allowed to escape into the streets. Patrols and inspections made evening activities increasingly risky. For many households, a small light might simply be needed for cooking, reading, sewing, or studying. Under occupation, however, even a faint glow could attract unwanted attention.',
    'everyday_model_section_1_p2' => 'An account recorded in The History of the Hong Kong and Kowloon Brigade illustrates how these restrictions intersected with underground resistance work. Leung Pui-Wan, who worked during the day at the Yokohama Specie Bank, secretly produced resistance propaganda in a loft on Pottinger Street at night. Before beginning her work, she carefully sealed the windows with blankets and curtains to prevent any light from escaping during blackout hours. Her experience reveals how even something as ordinary as light became associated with danger. In occupied Hong Kong, darkness was not merely a condition of night—it was part of the machinery of war.',

    'everyday_model_section_2_title' => 'The Shrinking World of the Family',
    'everyday_model_section_2_p1' => 'Before the war, family life in Hong Kong followed relatively stable rhythms shaped by work, school, markets, festivals, and social activities. Occupation disrupted those routines. Food shortages, inflation, fuel scarcity, family separation, and repatriation policies forced many households to focus increasingly on survival.',
    'everyday_model_section_2_p2' => 'The home became more than a place of rest. It became a storage space for scarce supplies, a refuge from uncertainty, a place to care for the sick, hide possessions, shelter relatives, and wait for news. Food distribution often became the most important daily concern. Parents frequently reduced their own portions so that children or elderly family members could eat. Valuables were exchanged for food. Some families left the city to seek support from relatives in rural areas. The hardships of wartime family life were not always dramatic. Sometimes they were reflected simply in a bowl of rice porridge that became thinner with each passing month.',

    'everyday_model_section_3_title' => 'Schools and Education Under Occupation',
    'everyday_model_section_3_p1' => 'Education was also reshaped by occupation policy. Japanese authorities regarded schools as important instruments for influencing public attitudes and promoting loyalty to the occupation regime. Historical records indicate that Japanese-language instruction became increasingly important, English-language education was restricted, and schools were encouraged to promote Japanese traditions and customs.',
    'everyday_model_section_3_p2' => 'For students, school became more than a place of learning. Some schools closed. Others were requisitioned. Many children left education entirely because of financial hardship or displacement. Those who remained in school faced changing curricula, altered language requirements, and uncertainty about the future. For a generation of young people, war interrupted the expected progression from education to employment and adulthood.',

    'everyday_model_section_4_title' => 'Newspapers, Radio, and Propaganda',
    'everyday_model_section_4_p1' => 'Information became increasingly difficult to obtain. Newspapers were censored. Radio broadcasts were monitored and controlled. Films and public information campaigns were used to promote official messages. Historical sources indicate that the Hong Kong News became an important vehicle for Japanese propaganda, while Chinese-language newspapers were reduced in number and subjected to strict censorship. Radio and cinema were also used to support occupation objectives.',
    'everyday_model_section_4_p2' => 'As a result, residents often struggled to obtain reliable information. Was the war turning against Japan? Were Allied forces advancing? Were missing relatives still alive? Would food supplies improve? Reliable answers were often unavailable. People pieced together information from official announcements, rumours, underground sources, and fragments of news from outside Hong Kong. The uncertainty itself became a source of anxiety.',

    'everyday_model_section_5_title' => 'Entertainment in Wartime',
    'everyday_model_section_5_p1' => 'Even during wartime, people sought moments of relief. Cinemas, cafés, teahouses, and small-scale entertainment venues continued to operate to varying degrees. Yet access became more limited, and the nature of entertainment changed significantly. Historical records note that entertainment remained available primarily to those who could afford it. Cinemas largely screened Japanese films, including Hong Kong Attack (香港攻略), the only feature film produced in occupied Hong Kong.',
    'everyday_model_section_5_p2' => 'Entertainment therefore acquired a contradictory character. It offered temporary escape from hunger and fear, yet it could also serve as a vehicle for occupation propaganda. For some residents, attending a film or listening to music provided a rare opportunity to relax. For many others, such experiences became luxuries beyond reach.',

    'everyday_model_section_6_title' => 'Illness and Medical Care',
    'everyday_model_section_6_p1' => 'Disease and ill health were constant concerns. Food shortages weakened physical health, while medicine became increasingly scarce. Hospitals and clinics struggled with limited resources, and overcrowded living conditions increased the risk of disease. For ordinary families, illness often carried both medical and financial consequences. Treatment cost money. Medicine was difficult to obtain. Caring for sick relatives required food, time, and energy that many households could scarcely spare. As a result, community support became especially important.',
    'everyday_model_section_6_p2' => 'People relied on traditional remedies, assistance from neighbours, and informal networks to obtain medicine and care. According to The History of the Hong Kong and Kowloon Brigade, the residence known as Tin Shui Lau Fong at Chek Kang—later associated with the British Army Aid Group\'s Y Station—also supported medical care for Brigade members and supplied medicine to prisoners of war held in Kowloon. This reminds us that wartime healthcare extended far beyond hospitals and clinics. It was also provided through village homes, safe houses, and underground networks.',

    'everyday_model_section_7_title' => 'Life in the Villages',
    'everyday_model_section_7_p1' => 'Life in rural areas differed from that of the city but was no less difficult. Villages often had access to farmland, water, and natural resources, yet they also faced military sweeps, food requisitioning, bandit activity, and transportation challenges. Communities in areas such as Sai Kung, Sha Tau Kok, and Lantau Island found themselves caught between occupation forces and resistance activities.',
    'everyday_model_section_7_p2' => 'According to The History of the Hong Kong and Kowloon Brigade, Japanese troops conducted sweeps through Wong Mo Ying Village. When they failed to locate resistance fighters, villagers were taken to the local church and subjected to severe interrogation and torture. Such incidents demonstrate that rural communities were not isolated from the war. Daily life might involve farming, cooking, and caring for family members one moment, while the threat of searches and violence loomed the next.',

    'everyday_model_section_8_title' => 'Hidden Lives in the City',
    'everyday_model_section_8_p1' => 'In urban Hong Kong and Kowloon, daily life often depended upon concealment. Working, shopping, travelling, visiting relatives, or collecting food could involve inspections and questioning. Some individuals maintained outwardly ordinary lives while secretly participating in resistance activities.',
    'everyday_model_section_8_p2' => 'The experience of Leung Pui-Wan illustrates this dual existence. By day, she worked at a Japanese bank and secretly recorded valuable economic information, including details about currency issuance, financial reports, and institutional transactions. By night, she produced underground propaganda materials. Her life appeared ordinary on the surface, yet every action involved risk. For many residents, survival required navigating carefully between outward compliance and private resistance.',

    'everyday_model_section_9_title' => 'Trust and Suspicion',
    'everyday_model_section_9_p1' => 'Occupation strained social trust. Informants, collaborators, police investigations, and surveillance made people cautious about what they said and whom they trusted. Families lowered their voices during conversations. Questions from strangers could provoke suspicion. Even long-standing relationships sometimes weakened under the pressure of fear. Yet trust did not disappear entirely.',
    'everyday_model_section_9_p2' => 'People sheltered relatives and friends. Food was shared. Resistance workers were guided through unfamiliar territory. Some individuals endured interrogation without betraying others. Daily life under occupation therefore contained two opposing forces: fear and solidarity. Both shaped the social experience of wartime Hong Kong.',

    'everyday_model_section_10_title' => 'Festivals and the Changing Experience of Time',
    'everyday_model_section_10_p1' => 'Traditional festivals also changed under occupation. Christmas became associated with the memory of Black Christmas. Lunar New Year, Mid-Autumn Festival, Ching Ming, and Chung Yeung could no longer be celebrated in the same way because of shortages, transportation difficulties, and restrictions on movement. Family reunions became more difficult.',
    'everyday_model_section_10_p2' => 'The rhythm of life itself changed. Before the war, many people organised their lives around work schedules, school terms, festivals, and family plans. During the occupation, people measured time through ration distributions, curfews, military searches, rumours of Allied advances, and the hope that the war might soon end. The three years and eight months of occupation were experienced not as a single event, but as countless days of waiting, worrying, searching for food, and enduring uncertainty.',

    'everyday_model_section_11_title' => 'Childhood During the Occupation',
    'everyday_model_section_11_p1' => 'For children and young people, wartime memories were often fragmented yet powerful. Many remembered hunger, queues, relocation, interrupted schooling, missing family members, soldiers in the streets, and whispered conversations at home. Children may not have fully understood politics or military events, but they understood fear and change. War often brought childhood to an abrupt end.',
    'everyday_model_section_11_p2' => 'Older children and teenagers frequently assumed adult responsibilities, finding work, caring for relatives, delivering messages, guiding travellers, or participating in resistance activities. This helps explain why students, workers, and young residents feature so prominently in many later accounts of resistance during the occupation.',

    'everyday_model_section_12_title' => 'Everyday Acts of Resistance',
    'everyday_model_section_12_p1' => 'Resistance did not always take the form of armed combat. Sometimes it meant printing a leaflet despite blackout restrictions. Sometimes it meant quietly passing information to a trusted contact. Sometimes it meant refusing to answer questions during an interrogation. Sometimes it meant sharing medicine, food, or shelter with someone in need.',
    'everyday_model_section_12_p2' => 'According to The History of the Hong Kong and Kowloon Brigade, the propaganda materials produced by Leung Pui-Wan included reports of Dongjiang Column and Hong Kong and Kowloon Brigade operations, information about conditions in the city, and messages encouraging support for the anti-Japanese struggle. These activities remind us that resistance could occur even in places where military action was impossible. Everyday life itself could become a form of resistance.',

    'everyday_model_section_13_title' => 'Conclusion: To Survive, and to Remember',
    'everyday_model_section_13_p1' => 'The history of everyday life under occupation is not as easily recorded as battles or government policies. It consists of small moments: a lamp carefully hidden behind curtains, a censored newspaper, a requisitioned school, a bowl of thin rice porridge, a whispered conversation, a renamed street, or a person concealed from the authorities. Together, these fragments reveal a side of history closest to the experiences of ordinary people.',
    'everyday_model_section_13_p2' => 'Understanding everyday life during the occupation allows us to see how residents survived from one day to the next amid fear, scarcity, and uncertainty. The people of occupied Hong Kong were not merely victims of war. They were individuals who struggled to preserve their families, their communities, their memories, and their dignity under extraordinarily difficult circumstances. It is through these everyday experiences that we can most fully appreciate the weight of Hong Kong\'s three years and eight months under occupation.',
    ]
];
