<?php

return [
     'japanese_occupation_rule' => [
        'title' => 'The Japanese Occupation Rule',
        'subtitle' => 'The Japanese Occupation Rule',
        'intro' => 'On 25 December 1941, Hong Kong fell to Japanese forces on what would later become known as Black Christmas. With the fighting over, the challenge facing the occupiers was no longer how to defeat the defenders, but how to govern a densely populated city, a major port, and a complex society under military rule.',
          
        // Tabs
        'tab_1' => 'Japanese Rule in Hong Kong',
        'tab_2' => 'Survival and Rationing in Crisis',
        'tab_3' => 'Economy and Society Under Occupation',
        'tab_4' => 'Everyday Life Under Occupation',

    // tab 1
    'rule_hk_section_1_title' => 'From Military Victory to Occupation Government',
    'rule_hk_section_1_p1' => 'The surrender of Hong Kong marked a profound transformation in the city\'s history. The British colonial administration ceased to function, and Hong Kong became a Japanese-occupied territory. Existing political institutions were disrupted, while civilian life was gradually incorporated into a system centred on military control, public security, resource management, and ideological supervision.',
    'rule_hk_section_1_p2' => 'According to Hong Kong Memory, Japanese forces established complete control over Hong Kong on 25 December 1941. In February 1942, the Hong Kong Occupation Government was formally established under Lieutenant General Rensuke Isogai, the first Japanese Governor of Occupied Hong Kong. Hong Kong was subsequently administered as part of Japan\'s wartime military system and was regarded as an important logistical base supporting operations in South China and the Pacific. This shift fundamentally altered the city\'s role. Hong Kong was no longer governed as a civilian colonial port, but as a military occupation centre whose resources, infrastructure, and population were expected to serve Japan\'s wartime objectives.',

    'rule_hk_section_2_title' => 'Establishing the Occupation Government',
    'rule_hk_section_2_p1' => 'Following the occupation, the Japanese administration created a military-civilian governing structure centred on the Hong Kong Occupation Government. Although the new administration assumed responsibility for public administration, policing, judicial functions, economic regulation, and social affairs, its primary purpose remained the support of Japanese military operations. The British administrative system was dismantled. Government buildings, public institutions, police functions, and judicial authority were transferred to Japanese control.',
    'rule_hk_section_2_p2' => 'According to wartime records preserved by the Government Records Service of Hong Kong, the occupation authorities introduced property-registration programmes that recorded ownership, addresses, land values, and building information. Certain streets and districts were renamed using Japanese nomenclature, while buildings and land were requisitioned for military and administrative use.',
    'rule_hk_section_2_p3' => 'These measures reflected more than administrative management. They represented an effort to reshape the urban landscape itself. Streets, buildings, schools, public institutions, and neighbourhoods were systematically reclassified, renamed, and repurposed within the framework of occupation rule.',

    // Model
    'rule_hk_model_section_1_title' => 'A City Governed by Military Priorities',
    'rule_hk_model_section_1_p1' => 'Under Japanese administration, Hong Kong was first and foremost regarded as a strategic military asset. Its harbour, shipyards, warehouses, airport, communications infrastructure, and transportation network were valued primarily for their contribution to Japan\'s military operations across South China and the Pacific. As a result, many aspects of governance became subordinate to military requirements.',
    'rule_hk_model_section_1_p2' => 'Before the war, Hong Kong had functioned as a free port, an international trading centre, and a hub of regional mobility. Under occupation, however, the city increasingly became a controlled logistical base. Ports were used for military transportation, industrial facilities were requisitioned, and civilian movement became subject to curfews, permits, checkpoints, and military oversight.',
    'rule_hk_model_section_1_p3' => 'For ordinary residents, the effects of military rule were felt in everyday life. Travel, employment, business activities, housing, access to food, and even access to information were increasingly regulated. Occupation was not confined to government offices. It extended into markets, streets, schools, police stations, workplaces, and homes.',

    'rule_hk_model_section_2_title' => 'The Kempeitai, Police, and the Politics of Fear',
    'rule_hk_model_section_2_p1' => 'Among the most feared institutions of occupied Hong Kong were the Kempeitai—the Japanese military police—and the broader security apparatus that supported them. To suppress resistance, monitor the population, and maintain control, the Japanese authorities relied upon military police, civilian police, intelligence agents, and local collaborators. House searches, identity checks, arrests, interrogations, and torture became recurring features of life under occupation.',
    'rule_hk_model_section_2_p2' => 'For many residents, the power of the occupation regime rested not only on punishment but on uncertainty. Individuals suspected of sheltering resistance fighters, transmitting intelligence, listening to foreign broadcasts, storing supplies, or associating with the wrong people could attract official attention. Informants and collaborators further deepened public anxiety by creating an atmosphere in which trust became increasingly fragile.',
    'rule_hk_model_section_2_p3' => 'This system of fear served a strategic purpose. It was intended not only to punish resistance but also to discourage it before it occurred. Political discussion became dangerous, assistance to resistance groups became risky, and even private actions could carry significant consequences. Although businesses reopened and daily routines resumed to some extent, many residents lived with a constant awareness that surveillance, investigation, or arrest could occur without warning.',

    'rule_hk_model_section_3_title' => 'Population Control and Forced Repatriation',
    'rule_hk_model_section_3_p1' => 'One of the occupation government\'s most consequential policies was population reduction. Severe food shortages emerged shortly after the occupation began. Unable—or unwilling—to maintain food supplies for Hong Kong\'s pre-war population, the Japanese administration implemented strict rationing and a policy of forced repatriation. According to the Government Records Service, the occupation authorities introduced both rice rationing and population-reduction measures in response to wartime shortages.',
    'rule_hk_model_section_3_p2' => 'Large numbers of unemployed residents, refugees, and individuals without stable access to food were compelled to leave Hong Kong and return to mainland China. For the occupation authorities, reducing the population eased pressure on limited food supplies and simplified administrative control. For affected families, however, the policy often meant separation, displacement, and uncertain journeys through a region already disrupted by war.',
    'rule_hk_model_section_3_p3' => 'The impact on Hong Kong society was profound. Prior to the occupation, the city had absorbed large numbers of refugees, workers, merchants, and intellectuals. During the occupation, population levels declined dramatically as a result of repatriation, hunger, disease, displacement, and death. Neighbourhoods became quieter. Businesses closed. Entire communities were altered. These demographic changes would shape many aspects of wartime life in the years that followed.',

    'rule_hk_model_section_4_title' => 'Registration, Documentation, and Movement Control',
    'rule_hk_model_section_4_p1' => 'Control over movement became another key feature of occupation rule. Residents were increasingly required to carry identity documents, permits, registration papers, and ration cards. Travel between districts often required official authorisation, and access to food or employment could depend upon proper documentation. Without the required papers, individuals risked detention, investigation, or accusations of involvement in resistance activities.',
    'rule_hk_model_section_4_p2' => 'The result was a significant reduction in personal freedom. Routes that had once connected districts, villages, islands, and urban centres became regulated spaces subject to inspection and control. For resistance groups, these measures complicated intelligence gathering and rescue operations. For ordinary residents, even routine travel became more difficult and uncertain.',
    'rule_hk_model_section_4_p3' => 'The permit system also contributed to social inequalities. Those with access to employment, official documentation, or connections to occupation institutions generally found it easier to survive. Those without such advantages faced greater risks of poverty, marginalisation, repatriation, or hunger. Occupation rule thus linked access to basic necessities with administrative compliance and political control.',

    'rule_hk_model_section_5_title' => 'Renaming, Propaganda, and Cultural Assimilation',
    'rule_hk_model_section_5_p1' => 'The Japanese administration sought not only to govern Hong Kong but also to reshape its symbolic landscape. Certain streets and districts received Japanese names. Public spaces displayed imperial propaganda. Schools and newspapers were subjected to censorship and ideological supervision. The Government Records Service notes that street names and place names were altered during the occupation, while property records documented these administrative changes.',
    'rule_hk_model_section_5_p2' => 'These changes were more than bureaucratic adjustments. They formed part of a broader effort to redefine the city\'s identity and integrate it into Japan\'s wartime imperial vision. Language, education, public ceremonies, and media became tools through which the occupation authorities attempted to weaken existing loyalties and promote acceptance of Japanese rule.',
    'rule_hk_model_section_5_p3' => 'Yet official propaganda did not necessarily translate into genuine support. Many residents complied publicly while privately preserving their own views, memories, and identities. Occupation authorities could rename streets and buildings, but they could not entirely erase the fears, grievances, and aspirations that persisted beneath the surface.',

    'rule_hk_model_section_6_title' => 'Local Elites and Collaboration',
    'rule_hk_model_section_6_p1' => 'Managing a city as complex as Hong Kong required more than Japanese personnel alone. The occupation authorities therefore sought assistance from selected Chinese elites, business leaders, community figures, and local intermediaries. Such arrangements reduced administrative burdens while creating the appearance of local participation in governance.',
    'rule_hk_model_section_6_p2' => 'These relationships were often complex and morally ambiguous. Some individuals cooperated in order to protect their families, communities, or businesses. Others actively supported occupation policies and became involved in collaborationist organisations, intelligence work, or law enforcement activities. For resistance groups, local collaborators could be particularly dangerous because of their knowledge of local languages, social networks, and community structures.',
    'rule_hk_model_section_6_p3' => 'As a result, occupied Hong Kong cannot be understood simply as a division between Japanese authorities and local residents. The realities of occupation created difficult choices, competing pressures, and a wide spectrum of responses ranging from resistance to accommodation. The social divisions created during this period would leave lasting scars on the community.',

    'rule_hk_model_section_7_title' => 'The Internment of Foreign Civilians',
    'rule_hk_model_section_7_p1' => 'Foreign civilians also experienced dramatic changes following the occupation. Many British and other Allied civilians were confined in internment camps, the most famous of which was Stanley Internment Camp. Residents of these camps lost their freedom and endured years of uncertainty, shortages, illness, and psychological strain.',
    'rule_hk_model_section_7_p2' => 'The internment system reflected the Japanese government\'s effort to isolate individuals associated with former colonial authorities or enemy nations. While Chinese residents often experienced occupation through rationing, surveillance, forced labour, population controls, and policing measures, foreign civilians were frequently subjected to detention and confinement. Although the experiences differed, both groups lived under the authority of the same occupation regime.',

    'rule_hk_model_section_8_title' => 'Violence as the Foundation of Occupation',
    'rule_hk_model_section_8_p1' => 'Occupation rule was sustained not only through administration but also through the threat of violence. Historical research and post-war testimony document arrests, torture, sexual violence, executions, looting, and other forms of abuse during the occupation period. Even when violence was not immediately visible, its possibility remained ever-present.',
    'rule_hk_model_section_8_p2' => 'For many residents, the greatest burden was uncertainty. The threat could come from Japanese soldiers, military police, informants, collaborationist police, or other agents of the occupation system. In response, many people sought protection through family networks, trusted relationships, and local communities while avoiding unnecessary attention.',
    'rule_hk_model_section_8_p3' => 'This atmosphere of insecurity forms the essential background for understanding later chapters on rationing, economic hardship, survival, and everyday life under occupation. Life under Japanese rule was not merely difficult—it was shaped by the combined pressures of military power, administrative control, and the constant possibility of coercion.',

    'rule_hk_model_section_9_title' => 'Conclusion: A City Under Control',
    'rule_hk_model_section_9_p1' => 'Japanese-occupied Hong Kong was a city fundamentally reshaped by military rule. The Occupation Government, the Kempeitai, police forces, registration systems, population controls, property records, renamed streets, propaganda campaigns, and collaborationist institutions formed an extensive system of control. This system sought to regulate movement, food supplies, employment, housing, language, education, and even public memory. It aimed to transform Hong Kong into a functioning component of Japan\'s wartime machinery.',
    'rule_hk_model_section_9_p2' => 'Yet control did not necessarily produce genuine acceptance. The occupation authorities could seize government offices, rename streets, establish checkpoints, and impose rationing, but they could not eliminate people\'s desire for security, dignity, and freedom. It was precisely because occupation rule was so restrictive that the acts of survival, mutual assistance, and resistance undertaken by Hong Kong\'s people became all the more significant.',

    // tab 2
    'survival_title' => 'Survival and rationing',
    'survival_subtitle' => 'Survival and Rationing in Crisis',
    'survival_intro' => 'One of the most immediate and pressing challenges faced by Hong Kong\'s residents during the Japanese occupation was survival itself. Before the war, Hong Kong depended heavily on imported food and regional trade networks to sustain its population. After the Japanese occupation, transportation routes were disrupted, trade connections severed, and resources requisitioned for military purposes. The city\'s established supply system quickly collapsed.',

    'survival_section_1_title' => 'Living Through Shortage and Uncertainty',
    'survival_section_1_p1' => 'Residents faced not only political repression and military rule, but also the daily struggle to obtain food, fuel, medicine, and other necessities. Questions that had once seemed routine became matters of survival: Was there enough rice? Could fuel be found for cooking? Would medicine still be available? Would there be enough food tomorrow?',
    'survival_section_1_p2' => 'According to exhibition materials produced by the Government Records Service, Hong Kong residents endured severe shortages of food and everyday necessities during the occupation. In response to worsening conditions, the Japanese administration introduced population-reduction measures, strict rice rationing, and compulsory currency conversion into military notes. Although these policies were presented as mechanisms for managing scarce resources, they also increased the population\'s dependence on the occupation authorities. Access to food increasingly depended upon registration, ration tickets, permits, and compliance with official regulations. Those without stable employment, proper documentation, or strong social support networks often found themselves most vulnerable to hunger and displacement.',

    'survival_section_2_title' => 'The Origins of the Food Crisis',
    'survival_section_2_p1' => 'Hong Kong had never been a self-sufficient city. Its dense population and limited agricultural land meant that food supplies depended largely on imports from mainland China and overseas markets. Once war disrupted maritime transport, regional trade, and inland supply routes, food became increasingly scarce. The occupation further intensified these shortages. Japanese military forces and occupation agencies received priority access to available resources, leaving fewer supplies for civilians. The resulting crisis was not simply a consequence of nature or geography. It emerged from a combination of wartime disruption, military requisitioning, economic isolation, and occupation policies.',
    'survival_section_2_p2' => 'As food supplies dwindled, daily life deteriorated rapidly. Rice prices soared. Meat, cooking oil, salt, sugar, fuel, and medicine became increasingly difficult to obtain. Many families reduced the number of meals they ate each day. Rice was stretched into thin porridge, while sweet potatoes, wild vegetables, leaves, and other substitutes became important sources of sustenance. Hunger affected more than physical health. It altered family relationships, economic behaviour, and social priorities. People queued for hours to obtain small amounts of food, exchanged possessions for supplies, sought assistance from relatives, or abandoned the city altogether in search of survival.',

    // Model
    'survival_model_section_1_title' => 'Rice Rationing and Daily Limits',
    'survival_model_section_1_p1' => 'To control food distribution, the Japanese administration introduced a formal rice-rationing system. According to the Government Records Service, by 1942 the daily rice allocation was limited to 6.4 taels per person, distributed through government-issued ration coupons. Rice distribution was restricted to authorised merchants, and contemporary reports in the Hong Kong Daily News indicated that only 57 designated rice dealers operated on Hong Kong Island during this period.',
    'survival_model_section_1_p2' => 'These allocations fell well below normal nutritional requirements. Even residents who possessed ration coupons could not always obtain sufficient food. Long queues, inconsistent quality, and interruptions in supply were common. For labourers, the elderly, children, and those suffering from illness, prolonged undernourishment quickly weakened physical health. Although rationing theoretically guaranteed minimum access to food, it effectively institutionalised scarcity. Daily life became an exercise in calculating how to survive with less than what was needed.',

    'survival_model_section_2_title' => 'Waiting, Queuing, and Uncertainty',
    'survival_model_section_2_p1' => 'Rationing transformed the rhythm of everyday life. Residents often spent hours waiting in line to purchase rice, collect supplies, or obtain information about future distributions. An intelligence report cited by the Government Records Service noted that severe food shortages existed during the early occupation period. Many residents survived on thin rice porridge and waited for hours to obtain rationed rice.',
    'survival_model_section_2_p2' => 'The queue itself became a defining feature of wartime life. Waiting consumed time and energy while generating constant uncertainty. Would supplies run out before reaching the front of the line? Would the ration station close unexpectedly? Would the required documents be accepted? Would prices increase again? For many families, obtaining food became the central concern around which daily life revolved.',

    'survival_model_section_3_title' => 'Forced Repatriation: Reducing the City\'s Population',
    'survival_model_section_3_p1' => 'As shortages intensified, the occupation authorities implemented one of their most controversial policies: population repatriation. According to historical records preserved by the Government Records Service, severe food shortages prompted the Japanese administration to reduce Hong Kong\'s population through organised repatriation programmes. Sources associated with the Hong Kong and Kowloon Brigade further record that occupation authorities sought to expel as many as one million residents, directing many refugees through Yuen Long and onward to Shenzhen.',
    'survival_model_section_3_p2' => 'For the authorities, reducing the population eased pressure on food supplies and simplified administration. For ordinary people, however, repatriation often meant forced displacement. Families were separated. Employment disappeared. Elderly individuals, children, and vulnerable residents faced uncertain journeys through wartime conditions with little guarantee of safety or support. What appeared on paper as a population-management policy became, in practice, a profound humanitarian crisis.',

    'survival_model_section_4_title' => 'From City to Countryside',
    'survival_model_section_4_p1' => 'Under the combined pressures of rationing and repatriation, many residents left urban areas in search of food. The countryside offered no guarantee of comfort, but it sometimes provided access to farmland, fuel, relatives, and local support networks unavailable in the city. This movement altered the social landscape of Hong Kong.',
    'survival_model_section_4_p2' => 'Neighbourhoods that had once been crowded became quieter. Businesses closed. Families dispersed. Meanwhile, villages in the New Territories absorbed increasing numbers of refugees and displaced residents. Some exchanged labour for food. Others depended upon relatives or charitable assistance. Many travelled considerable distances in search of basic necessities. Survival increasingly depended not only on personal effort, but also on whether one had somewhere to go and someone willing to help.',

    'survival_model_section_5_title' => 'The Black Market and the Economy of Exchange',
    'survival_model_section_5_p1' => 'When official supplies proved inadequate, the black market became an important part of everyday survival. Rice, fuel, salt, cooking oil, medicine, cloth, and other essentials could often be obtained through unofficial channels—usually at greatly inflated prices. Families with savings or valuable possessions could exchange jewellery, furniture, clothing, or foreign currency for food. Poorer households frequently exhausted their resources quickly and found themselves with little left to trade.',
    'survival_model_section_5_p2' => 'The black market reflected more than opportunism. It emerged because official distribution systems failed to meet basic needs. For some, it offered a means of survival. For others, it represented exploitation. In either case, it became a central feature of the wartime economy. Many families gradually exchanged years of accumulated possessions for only a few days\' worth of food.',

    'survival_model_section_6_title' => 'Military Currency and Economic Collapse',
    'survival_model_section_6_p1' => 'The Japanese administration required residents to exchange Hong Kong currency for Japanese military notes. According to the Government Records Service, this compulsory currency conversion effectively transferred private wealth into the hands of the occupation authorities. The consequences were severe.',
    'survival_model_section_6_p2' => 'Savings lost value. Confidence in the currency eroded. Inflation intensified. Even residents who possessed money often found that essential goods remained unavailable. In an environment of scarcity, tangible items became more valuable than paper currency. Rice, fuel, medicine, clothing, and permits often carried greater practical value than money itself.',

    'survival_model_section_7_title' => 'Fuel Shortages and the Challenge of Cooking',
    'survival_model_section_7_p1' => 'Food shortages were accompanied by shortages of fuel. The Government Records Service notes that firewood and other fuel sources became increasingly difficult to obtain during the occupation. Even families fortunate enough to acquire rice sometimes lacked the means to cook it.',
    'survival_model_section_7_p2' => 'Residents adapted by preparing thinner meals, cooking in larger batches, collecting firewood, dismantling wooden materials for fuel, and reusing whatever combustible materials they could find. The challenges of daily life extended beyond obtaining food. Cooking, heating, and basic household activities became increasingly difficult under conditions of scarcity.',

    'survival_model_section_8_title' => 'Rooftop Gardens and Self-Help',
    'survival_model_section_8_p1' => 'In response to shortages, many residents sought ways to become more self-reliant. According to the Government Records Service, some residents cultivated vegetables on rooftops during the occupation in an effort to supplement their diets.',
    'survival_model_section_8_p2' => 'Rooftops, courtyards, vacant lots, hillsides, and village land were transformed into small-scale growing areas. These gardens rarely produced enough food to eliminate hunger, but they represented an important form of self-help and resilience. For many families, a small patch of vegetables provided not only nutrition but also hope.',

    'survival_model_section_9_title' => 'Hunger, Disease, and Death',
    'survival_model_section_9_p1' => 'Long-term hunger weakened resistance to disease. Medical supplies were scarce. Hospitals and clinics operated under difficult conditions. Malnutrition, infectious disease, injury, and deteriorating sanitation combined to threaten public health. The Government Records Service records that conditions within internment camps were particularly harsh, with many detainees suffering from malnutrition and illness.',
    'survival_model_section_9_p2' => 'Conditions in rural areas could be equally severe. According to The History of the Hong Kong and Kowloon Brigade, villagers in Chek Keng endured extreme hardship during the occupation. Food shortages became so severe that two residents reportedly died of starvation. Yet even under these conditions, villagers continued to contribute rice to support resistance fighters. Such accounts remind us that hunger was not an abstract statistic—it was a force that shaped daily decisions and, in some cases, determined life and death.',

    'survival_model_section_10_title' => 'Families Under Strain',
    'survival_model_section_10_p1' => 'The burdens of rationing and population control affected different groups in different ways. Young and healthy adults sometimes found opportunities to seek work or relocate. The elderly, children, pregnant women, the sick, and those living alone often faced greater difficulties. Once a household lost its income, savings and possessions could disappear rapidly. Some families sent children to live with relatives. Others sought refuge elsewhere. Many became separated and never reunited.',
    'survival_model_section_10_p2' => 'Under such conditions, the family became the most important unit of survival. Decisions about who would eat first, who would receive limited resources, who would remain, and who would leave were often painful and deeply personal. The suffering of wartime Hong Kong was not measured only in demographic statistics or economic indicators. It was also experienced through countless quiet sacrifices made within individual households.',

    'survival_model_section_11_title' => 'Dignity Amid Scarcity',
    'survival_model_section_11_p1' => 'Perhaps the harshest aspect of rationing was the way it forced people to struggle for the most basic necessities of life. Queuing, registration checks, waiting, rejection, and displacement became part of the occupation experience. Yet survival did not necessarily mean surrender.',
    'survival_model_section_11_p2' => 'Many residents continued to care for their families, assist neighbours, support resistance groups, and preserve hope despite extraordinary hardship. Historical records describe villagers in places such as Chek Kang and Tai Long sharing scarce food supplies with resistance fighters despite facing shortages themselves. Such actions remind us that resistance sometimes took the form of armed struggle—but it could also take the form of generosity, solidarity, and mutual aid during times of hunger.',

    'survival_model_section_12_title' => 'Conclusion: Hong Kong in a Time of Hunger',
    'survival_model_section_12_p1' => 'The rationing system forced Hong Kong\'s residents to confront the limits of survival every day. Food shortages, restricted rice allocations, population repatriation, black-market trading, currency devaluation, fuel scarcity, disease, and displacement combined to create some of the most difficult conditions experienced during the occupation. For many people, war was not experienced primarily through battles or military campaigns. It was experienced through shrinking bowls of rice, hours spent waiting in queues, the loss of savings, the search for fuel, and the difficult decision to leave home in search of survival.',
    'survival_model_section_12_p2' => 'This history reminds us that the damage caused by occupation extended beyond violence and imprisonment. It was also measured in hunger, deprivation, and the gradual erosion of everyday life. The survival of Hong Kong\'s people during these years was not inevitable. It was the result of persistence, sacrifice, mutual support, and a continuous struggle to endure under extraordinarily difficult circumstances.',
    ]
];
